### ISSUE TITLE
Optimized refresh broken

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#10186]
Reported from https://discuss.linuxcontainers.org/t/error-error-transferring-instance-data-failed-getting-instance-storage-pool-name-instance-storage-pool-not-found/13743

This appears to be an issue with optimized refresh, but I am still investigating it.

**Comment by tomponline** [comment]
On source server:

```
root@v1:~# lxc copy c1 v2:c1 --refresh
Error: Failed instance creation: Error transferring instance data: Got error reading source
```

On target server:

```
time="2022-04-05T14:02:11Z" level=debug msg="CreateInstanceFromMigration started" args="{c1  map[] [] {BTRFS [migration_header header_subvolumes header_subvolume_uuids]} true true false 0 }" instance=c1 project=default
time="2022-04-05T14:02:11Z" level=debug msg="Received migration meta data header" driver=btrfs name=c1 pool=btrfs
time="2022-04-05T14:02:11Z" level=debug msg="Sent migration meta data header" driver=btrfs header="{[{/  false 470a9496-200e-3e4f-97b4-bbce220288d4}]}" name=c1 pool=btrfs
time="2022-04-05T14:02:11Z" level=debug msg="Got error reading migration control socket websocket: close 1000 (normal)"
time="2022-04-05T14:02:11Z" level=debug msg="Failure for task operation: 1fdbf2d9-712a-41a1-82bc-07ace679a463: Error transferring instance data: Got error reading source"
time="2022-04-05T14:02:11Z" level=debug msg="Receiving volume" driver=btrfs name=c1 path=/var/snap/lxd/common/lxd/storage-pools/btrfs/containers/c1 pool=btrfs receivePath=/var/snap/lxd/common/lxd/storage-pools/btrfs/containers/migration.1364918867
time="2022-04-05T14:02:11Z" level=debug msg="CreateInstanceFromMigration finished" args="{c1  map[] [] {BTRFS [migration_header header_subvolumes header_subvolume_uuids]} true true false 0 }" instance=c1 project=default
time="2022-04-05T14:02:12Z" level=debug msg="Event listener server handler stopped" listener=5a11cf0f-cedf-4fb7-af17-3429c143a3ef local="10.64.199.30:8443" remote="10.64.199.27:44566"
```

**Comment by manfromafar** [comment]
--refresh for zfs appears to be broken in multiple ways. 
If a failure occurs you are unable to ever send the the container again even after deleting and recreating. 
Resulting error code when trying to send again: 
```
"Error: Failed instance creation: Error transferring instance data: Cannot create volume, already exists on migration target storage"
```
This can be easily reproduced by the following: 
1. Snapshot local container 
   `lxc snapshot container snapshot `
   `lx snapshot container snapshot2`
2. Copy the container to a remote 
    `lxc copy container remote:container` 
3. Snapshot the local container again
   `lxc snapshot container snapshot3`
4. Remove snapshot1 from remote container 
   `lxc delete remote:container/snapshot1`
5. Try to refresh the local container to the remote 
    `lxc copy container remote:container --refresh`
    This will fail with a zfs error about needed to remove the previous snapshots because lxd wants to recopy the entire tree. 
6. Try to do the send again and you'll get the migration error now locked to that container name. 

Reasonable fix
1. LXD should default to syncing only missing snapshots from latest on target to latest on source and not doing a full resync as you may want to keep the older snapshots on the target. 
An additional flag for full resync can be added, this will need to be warned with possible data deletion.  
    lxc already has the ability to check which snapshots exist on the target and can do a simple lookup to see which match on the source

Additional problems caused by failures in --refresh: 

When a copy fails using zfs it leaves  a zfs send running without a actual target. 
This causes other issues when trying to clean up snapshots/containers as you are unable to delete them when a send is running. 


Improvements for zfs send.
1. zfs send should exclude the -c flag unless explicitly asked for in the copy. The inclusion of the -c overrides the targets compression settings and uses the sources instead. Which can cause issues when not expecting the size differences.
I.E. source server runs lz4 compression but target runs zstd-6 compression to save space. 

3. When sending bulk snapshots -I can be used to group all snapshots together instead of sending individually. 
If the snapshots need to be send individually -i can be used to send only the incremental data instead

**Comment by tomponline** [comment]
Thanks @manfromafar 

@monstermunchkin if you're free to take a look at this feel free to self assign as you'll be more familiar with this issue

**Comment by monstermunchkin** [comment]
I believe that falling back onto non-optimized refresh if optimized refresh doesn't work would be a better solution. The reproducer shows a limitation of zfs which we cannot solve unless we use non-optimized refresh. Forcing an optimized refresh and by that basically doing a complete copy isn't an optimization at all.

**Comment by tomponline** [comment]
@monstermunchkin please could you expand a bit on what the limitation is? Is there a way we can detect it early?

**Comment by manfromafar** [comment]
zfs can do the optimized refreshes you just have to play by the rules set out by zfs. 
Instead of lxd trying to resync the entire tree, lxd should instead find the head snapshot of the remote target and the head snapshot of the source and do a incremental from there. Which is 99% of the time what you actually want. 
IF a user actually wants to make the trees mirror then you can add a --force to --refresh or --resync that will force sync the entire tree replacing everything on the remote.

**Comment by monstermunchkin** [comment]
> please could you expand a bit on what the limitation is?

```
lxc init testimage c1 -s zfs-1
# This creates snap0
lxc snapshot c1
# This creates snap1
lxc snapshot c1
lxc copy c1 l2:c1
# This creates snap2
lxc snapshot c1
lxc rm l2:c1/snap0
```

This leaves us with
```
# on the source
zfs-1/containers/c1
zfs-1/containers/c1@snapshot-snap0
zfs-1/containers/c1@snapshot-snap1
zfs-1/containers/c1@snapshot-snap2

# on the target
zfs-2/containers/c1
zfs-2/containers/c1@snapshot-snap1
```

Now, when doing a refresh, the source wants to send `snap0`:
```
# zfs send zfs-1/containers/c1@snapshot-snap0 | zfs receive -F zfs-2/containers/c1
cannot receive new filesystem stream: destination has snapshots (eg. zfs-2/containers/c1@snapshot-snap1)
must destroy them to overwrite it
```

If we deleted `snap1` on the target, the command would succeed. What would also work (as suggested by @manfromafar) is
```
# zfs send -i zfs-1/containers/c1@snapshot-snap1 zfs-1/containers/c1@snapshot-snap2 | zfs receive -F zfs-2/containers/c1
```

> Is there a way we can detect it early?

I believe we could detect missing snapshots which would lead to such a failure. A problem would be that if we fallback to rsync refresh, optimized refresh won't work anymore as the instance snapshots would have been modified.

> Instead of lxd trying to resync the entire tree, lxd should instead find the head snapshot of the remote target and the head snapshot of the source and do a incremental from there. Which is 99% of the time what you actually want.
IF a user actually wants to make the trees mirror then you can add a --force to --refresh or --resync that will force sync the entire tree replacing everything on the remote.

Technically, this would be possible. But this would break our previous behavior, and I don't know if that's what we want.

@stgraber, what's your take on this?

**Comment by stgraber** [comment]
`--refresh` is meant to have the target match the source, any deletion performed on the target should be undone by the next refresh.

**Comment by manfromafar** [comment]
> `--refresh` is meant to have the target match the source, any deletion performed on the target should be undone by the next refresh.

I viewed --refresh more as a way to update changes between two copies of a container hence only coping new snapshots. 

But that also leads me to wonder how broken --refresh is when the target container has more snapshots then the source. 
I assume that scenario also fails but haven't tested

**Comment by tomponline** [comment]
> when the target container has more snapshots then the source.

It should delete them from the target.

**Comment by NeonHorizon** [comment]
It does delete them from the target (or at least did before this bug).
I've been using rotating local snapshots along with an offsite --refresh synced copy of my VM's for quite some time and its been basically replicating what I had locally each time.
[For reference I'm using BTRFS not ZFS]

**Comment by stgraber** [comment]
Yep, that's exactly what this feature is intended for, it lets you sync your instances to another LXD server for backup or for pre-migration. At the end of a refresh, we expect the target to match the source including its snapshot list.

**Comment by tomponline** [comment]
@monstermunchkin can this be closed now?

**Comment by monstermunchkin** [comment]
@tomponline I hope so.

**Comment by tomponline** [comment]
Fixed by:

https://github.com/lxc/lxd/pull/10192
https://github.com/lxc/lxd/pull/10234

**Comment by tomponline** [comment]
Looks like there are still remnant issues with optimized btrfs refresh https://discuss.linuxcontainers.org/t/deleting-container-throws-error-error-could-not-get-subvolume-flags-invalid-argument/13953

**Comment by tomponline** [comment]
Reopening due crash in https://discuss.linuxcontainers.org/t/error-error-transferring-instance-data-failed-getting-instance-storage-pool-name-instance-storage-pool-not-found/13743/50?u=tomp

```
2022-05-05T08:28:44+02:00 lxd.daemon[441075]: time="2022-05-05T08:28:44+02:00" level=debug msg="MigrateInstance started" args="&{archive [] {ZFS [migration_header compress]} true true false <nil>  false true}" instance=archive project=default
2022-05-05T08:28:44+02:00 lxd.daemon[441075]: time="2022-05-05T08:28:44+02:00" level=debug msg="MigrateInstance finished" args="&{archive [] {ZFS [migration_header compress]} true true false map[filesystem:dpool/lxd/containers/archive@migration-e049046a-1feb-49fa-87d8-0ec8b4b9fe44]  false true}" instance=archive project=default
2022-05-05T08:28:44+02:00 lxd.daemon[441075]: time="2022-05-05T08:28:44+02:00" level=debug msg="MigrateInstance started" args="&{archive [] {ZFS [migration_header compress]} true true true map[filesystem:dpool/lxd/containers/archive@migration-e049046a-1feb-49fa-87d8-0ec8b4b9fe44]  false true}" instance=archive project=default
2022-05-05T08:28:45+02:00 lxd.daemon[441075]: time="2022-05-05T08:28:45+02:00" level=debug msg="MigrateInstance finished" args="&{archive [] {ZFS [migration_header compress]} true true true map[filesystem:dpool/lxd/containers/archive@migration-e049046a-1feb-49fa-87d8-0ec8b4b9fe44]  false true}" instance=archive project=default
2022-05-05T08:28:45+02:00 lxd.daemon[441075]: panic: runtime error: slice bounds out of range [:-1]
2022-05-05T08:28:45+02:00 lxd.daemon[441075]: goroutine 7832 [running]:
2022-05-05T08:28:45+02:00 lxd.daemon[441075]: io.ReadAll({0x7f5de0516e70, 0xc0016a5d80})
2022-05-05T08:28:45+02:00 lxd.daemon[441075]: 	/snap/go/9605/src/io/io.go:646 +0x197
2022-05-05T08:28:45+02:00 lxd.daemon[441075]: io/ioutil.ReadAll(...)
2022-05-05T08:28:45+02:00 lxd.daemon[441075]: 	/snap/go/9605/src/io/ioutil/ioutil.go:27
2022-05-05T08:28:45+02:00 lxd.daemon[441075]: github.com/lxc/lxd/lxd/storage/drivers.(*zfs).MigrateVolume(0xc0004c2a50, {{0xc00127e470, 0x7}, {0xc000fe0af0, 0x7}, 0xc000f40360, {0x188a56e, 0xa}, {0x188a9ce, 0xa}, ...}, ...)
2022-05-05T08:28:45+02:00 lxd.daemon[441075]: 	/build/lxd/parts/lxd/src/lxd/storage/drivers/driver_zfs_volumes.go:1900 +0x672
2022-05-05T08:28:45+02:00 lxd.daemon[441075]: github.com/lxc/lxd/lxd/storage.(*lxdBackend).MigrateInstance(0xc000377a40, {0x1baf778, 0xc0004c0000}, {0x1b96140, 0xc0016a5d80}, 0xc000a40f80, 0x0?)
2022-05-05T08:28:45+02:00 lxd.daemon[441075]: 	/build/lxd/parts/lxd/src/lxd/storage/backend_lxd.go:2176 +0x753
2022-05-05T08:28:45+02:00 lxd.daemon[441075]: main.(*migrationSourceWs).Do(0xc000238a00, 0xc0003fe420, 0x0?)
2022-05-05T08:28:45+02:00 lxd.daemon[441075]: 	/build/lxd/parts/lxd/src/lxd/migrate_instance.go:712 +0x1850
2022-05-05T08:28:45+02:00 lxd.daemon[441075]: main.instancePost.func5(0x0?)
2022-05-05T08:28:45+02:00 lxd.daemon[441075]: 	/build/lxd/parts/lxd/src/lxd/instance_post.go:315 +0x45
2022-05-05T08:28:45+02:00 lxd.daemon[441075]: github.com/lxc/lxd/lxd/operations.(*Operation).Run.func1(0xc0003be360, 0xc00175a200?)
2022-05-05T08:28:45+02:00 lxd.daemon[441075]: 	/build/lxd/parts/lxd/src/lxd/operations/operations.go:280 +0x42
2022-05-05T08:28:45+02:00 lxd.daemon[441075]: created by github.com/lxc/lxd/lxd/operations.(*Operation).Run
2022-05-05T08:28:45+02:00 lxd.daemon[441075]: 	/build/lxd/parts/lxd/src/lxd/operations/operations.go:279 +0x118
2022-05-05T08:28:45+02:00 lxd.daemon[440924]: => LXD failed with return code 2
```

**Comment by monstermunchkin** [comment]
This error can be reproduced by running:
1. `lxc launch images:alpine/edge c1`
2. `lxc snapshot c1`
3. `lxc copy c1 l2:c1 --stateless`
4. `lxc copy c1 l2:c1 --stateless --refresh`

**Comment by tomponline** [comment]
> This error can be reproduced by running:
> 
>     1. `lxc launch images:alpine/edge c1`
> 
>     2. `lxc snapshot c1`
> 
>     3. `lxc copy c1 l2:c1 --stateless`
> 
>     4. `lxc copy c1 l2:c1 --stateless --refresh`

Please can you update the tests with this scenario? Thanks

**Comment by tomponline** [comment]
@stgraber going to keep this open until the tests for the latest fix have landed so we can keep track of it.

**Comment by tomponline** [comment]
Having to re-open this again as found another issue:

With ZFS storage pools:
```
lxc storage volume copy l1:vol1 l2:vol2 --refresh
lxc storage volume snapshot 
lxc storage volume copy l1:vol1 l2:vol2 --refresh # hangs
```

**Comment by monstermunchkin** [comment]
> Having to re-open this again as found another issue:
> 
> With ZFS storage pools:
> 
> ```
> lxc storage volume copy l1:vol1 l2:vol2 --refresh
> lxc storage volume snapshot 
> lxc storage volume copy l1:vol1 l2:vol2 --refresh # hangs
> ```
> 
> See https://github.com/lxc/lxd/pull/10437/files#diff-5bc3cb620bcc6c06dad35b1d41367a25311c1e75e804ba270a84c48dab80347aR339-R347 for example.

This doesn't seem to hang anymore. Tested it with:

```
$ lxc storage volume create zfs vol3
Storage volume vol3 created
$ lxc storage volume copy zfs/vol3 l2:zfs/vol2
Storage volume copied successfully!
$ lxc storage volume snapshot zfs vol3
$ lxc storage volume snapshot zfs vol3
$ lxc storage volume snapshot zfs vol3
$ lxc storage volume copy zfs/vol3 l2:zfs/vol2 --refresh
Storage volume copied successfully!
```

**Comment by stgraber** [comment]
Tentatively closing this one again.

**Comment by monstermunchkin** [comment]
Yes, I can confirm this. After going through the test, I could create a short reproducer:
```go
lxc storage volume create l1:zfs vol1
lxc storage volume snapshot l1:zfs vol1
lxc storage volume snapshot l1:zfs vol1

lxc storage volume copy l1:zfs/vol1 l2:zfs/vol2

lxc storage volume create l1:zfs vol3
lxc storage volume snapshot l1:zfs vol3
lxc storage volume snapshot l1:zfs vol3
lxc storage volume snapshot l1:zfs vol3
lxc storage volume copy l1:zfs/vol3 l2:zfs/vol2 --refresh
```

**Comment by tomponline** [comment]
https://github.com/lxc/lxd/issues/10568

**Comment by tomponline** [comment]
https://github.com/lxc/lxd/issues/11308
