### ISSUE TITLE
lxc remote add fails with EOF when posting to /1.0/certificates

### ISSUE THREAD

**Issue by rrva** [lxc/lxd#1058]
In 0.16, when I enable listening over HTTPS with

    lxc config set core.https_address [::]:8443
    lxc config set core.trust_password blah

On the same machine as lxd runs:

    lxc remote add localhost localhost

I get

lxc remote add localhost localhost
Admin password for localhost:
error: Post https://localhost:8443/1.0/certificates: EOF

lxd logfile

```
INFO[08-29|11:53:26] LXD is starting                          path=/var/lib/lxd
INFO[08-29|11:53:26] Default uid/gid map:
INFO[08-29|11:53:26]  - u 0 100000 65536
INFO[08-29|11:53:26]  - g 0 100000 65536
INFO[08-29|11:53:26] Init                                     driver=storage/btrfs
INFO[08-29|11:53:26] Looking for existing certificates:       cert=/var/lib/lxd/server.crt key=/var/lib/lxd/server.key
INFO[08-29|11:53:26] LXD isn't socket activated
INFO[08-29|11:53:26] REST API daemon:
INFO[08-29|11:53:26]  - binding socket                        socket=/var/lib/lxd/unix.socket
INFO[08-29|11:53:26]  - binding socket                        socket=[::]:8443
INFO[08-29|11:53:41] allowing untrusted GET                   url=/1.0 ip=127.0.0.1:39063
DBUG[08-29|11:53:41]
        {
                "type": "sync",
                "status": "Success",
                "status_code": 200,
                "metadata": {
                        "api_compat": 1,
                        "auth": "untrusted"
                }
        }
INFO[08-29|11:53:41] allowing untrusted GET                   ip=127.0.0.1:39063 url=/1.0
DBUG[08-29|11:53:41]
        {
                "type": "sync",
                "status": "Success",
                "status_code": 200,
                "metadata": {
                        "api_compat": 1,
                        "auth": "untrusted"
                }
        }
INFO[08-29|11:53:44] allowing untrusted POST                  url=/1.0/certificates ip=127.0.0.1:39063
DBUG[08-29|11:53:44]
        {
                "password": "blah",
                "type": "client"
        }
2015/08/29 11:53:44 http: panic serving 127.0.0.1:39063: runtime error: slice bounds out of range
goroutine 50 [running]:
net/http.(*conn).serve.func1(0xc820258000, 0x7f54c7f94088, 0xc820256000)
        /usr/local/go/src/net/http/server.go:1287 +0xb5
main.(*Daemon).PasswordCheck(0xc82009fb80, 0xc8201be510, 0x4, 0x9)
        /home/vagrant/go/src/github.com/lxc/lxd/lxd/daemon.go:955 +0x953
main.certificatesPost(0xc82009fb80, 0xc82000c2a0, 0x0, 0x0)
        /home/vagrant/go/src/github.com/lxc/lxd/lxd/daemon.go:955 +0x953                                                                               
main.certificatesPost(0xc82009fb80, 0xc82000c2a0, 0x0, 0x0)
        /home/vagrant/go/src/github.com/lxc/lxd/lxd/certificates.go:144 +0x4f2
main.(*Daemon).createCmd.func1(0x7f54c7f9c930, 0xc820258160, 0xc82000c2a0)
        /home/vagrant/go/src/github.com/lxc/lxd/lxd/daemon.go:266 +0x80d
net/http.HandlerFunc.ServeHTTP(0xc820199f90, 0x7f54c7f9c930, 0xc820258160, 0xc82000c2a0)
        /usr/local/go/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc820198690, 0x7f54c7f9c930, 0xc820258160, 0xc82000c2a0)
        /home/vagrant/go/src/github.com/gorilla/mux/mux.go:100 +0x29e
net/http.serverHandler.ServeHTTP(0xc82022c480, 0x7f54c7f9c930, 0xc820258160, 0xc82000c2a0)
        /usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc820258000)
        /usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:1910 +0x3f6
```

**Comment by rrva** [comment]
Nevermind, password was not set. The PasswordCheck function could log this.

**Comment by tych0** [comment]
Sorry, can we reopen this and fix it with a better error message?

**Comment by stgraber** [comment]
yup, getting a stacktrace is never a good thing :)
