### ISSUE TITLE
panic: concurrent write to websocket connection

### ISSUE THREAD

**Issue by omani** [lxc/lxd#11174]
LXD server 5.8 freshly built from source:

```
$ sudo lxd --group wheel
WARNING[2022-11-30T03:54:07+03:00] AppArmor support has been disabled because of lack of kernel support
WARNING[2022-11-30T03:54:07+03:00]  - AppArmor support has been disabled, Disabled because of lack of kernel support
WARNING[2022-11-30T03:54:07+03:00]  - Couldn't find the CGroup network priority controller, network priority will be ignored
WARNING[2022-11-30T03:54:07+03:00]  - Couldn't find the CGroup memory swap accounting, swap limits will be ignored
panic: concurrent write to websocket connection

goroutine 11257 [running]:
github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc000e6bef8, 0x1, {0xc000eb49f7?, 0x7f4627da05b8?, 0xc000199b80?})
        /home/sun/.local/share/go/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:617 +0x52b
github.com/gorilla/websocket.(*Conn).WriteMessage(0xc00019a000, 0xc0000b27f0?, {0xc000eb49f7, 0x1, 0x1})
        /home/sun/.local/share/go/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:770 +0x139
github.com/lxc/lxd/shared.WebsocketConsoleMirror.func1(0x3195950?, {0x1fa3280?, 0xc0000b27f0})
        /home/sun/git/lxd/shared/network.go:481 +0x1c5
created by github.com/lxc/lxd/shared.WebsocketConsoleMirror
        /home/sun/git/lxd/shared/network.go:474 +0x1aa

```

the software LXDware caused LXD to panic. I hit the button "Start exec" on the container page and LXD went down.

![2022-11-30-040758_1426x934_scrot](https://user-images.githubusercontent.com/3346207/204682759-4e3fcaf8-7336-4cb5-a269-25d76b22363a.png)

```golang
func WebsocketConsoleMirror(conn *websocket.Conn, w io.WriteCloser, r io.ReadCloser) (chan bool, chan bool) {
	readDone := make(chan bool, 1)
	writeDone := make(chan bool, 1)

	go DefaultWriter(conn, w, writeDone)

	go func(conn *websocket.Conn, r io.ReadCloser) {
		in := ReaderToChannel(r, -1)
		for {
			buf, ok := <-in
			if !ok {
				_ = r.Close()
				logger.Debugf("Sending write barrier")
				_ = conn.WriteMessage(websocket.BinaryMessage, []byte("\r"))
				_ = conn.WriteMessage(websocket.TextMessage, []byte{})
				readDone <- true
				return
			}

			err := conn.WriteMessage(websocket.BinaryMessage, buf)
			if err != nil {
				logger.Debugf("Got err writing %s", err)
				break
			}
		}

		closeMsg := websocket.FormatCloseMessage(websocket.CloseNormalClosure, "")
		_ = conn.WriteMessage(websocket.CloseMessage, closeMsg)
		readDone <- true
		_ = r.Close()
	}(conn, r)

	return readDone, writeDone
}
```

https://pkg.go.dev/github.com/gorilla/websocket?utm_source=godoc#hdr-Concurrency

maybe you want a mutex here.

**Comment by tomponline** [comment]
Strange you got an error from `WebsocketConsoleMirror` when pressing on the `Exec` tab, I would have thought you would have got it when pressing on the `Console` tab. Had you pressed the `Console` tab first and then click on the `Exec` tab? Perhaps it was the disconnection of a partially setup console that causes it?

**Comment by tomponline** [comment]
Is this reliably reproducible or does it only happens sometimes?

**Comment by omani** [comment]
> Strange you got an error from `WebsocketConsoleMirror` when pressing the `Start Exec` button in the `Exec` tab, I would have thought you would have got it when pressing on the `Console` tab. Had you pressed the `Console` tab first and then click on the `Exec` tab? Perhaps it was the disconnection of a partially setup console that causes it?

yes I clicked on the console first. then closed the connection there (or maybe not, cant remember) and then tested the exec tab.

I dont know much about lxdware since I am evaluating to see if it fits my needs. but yeah I remember that's the order I clicked on the buttons. first console, then exec.

no I cant reproduce it anymore, no matter which order:
- leave console open, start exec
- open close console, start exec
- open close console, start stop exec start
- rapid start stop exec

so far it happened only once.
