### ISSUE TITLE
lxc config edit hangs lxd

### ISSUE THREAD

**Issue by jsimonetti** [lxc/lxd#1124]
When editing the container configuration and pasting the following content into the configuration, lxd hangs.

Content to paste:
```
  raw.lxc: |-
    lxc.cgroup.memory.memsw.limit_in_bytes: 2G
    lxc.cgroup.cpu.shares: 1024
```

I only then realised I had the format wrong and should have used = instead of :.

Version detail:
Running latest test version of Ubuntu 15.10

lxc    1.1.3-0ubuntu1    amd64
lxd    0.18-0ubuntu2    amd64

**Comment by cuihaoleo** [comment]
Same here. lxd 0.18-0ubuntu2~ubuntu15.04.1~ppa1 from lxc-stable PPA.

Try directly talk with restful api:

    curl -E client.crt --key client.key --insecure https://127.0.0.1:8443/1.0/containers/test -X PUT --data '{}'

lxd service hangs and print backtrace:
```
Sep 22 22:14:20 lxc lxd[6651]: t=2015-09-22T22:14:20+0800 lvl=dbug msg="Found cert" k=0
Sep 22 22:14:20 lxc lxd[6651]: t=2015-09-22T22:14:20+0800 lvl=info msg=handling url=/1.0/containers/test ip=127.0.0.1:60613 method=PUT
Sep 22 22:14:20 lxc lxd[6651]: t=2015-09-22T22:14:20+0800 lvl=dbug msg="Container load" container=test
Sep 22 22:14:20 lxc lxd[6651]: t=2015-09-22T22:14:20+0800 lvl=dbug msg="\n\t{\n\t\t\"type\": \"async\",\n\t\t\"status\": \"OK\",\n\t\t\"status_code\": 100,\n\t\t\"operation\": \"/1.0/operations/0c72f81b-5a1d-4571-bbdd-2f26f5c3ce21\",\n\t\t\"resources\": null,\n\t\t\"metadata\": null\n\t}"
Sep 22 22:14:20 lxc lxd[6651]: panic: assignment to entry in nil map
Sep 22 22:14:20 lxc lxd[6651]: goroutine 13 [running]:
Sep 22 22:14:20 lxc lxd[6651]: github.com/lxc/lxd/shared.Devices.ExtendFromProfile(0x0, 0xc8201af7a0, 0xc8200c6ea0, 0x0, 0x0)
Sep 22 22:14:20 lxc lxd[6651]: /build/lxd-XknFpQ/lxd-0.18/dist/src/github.com/lxc/lxd/shared/devices.go:114 +0x20d
Sep 22 22:14:20 lxc lxd[6651]: main.(*containerLXD).ConfigReplace(0xc820207b00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Sep 22 22:14:20 lxc lxd[6651]: /build/lxd-XknFpQ/lxd-0.18/dist/src/github.com/lxc/lxd/lxd/container.go:1164 +0xc11
Sep 22 22:14:20 lxc lxd[6651]: main.containerPut.func2(0x0, 0x0)
Sep 22 22:14:20 lxc lxd[6651]: /build/lxd-XknFpQ/lxd-0.18/dist/src/github.com/lxc/lxd/lxd/container_put.go:38 +0xbf
Sep 22 22:14:20 lxc lxd[6651]: github.com/lxc/lxd/shared.OperationWrap.func1(0x0, 0x0, 0x0, 0x0, 0x0)
Sep 22 22:14:20 lxc lxd[6651]: /build/lxd-XknFpQ/lxd-0.18/dist/src/github.com/lxc/lxd/shared/operation.go:45 +0x37
Sep 22 22:14:20 lxc lxd[6651]: main.startOperation.func1(0xc82017be00)
Sep 22 22:14:20 lxc lxd[6651]: /build/lxd-XknFpQ/lxd-0.18/dist/src/github.com/lxc/lxd/lxd/operations.go:69 +0x30
Sep 22 22:14:20 lxc lxd[6651]: created by main.startOperation
Sep 22 22:14:20 lxc lxd[6651]: /build/lxd-XknFpQ/lxd-0.18/dist/src/github.com/lxc/lxd/lxd/operations.go:76 +0x1f5
Sep 22 22:14:20 lxc lxd[6651]: goroutine 1 [semacquire, 2 minutes]:
Sep 22 22:14:20 lxc lxd[6651]: sync.runtime_Semacquire(0xc82017598c)
Sep 22 22:14:20 lxc lxd[6651]: /usr/lib/go/src/runtime/sema.go:43 +0x26
Sep 22 22:14:20 lxc lxd[6651]: sync.(*WaitGroup).Wait(0xc820175980)
Sep 22 22:14:20 lxc lxd[6651]: /usr/lib/go/src/sync/waitgroup.go:126 +0xb4
Sep 22 22:14:20 lxc lxd[6651]: main.run(0x0, 0x0)
Sep 22 22:14:20 lxc lxd[6651]: /build/lxd-XknFpQ/lxd-0.18/dist/src/github.com/lxc/lxd/lxd/main.go:201 +0xc29
Sep 22 22:14:20 lxc lxd[6651]: main.main()
Sep 22 22:14:20 lxc lxd[6651]: /build/lxd-XknFpQ/lxd-0.18/dist/src/github.com/lxc/lxd/lxd/main.go:41 +0x24
Sep 22 22:14:20 lxc lxd[6651]: goroutine 17 [syscall, 2 minutes, locked to thread]:
Sep 22 22:14:20 lxc lxd[6651]: runtime.goexit()
Sep 22 22:14:20 lxc lxd[6651]: /usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1
Sep 22 22:14:20 lxc lxd[6651]: goroutine 5 [syscall, 2 minutes]:
Sep 22 22:14:20 lxc lxd[6651]: os/signal.loop()
Sep 22 22:14:20 lxc lxd[6651]: /usr/lib/go/src/os/signal/signal_unix.go:22 +0x18
Sep 22 22:14:20 lxc lxd[6651]: created by os/signal.init.1
Sep 22 22:14:20 lxc lxd[6651]: /usr/lib/go/src/os/signal/signal_unix.go:28 +0x37
Sep 22 22:14:20 lxc lxd[6651]: goroutine 6 [chan receive, 2 minutes]:
Sep 22 22:14:20 lxc lxd[6651]: database/sql.(*DB).connectionOpener(0xc820099f40)
Sep 22 22:14:20 lxc lxd[6651]: /usr/lib/go/src/database/sql/sql.go:634 +0x45
Sep 22 22:14:20 lxc lxd[6651]: created by database/sql.Open
Sep 22 22:14:20 lxc lxd[6651]: /usr/lib/go/src/database/sql/sql.go:481 +0x336
Sep 22 22:14:20 lxc lxd[6651]: goroutine 7 [select, 2 minutes]:
Sep 22 22:14:20 lxc lxd[6651]: main.(*Daemon).Init.func1(0xc82009bb80)
Sep 22 22:14:20 lxc lxd[6651]: /build/lxd-XknFpQ/lxd-0.18/dist/src/github.com/lxc/lxd/lxd/daemon.go:607 +0x17e
Sep 22 22:14:20 lxc lxd[6651]: created by main.(*Daemon).Init
Sep 22 22:14:20 lxc systemd[1]: lxd.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 22 22:14:20 lxc lxd[6651]: /build/lxd-XknFpQ/lxd-0.18/dist/src/github.com/lxc/lxd/lxd/daemon.go:615 +0xea5
Sep 22 22:14:20 lxc lxd[6651]: goroutine 21 [chan receive, 2 minutes]:
Sep 22 22:14:20 lxc lxd[6651]: main.run.func3(0xc82009bb80, 0xc820175970, 0xc820175980)
Sep 22 22:14:20 lxc lxd[6651]: /build/lxd-XknFpQ/lxd-0.18/dist/src/github.com/lxc/lxd/lxd/main.go:178 +0x16e
Sep 22 22:14:20 lxc lxd[6651]: created by main.run
Sep 22 22:14:20 lxc lxd[6651]: /build/lxd-XknFpQ/lxd-0.18/dist/src/github.com/lxc/lxd/lxd/main.go:187 +0xbe5
Sep 22 22:14:20 lxc lxd[6651]: goroutine 22 [chan receive, 2 minutes]:
Sep 22 22:14:20 lxc lxd[6651]: main.run.func4(0xc820175970, 0xc82009bb80, 0xc820175980)
Sep 22 22:14:20 lxc lxd[6651]: /build/lxd-XknFpQ/lxd-0.18/dist/src/github.com/lxc/lxd/lxd/main.go:194 +0x354
Sep 22 22:14:20 lxc lxd[6651]: created by main.run
Sep 22 22:14:20 lxc lxd[6651]: /build/lxd-XknFpQ/lxd-0.18/dist/src/github.com/lxc/lxd/lxd/main.go:199 +0xc1b
Sep 22 22:14:20 lxc lxd[6651]: goroutine 23 [select, 2 minutes, locked to thread]:
Sep 22 22:14:20 lxc lxd[6651]: runtime.gopark(0xcda178, 0xc82001ff28, 0xb1d518, 0x6, 0x56fb18, 0x2)
Sep 22 22:14:20 lxc lxd[6651]: /usr/lib/go/src/runtime/proc.go:185 +0x163
Sep 22 22:14:20 lxc lxd[6651]: runtime.selectgoImpl(0xc82001ff28, 0x0, 0x18)
Sep 22 22:14:20 lxc lxd[6651]: /usr/lib/go/src/runtime/select.go:392 +0xa64
Sep 22 22:14:20 lxc lxd[6651]: runtime.selectgo(0xc82001ff28)
Sep 22 22:14:20 lxc lxd[6651]: /usr/lib/go/src/runtime/select.go:212 +0x12
Sep 22 22:14:20 lxc lxd[6651]: runtime.ensureSigM.func1()
Sep 22 22:14:20 lxc lxd[6651]: /usr/lib/go/src/runtime/signal1_unix.go:227 +0x353
Sep 22 22:14:20 lxc lxd[6651]: runtime.goexit()
Sep 22 22:14:20 lxc lxd[6651]: /usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1
Sep 22 22:14:20 lxc lxd[6651]: goroutine 34 [IO wait, 2 minutes]:
Sep 22 22:14:20 lxc lxd[6651]: net.runtime_pollWait(0x7fc1e1da5b80, 0x72, 0xc82000e190)
Sep 22 22:14:20 lxc lxd[6651]: /usr/lib/go/src/runtime/netpoll.go:157 +0x60
Sep 22 22:14:20 lxc lxd[6651]: net.(*pollDesc).Wait(0xc820177640, 0x72, 0x0, 0x0)
Sep 22 22:14:20 lxc lxd[6651]: /usr/lib/go/src/net/fd_poll_runtime.go:73 +0x3a
Sep 22 22:14:20 lxc lxd[6651]: net.(*pollDesc).WaitRead(0xc820177640, 0x0, 0x0)
Sep 22 22:14:20 lxc lxd[6651]: /usr/lib/go/src/net/fd_poll_runtime.go:78 +0x36
Sep 22 22:14:20 lxc lxd[6651]: net.(*netFD).accept(0xc8201775e0, 0x0, 0x7fc1e1db2b68, 0xc8200cc060)
Sep 22 22:14:20 lxc lxd[6651]: /usr/lib/go/src/net/fd_unix.go:408 +0x27c
Sep 22 22:14:20 lxc lxd[6651]: net.(*UnixListener).AcceptUnix(0xc820169120, 0xc82018ce10, 0x0, 0x0)
Sep 22 22:14:20 lxc lxd[6651]: /usr/lib/go/src/net/unixsock_posix.go:304 +0x53
Sep 22 22:14:20 lxc lxd[6651]: net.(*UnixListener).Accept(0xc820169120, 0x0, 0x0, 0x0, 0x0)
Sep 22 22:14:20 lxc lxd[6651]: /usr/lib/go/src/net/unixsock_posix.go:314 +0x41
Sep 22 22:14:20 lxc lxd[6651]: net/http.(*Server).Serve(0xc8201ba000, 0x7fc1e013bd98, 0xc820169120, 0x0, 0x0)
Sep 22 22:14:20 lxc lxd[6651]: /usr/lib/go/src/net/http/server.go:1887 +0xb3
Sep 22 22:14:20 lxc lxd[6651]: net/http.Serve(0x7fc1e013bd98, 0xc820169120, 0x7fc1e1db2b40, 0xc820129a40, 0x0, 0x0)
Sep 22 22:14:20 lxc lxd[6651]: /usr/lib/go/src/net/http/server.go:1765 +0x85
Sep 22 22:14:20 lxc systemd[1]: Unit lxd.service entered failed state.
Sep 22 22:14:20 lxc systemd[1]: lxd.service failed.
Sep 22 22:14:20 lxc lxd[6651]: main.(*Daemon).Init.func4.1(0x0, 0x0)
Sep 22 22:14:20 lxc lxd[6651]: /build/lxd-XknFpQ/lxd-0.18/dist/src/github.com/lxc/lxd/lxd/daemon.go:766 +0x7d
Sep 22 22:14:20 lxc lxd[6651]: gopkg.in/tomb%2ev2.(*Tomb).run(0xc82009bc08, 0xc8201ae060)
Sep 22 22:14:20 lxc lxd[6651]: /build/lxd-XknFpQ/lxd-0.18/dist/src/gopkg.in/tomb.v2/tomb.go:153 +0x21
Sep 22 22:14:20 lxc lxd[6651]: created by gopkg.in/tomb%2ev2.(*Tomb).Go
Sep 22 22:14:20 lxc lxd[6651]: /build/lxd-XknFpQ/lxd-0.18/dist/src/gopkg.in/tomb.v2/tomb.go:149 +0x131
Sep 22 22:14:20 lxc lxd[6651]: goroutine 35 [IO wait]:
Sep 22 22:14:20 lxc lxd[6651]: net.runtime_pollWait(0x7fc1e1da5ac0, 0x72, 0xc82000e190)
Sep 22 22:14:20 lxc lxd[6651]: /usr/lib/go/src/runtime/netpoll.go:157 +0x60
Sep 22 22:14:20 lxc lxd[6651]: net.(*pollDesc).Wait(0xc820177a30, 0x72, 0x0, 0x0)
Sep 22 22:14:20 lxc lxd[6651]: /usr/lib/go/src/net/fd_poll_runtime.go:73 +0x3a
Sep 22 22:14:20 lxc lxd[6651]: net.(*pollDesc).WaitRead(0xc820177a30, 0x0, 0x0)
Sep 22 22:14:20 lxc lxd[6651]: /usr/lib/go/src/net/fd_poll_runtime.go:78 +0x36
Sep 22 22:14:20 lxc lxd[6651]: net.(*netFD).accept(0xc8201779d0, 0x0, 0x7fc1e1db2b68, 0xc82019c100)
Sep 22 22:14:20 lxc lxd[6651]: /usr/lib/go/src/net/fd_unix.go:408 +0x27c
Sep 22 22:14:20 lxc lxd[6651]: net.(*TCPListener).AcceptTCP(0xc8200262f0, 0xc820124000, 0x0, 0x0)
Sep 22 22:14:20 lxc lxd[6651]: /usr/lib/go/src/net/tcpsock_posix.go:254 +0x4d
Sep 22 22:14:20 lxc lxd[6651]: net.(*TCPListener).Accept(0xc8200262f0, 0x0, 0x0, 0x0, 0x0)
Sep 22 22:14:20 lxc lxd[6651]: /usr/lib/go/src/net/tcpsock_posix.go:264 +0x3d
Sep 22 22:14:20 lxc lxd[6651]: crypto/tls.(*listener).Accept(0xc8201692c0, 0x0, 0x0, 0x0, 0x0)
Sep 22 22:14:20 lxc lxd[6651]: /usr/lib/go/src/crypto/tls/tls.go:46 +0x60
Sep 22 22:14:20 lxc lxd[6651]: net/http.(*Server).Serve(0xc8201842a0, 0x7fc1e013bea8, 0xc8201692c0, 0x0, 0x0)
Sep 22 22:14:20 lxc lxd[6651]: /usr/lib/go/src/net/http/server.go:1887 +0xb3
Sep 22 22:14:20 lxc lxd[6651]: net/http.Serve(0x7fc1e013bea8, 0xc8201692c0, 0x7fc1e1db2b40, 0xc820129a40, 0x0, 0x0)
Sep 22 22:14:20 lxc lxd[6651]: /usr/lib/go/src/net/http/server.go:1765 +0x85
Sep 22 22:14:20 lxc lxd[6651]: main.(*Daemon).Init.func4.1(0x0, 0x0)
Sep 22 22:14:20 lxc lxd[6651]: /build/lxd-XknFpQ/lxd-0.18/dist/src/github.com/lxc/lxd/lxd/daemon.go:766 +0x7d
Sep 22 22:14:20 lxc lxd[6651]: gopkg.in/tomb%2ev2.(*Tomb).run(0xc82009bc08, 0xc8201ae0c0)
Sep 22 22:14:20 lxc lxd[6651]: /build/lxd-XknFpQ/lxd-0.18/dist/src/gopkg.in/tomb.v2/tomb.go:153 +0x21
Sep 22 22:14:20 lxc lxd[6651]: created by gopkg.in/tomb%2ev2.(*Tomb).Go
Sep 22 22:14:20 lxc lxd[6651]: /build/lxd-XknFpQ/lxd-0.18/dist/src/gopkg.in/tomb.v2/tomb.go:149 +0x131
Sep 22 22:14:20 lxc lxd[6651]: goroutine 36 [IO wait, 2 minutes]:
Sep 22 22:14:20 lxc lxd[6651]: net.runtime_pollWait(0x7fc1e1da5c40, 0x72, 0xc82000e190)
Sep 22 22:14:20 lxc lxd[6651]: /usr/lib/go/src/runtime/netpoll.go:157 +0x60
Sep 22 22:14:20 lxc lxd[6651]: net.(*pollDesc).Wait(0xc8200d9f00, 0x72, 0x0, 0x0)
Sep 22 22:14:20 lxc lxd[6651]: /usr/lib/go/src/net/fd_poll_runtime.go:73 +0x3a
Sep 22 22:14:20 lxc lxd[6651]: net.(*pollDesc).WaitRead(0xc8200d9f00, 0x0, 0x0)
Sep 22 22:14:20 lxc lxd[6651]: /usr/lib/go/src/net/fd_poll_runtime.go:78 +0x36
Sep 22 22:14:20 lxc lxd[6651]: net.(*netFD).accept(0xc8200d9ea0, 0x0, 0x7fc1e1db2b68, 0xc82019c980)
Sep 22 22:14:20 lxc lxd[6651]: /usr/lib/go/src/net/fd_unix.go:408 +0x27c
Sep 22 22:14:20 lxc lxd[6651]: net.(*UnixListener).AcceptUnix(0xc8200cd8a0, 0xc8200b7d80, 0x0, 0x0)
Sep 22 22:14:20 lxc lxd[6651]: /usr/lib/go/src/net/unixsock_posix.go:304 +0x53
Sep 22 22:14:20 lxc lxd[6651]: net.(*UnixListener).Accept(0xc8200cd8a0, 0x0, 0x0, 0x0, 0x0)
Sep 22 22:14:20 lxc lxd[6651]: /usr/lib/go/src/net/unixsock_posix.go:314 +0x41
Sep 22 22:14:20 lxc lxd[6651]: net/http.(*Server).Serve(0xc8201b6000, 0x7fc1e013bd98, 0xc8200cd8a0, 0x0, 0x0)
Sep 22 22:14:20 lxc lxd[6651]: /usr/lib/go/src/net/http/server.go:1887 +0xb3
Sep 22 22:14:20 lxc lxd[6651]: main.(*Daemon).Init.func4.2(0x0, 0x0)
Sep 22 22:14:20 lxc lxd[6651]: /build/lxd-XknFpQ/lxd-0.18/dist/src/github.com/lxc/lxd/lxd/daemon.go:771 +0xdd
Sep 22 22:14:20 lxc lxd[6651]: gopkg.in/tomb%2ev2.(*Tomb).run(0xc82009bc08, 0xc82019a710)
Sep 22 22:14:20 lxc lxd[6651]: /build/lxd-XknFpQ/lxd-0.18/dist/src/gopkg.in/tomb.v2/tomb.go:153 +0x21
Sep 22 22:14:20 lxc lxd[6651]: created by gopkg.in/tomb%2ev2.(*Tomb).Go
Sep 22 22:14:20 lxc lxd[6651]: /build/lxd-XknFpQ/lxd-0.18/dist/src/gopkg.in/tomb.v2/tomb.go:149 +0x131
Sep 22 22:14:20 lxc systemd[1]: lxd.service holdoff time over, scheduling restart.
Sep 22 22:14:20 lxc systemd[1]: Started Container hypervisor based on LXC.
Sep 22 22:14:20 lxc systemd[1]: Starting Container hypervisor based on LXC...
```

**Comment by stgraber** [comment]
wow, this properly messes up the daemon indeed.

**Comment by stgraber** [comment]
Got a fix for this one.
