### ISSUE TITLE
Beta4: lxc list : panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by aarnaud** [lxc/lxd#1653]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 14.04.3
 * The output of "lxc info" or if that fails:
   * Kernel version: 3.19
   * LXC version: 2.0.0.beta4
   * LXD version: 2.0.0.beta4
   * Storage backend in use: ext4

# Issue description

`lxc list` crashed.

# Steps to reproduce

i don't know.

# Information to attach

Sorry i didn't have logs for this.

````bash
$ lxc list
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x40 pc=0x423a8a]
​
goroutine 1 [running]:
panic(0x8aca60, 0xc82000e160)
	/usr/lib/go/src/runtime/panic.go:464 +0x3e6
main.(*listCmd).IP4ColumnData(0xc8200b9860, 0xc8200f4ad4, 0x6, 0xc8200f67e0, 0xece60b9b1, 0x0, 0xd84f00, 0xc8200f6810, 0x0, 0xc8200f68d0, ...)
	/build/lxd-shPX1c/lxd-2.0.0~beta4/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxc/list.go:371 +0xaa
main.(*listCmd).IP4ColumnData-fm(0xc8200f4ad4, 0x6, 0xc8200f67e0, 0xece60b9b1, 0x0, 0xd84f00, 0xc8200f6810, 0x0, 0xc8200f68d0, 0xc8200f6900, ...)
	/build/lxd-shPX1c/lxd-2.0.0~beta4/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxc/list.go:332 +0x92
main.(*listCmd).listContainers(0xc8200b9860, 0xc8200ba900, 0xc82011ce00, 0x5, 0x6, 0xc8200e17c8, 0x0, 0x0, 0xc820150000, 0x6, ...)
	/build/lxd-shPX1c/lxd-2.0.0~beta4/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxc/list.go:273 +0xde3
main.(*listCmd).run(0xc8200b9860, 0xc8200e2090, 0x0, 0x0, 0x0, 0x0, 0x0)
	/build/lxd-shPX1c/lxd-2.0.0~beta4/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxc/list.go:357 +0x119e
main.run(0x0, 0x0)
	/build/lxd-shPX1c/lxd-2.0.0~beta4/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxc/main.go:159 +0x1098
main.main()
	/build/lxd-shPX1c/lxd-2.0.0~beta4/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxc/main.go:23 +0x3a
````

- `lxc list -c ns` worked
- `lxc list -c ns4` failed
- `lxc list -c ns6` failed

After stop and start all container, it's works.

Thanks,

**Comment by nick4u** [comment]
sime  .. i missed capslock and instead of "-c nsP" wrote :
```
$ lxc list -c nsp
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x48 pc=0x424861]

goroutine 1 [running]:
panic(0x8acae0, 0xc8200100f0)
        /usr/lib/go/src/runtime/panic.go:464 +0x3e6
main.(*listCmd).PIDColumnData(0xc8200e9440, 0xc820010778, 0x6, 0xc820016600, 0xece5e603a, 0x0, 0xd84f00, 0xc820016630, 0x0, 0xc8200166c0, ...)
        /build/lxd-nM_CF2/lxd-2.0.0~beta4/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxc/list.go:421 +0x31
main.(*listCmd).PIDColumnData-fm(0xc820010778, 0x6, 0xc820016600, 0xece5e603a, 0x0, 0xd84f00, 0xc820016630, 0x0, 0xc8200166c0, 0xc8200166f0, ...)
        /build/lxd-nM_CF2/lxd-2.0.0~beta4/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxc/list.go:337 +0x92
main.(*listCmd).listContainers(0xc8200e9440, 0xc8200ea900, 0xc820166000, 0x3, 0x4, 0xc8201137c8, 0x0, 0x0, 0xc820148180, 0x3, ...)
        /build/lxd-nM_CF2/lxd-2.0.0~beta4/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxc/list.go:273 +0xde3
main.(*listCmd).run(0xc8200e9440, 0xc820083f80, 0x0, 0x0, 0x0, 0x0, 0x0)
        /build/lxd-nM_CF2/lxd-2.0.0~beta4/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxc/list.go:357 +0x119e
main.run(0x0, 0x0)
        /build/lxd-nM_CF2/lxd-2.0.0~beta4/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxc/main.go:159 +0x1098
main.main()
        /build/lxd-nM_CF2/lxd-2.0.0~beta4/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxc/main.go:23 +0x3a
jakub@frgra1:~$ lxc list -c nsP
+----------------+---------+---------------+
|      NAME      |  STATE  |   PROFILES    |
+----------------+---------+---------------+
| ct100-02-base1 | STOPPED | vlan100       |
|                |         | small         |
+----------------+---------+---------------+
| ct100-03-dns   | RUNNING | vlan100       |
|                |         | small         |
+----------------+---------+---------------+
| ct102-03-mysql | RUNNING | vlan102       |
|                |         | big           |
+----------------+---------+---------------+

$ lxc info
apicompat: 0
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
<DATA>
    -----END CERTIFICATE-----
  driver: lxc
  driverversion: 2.0.0.rc2
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.2.0-30-generic
  server: lxd
  serverpid: 3307
  serverversion: 2.0.0.beta4
  storage: zfs
  storageversion: "5"
config:
  storage.zfs_pool_name: lxd
public: false

```

**Comment by IshwarKanse** [comment]
The pid column is giving panic error.

~~~
ishwar@anonymous:~$ lxc list -c46acnPst
+---------------------+------+--------------+----------------------+-------------+---------------+---------+------------+
|        IPV4         | IPV6 | ARCHITECTURE |      CREATED AT      |    NAME     |   PROFILES    |  STATE  |    TYPE    |
+---------------------+------+--------------+----------------------+-------------+---------------+---------+------------+
| 172.31.31.20 (eth0) |      | x86_64       |                      | nms         | bridged       | RUNNING | PERSISTENT |
+---------------------+------+--------------+----------------------+-------------+---------------+---------+------------+
| 172.31.31.50 (eth0) |      | x86_64       |                      | zabbix      | bridged       | RUNNING | PERSISTENT |
+---------------------+------+--------------+----------------------+-------------+---------------+---------+------------+
|                     |      | x86_64       | 2016/02/20 08:16 UTC | ipa         | default       | STOPPED | PERSISTENT |
+---------------------+------+--------------+----------------------+-------------+---------------+---------+------------+
|                     |      | x86_64       | 2016/02/24 09:34 UTC | kali        | bridged       | STOPPED | PERSISTENT |
+---------------------+------+--------------+----------------------+-------------+---------------+---------+------------+
|                     |      | x86_64       | 2016/02/15 06:49 UTC | mediaportal | bridged       | STOPPED | PERSISTENT |
+---------------------+------+--------------+----------------------+-------------+---------------+---------+------------+
|                     |      | x86_64       | 2016/02/18 06:24 UTC | osticket    | default       | STOPPED | PERSISTENT |
+---------------------+------+--------------+----------------------+-------------+---------------+---------+------------+
|                     |      | x86_64       |                      | pktfence    | default       | STOPPED | PERSISTENT |
|                     |      |              |                      |             | privi         |         |            |
+---------------------+------+--------------+----------------------+-------------+---------------+---------+------------+
|                     |      | x86_64       | 2016/02/25 06:41 UTC | rocketchat  | default       | STOPPED | PERSISTENT |
+---------------------+------+--------------+----------------------+-------------+---------------+---------+------------+
|                     |      | x86_64       | 2016/02/17 05:54 UTC | sandstorm   | default       | STOPPED | PERSISTENT |
+---------------------+------+--------------+----------------------+-------------+---------------+---------+------------+
|                     |      | x86_64       | 2016/02/24 06:05 UTC | vmin        | default       | STOPPED | PERSISTENT |
+---------------------+------+--------------+----------------------+-------------+---------------+---------+------------+
|                     |      | x86_64       |                      | openvas     | bridged       | STOPPED | PERSISTENT |
+---------------------+------+--------------+----------------------+-------------+---------------+---------+------------+
~~~

~~~
ishwar@anonymous:~$ lxc list -c np --debug
DBUG[02-26|12:27:01] Raw response: {"type":"sync","status":"Success","status_code":200,"metadata":{"api_extensions":[],"api_status":"development","api_version":"1.0","auth":"trusted","config":{},"environment":{"addresses":[],"architectures":["x86_64","i686"],"certificate":"-----BEGIN CERTIFICATE-----\nMIIFcjCCA1qgAwIBAgIQdNz4wk+qnA2ey8Cu0nDRPTANBgkqhkiG9w0BAQsFADA3\nMRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRcwFQYDVQQDDA5yb290QGFu\nb255bW91czAeFw0xNjAxMDEwOTU4NTJaFw0yNTEyMjkwOTU4NTJaMDcxHDAaBgNV\nBAoTE2xpbnV4Y29udGFpbmVycy5vcmcxFzAVBgNVBAMMDnJvb3RAYW5vbnltb3Vz\nMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA1D4htgEexTm1UteaCxId\nmhZeGBHmBJma3FU/Ibb7fijEk6cMYqx22zpxJNTd/GN9tQFl/Scww3sTbmbTEdzR\nDKtT8MRM0XPdc7Sam8tfxAOnKVSUkjyFuREFKGhM5MqLlwAMbzOC55kNmJXfLMbo\nYYtsVOjmcy+w6i9eEvJhMmBjfKAM9caVDkh09ihWUM8xfbEydE8pnaUf+i8+MmCs\nfBgb3wYgvaKkMlj1krbB5zgc6eHWnRUglwbXCbB3nzmQrtte9CxGno8FAvzqCcNm\nyTbrZYG7Q2y7ya5Ra9ftGzbUjAosYnnrPUlqe2W7z1OHGm9u/fR/rC1tz0m/nAI8\nC+oYL+5eHPt36Wx7CpnCEdUynAaaL2rD498yCqihPxKIA5a4Y9XZefHuTRphsg7L\ngSfPQNl+rFuEKuZGD3MYLB3r4TCL/Fi0KOO1YyfiSMuDQkQAkuNnbkAgWKyBrUcC\nC3KwtRiz+Wc2hPB/9hA6j3IKO6Xgiol/qH0PIOHyzGgyiF7dTuwfdjTT5M5tjOB/\nb+O+E2TDgzgej9ASDhWZjBk+loVN3crd0ieJ6JxezI+PO1RvxWeChXwKpXG/lwqi\nK3DOeGsiWeWvicUy5PwEKH/BECu0mvx6P8NaIMg0dxgGjf+T0KsSsHP1gy0RERLW\nmtczW0Dp7MN5OOOv8aVFqckCAwEAAaN6MHgwDgYDVR0PAQH/BAQDAgWgMBMGA1Ud\nJQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAwQwYDVR0RBDwwOoIJYW5vbnlt\nb3Vzgg8xNzIuMzEuMzEuMzUvMjSCHGZlODA6OjdhNDU6YzRmZjpmZTQzOjM2YmUv\nNjQwDQYJKoZIhvcNAQELBQADggIBAA8544z9/C2474KcKYTV/yswgE7gsHm/6lam\nYJgYJkiganH3UBt64583B5IrFXgGSoktgjvSkWya4CYZYRP7PL3Xs9W6kY+E27KW\n9PLje6mfi7gGyQd/S9TTnWJRvG9jd6hxVoZYOAOpu+vC08yPh02Mr/NQljypaeJK\n2XWEabIlGmpXeTW7x6QExjEqPDktuRjJqnydcbil+7nO92ajr+VkUHl4u6RN3kPo\ncHVrLygTDWfyUd0b0mKzTgTU9p8BWZm1fw6ojBdycNpCyLmkJAcCjub1q5imZihM\nc1P7K3lQ5lwYeS0hupU4s8gCGslrezWtU1xcmIbMBV/3Yn/i8c/6pIracEzP3CAL\nwY0GAVfsRI8rd6vYucf0khRSskdQ5XS2tDrbbR6QUvl4J4ckvO8d4OI+790UltSv\nEtTPFq8z4gawJKwAgniFuG6UyB1s09VDZy/riRkOxfIIZpEyFsSncvh3eycI+zDr\nSyZ19pWH+ehbX7J4Kzyeioo0QmzkwJ2/m88MX+GD0JgnnsW5jQxH/hWf86laYGOR\n1SFJmNkAuN0tsbuy0B8wBSen1cFWao6m0iYNvdxfOIbkrm55R81on+ZVFPBYQ21s\nY0y9cwcMAcJiIVAjwYA8o2eXdzI5EUlg0k5hDD9P0EpVqp96IALR7z2TC/jtDH7S\n15+22GWQ\n-----END CERTIFICATE-----\n","driver":"lxc","driver_version":"2.0.0.rc3","kernel":"Linux","kernel_architecture":"x86_64","kernel_version":"4.2.0-30-generic","server":"lxd","server_pid":3132,"server_version":"2.0.0.beta4","storage":"btrfs","storage_version":"4.0"},"public":false}}
 
DBUG[02-26|12:27:01] Raw response: {"type":"sync","status":"Success","status_code":200,"metadata":[{"architecture":"x86_64","config":{"volatile.base_image":"4dfde108d4e03643816ce2b649799dd3642565ca81a147c9153ca34c151b42ea","volatile.eth0.hwaddr":"00:16:3e:0f:92:99","volatile.eth0.name":"eth0","volatile.last_state.idmap":"[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536}]"},"created_at":"2016-02-20T08:16:28Z","devices":{"root":{"path":"/","type":"disk"}},"ephemeral":false,"expanded_config":{"volatile.base_image":"4dfde108d4e03643816ce2b649799dd3642565ca81a147c9153ca34c151b42ea","volatile.eth0.hwaddr":"00:16:3e:0f:92:99","volatile.eth0.name":"eth0","volatile.last_state.idmap":"[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536}]"},"expanded_devices":{"eth0":{"nictype":"bridged","parent":"lxcbr0","type":"nic"},"root":{"path":"/","type":"disk"}},"name":"ipa","profiles":["default"],"status":"Stopped","status_code":102},{"architecture":"x86_64","config":{"volatile.base_image":"33746e5a1e0d06ed7a62cacf7d4fcf8f0197272fac0c5c960af301fbad1da436","volatile.eth0.hwaddr":"00:16:3e:13:5c:1c","volatile.eth0.name":"eth0","volatile.last_state.idmap":"[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536}]"},"created_at":"2016-02-24T09:34:08Z","devices":{"root":{"path":"/","type":"disk"}},"ephemeral":false,"expanded_config":{"volatile.base_image":"33746e5a1e0d06ed7a62cacf7d4fcf8f0197272fac0c5c960af301fbad1da436","volatile.eth0.hwaddr":"00:16:3e:13:5c:1c","volatile.eth0.name":"eth0","volatile.last_state.idmap":"[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536}]"},"expanded_devices":{"eth0":{"nictype":"bridged","parent":"br0","type":"nic"},"root":{"path":"/","type":"disk"}},"name":"kali","profiles":["bridged"],"status":"Stopped","status_code":102},{"architecture":"x86_64","config":{"volatile.base_image":"09e6097a5761d830c2a15b4ed5c2eb4d1da5ea50415d070dc650ff6ff794b820","volatile.eth0.hwaddr":"00:16:3e:98:86:e6","volatile.eth0.name":"eth0","volatile.last_state.idmap":"[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536}]"},"created_at":"2016-02-15T06:49:50Z","devices":{"eth0":{"nictype":"bridged","parent":"br0","type":"nic"},"root":{"path":"/","type":"disk"}},"ephemeral":false,"expanded_config":{"volatile.base_image":"09e6097a5761d830c2a15b4ed5c2eb4d1da5ea50415d070dc650ff6ff794b820","volatile.eth0.hwaddr":"00:16:3e:98:86:e6","volatile.eth0.name":"eth0","volatile.last_state.idmap":"[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536}]"},"expanded_devices":{"eth0":{"nictype":"bridged","parent":"br0","type":"nic"},"root":{"path":"/","type":"disk"}},"name":"mediaportal","profiles":["bridged"],"status":"Stopped","status_code":102},{"architecture":"x86_64","config":{"volatile.base_image":"1709b50193c6a3fb3ad0a418c6d9bda0141e8abfac1bb1dad576c2eb5655dc46","volatile.eth0.hwaddr":"00:16:3e:ca:65:ea","volatile.eth0.name":"eth0","volatile.last_state.idmap":"[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536}]","volatile.lo.hwaddr":"00:16:3e:3d:da:27","volatile.lo.name":"eth1"},"created_at":"1970-01-01T00:00:00Z","devices":{"root":{"path":"/","type":"disk"}},"ephemeral":false,"expanded_config":{"volatile.base_image":"1709b50193c6a3fb3ad0a418c6d9bda0141e8abfac1bb1dad576c2eb5655dc46","volatile.eth0.hwaddr":"00:16:3e:ca:65:ea","volatile.eth0.name":"eth0","volatile.last_state.idmap":"[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536}]","volatile.lo.hwaddr":"00:16:3e:3d:da:27","volatile.lo.name":"eth1"},"expanded_devices":{"eth0":{"nictype":"bridged","parent":"br0","type":"nic"},"root":{"path":"/","type":"disk"}},"name":"nms","profiles":["bridged"],"status":"Running","status_code":103},{"architecture":"x86_64","config":{"volatile.base_image":"09e6097a5761d830c2a15b4ed5c2eb4d1da5ea50415d070dc650ff6ff794b820","volatile.eth0.hwaddr":"00:16:3e:01:d2:68","volatile.eth0.name":"eth0","volatile.last_state.idmap":"[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536}]"},"created_at":"1970-01-01T00:00:00Z","devices":{"root":{"path":"/","type":"disk"}},"ephemeral":false,"expanded_config":{"volatile.base_image":"09e6097a5761d830c2a15b4ed5c2eb4d1da5ea50415d070dc650ff6ff794b820","volatile.eth0.hwaddr":"00:16:3e:01:d2:68","volatile.eth0.name":"eth0","volatile.last_state.idmap":"[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536}]"},"expanded_devices":{"eth0":{"nictype":"bridged","parent":"br0","type":"nic"},"root":{"path":"/","type":"disk"}},"name":"openvas","profiles":["bridged"],"status":"Stopped","status_code":102},{"architecture":"x86_64","config":{"volatile.base_image":"09e6097a5761d830c2a15b4ed5c2eb4d1da5ea50415d070dc650ff6ff794b820","volatile.eth0.hwaddr":"00:16:3e:01:8a:d3","volatile.eth0.name":"eth0","volatile.last_state.idmap":"[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536}]"},"created_at":"2016-02-18T06:24:58Z","devices":{"root":{"path":"/","type":"disk"}},"ephemeral":false,"expanded_config":{"volatile.base_image":"09e6097a5761d830c2a15b4ed5c2eb4d1da5ea50415d070dc650ff6ff794b820","volatile.eth0.hwaddr":"00:16:3e:01:8a:d3","volatile.eth0.name":"eth0","volatile.last_state.idmap":"[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536}]"},"expanded_devices":{"eth0":{"nictype":"bridged","parent":"lxcbr0","type":"nic"},"root":{"path":"/","type":"disk"}},"name":"osticket","profiles":["default"],"status":"Stopped","status_code":102},{"architecture":"x86_64","config":{"volatile.base_image":"4b7904ab996d79ccd69bc20b451b4919873657e51828503f840b9af623220c12","volatile.eth0.hwaddr":"00:16:3e:7b:99:09","volatile.eth0.name":"eth0","volatile.last_state.idmap":"[]"},"created_at":"1970-01-01T00:00:00Z","devices":{"root":{"path":"/","type":"disk"}},"ephemeral":false,"expanded_config":{"security.privileged":"true","volatile.base_image":"4b7904ab996d79ccd69bc20b451b4919873657e51828503f840b9af623220c12","volatile.eth0.hwaddr":"00:16:3e:7b:99:09","volatile.eth0.name":"eth0","volatile.last_state.idmap":"[]"},"expanded_devices":{"eth0":{"nictype":"bridged","parent":"lxcbr0","type":"nic"},"root":{"path":"/","type":"disk"}},"name":"pktfence","profiles":["default","privi"],"status":"Stopped","status_code":102},{"architecture":"x86_64","config":{"volatile.base_image":"7c0b8de47a5b4353281b8224e9b3f092eb71de64d9014cb70114c408e6912b9d","volatile.eth0.hwaddr":"00:16:3e:a0:2a:c1","volatile.eth0.name":"eth0","volatile.last_state.idmap":"[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536}]","volatile.lo.hwaddr":"00:16:3e:40:70:d2","volatile.lo.name":"eth1"},"created_at":"2016-02-25T06:41:33Z","devices":{"root":{"path":"/","type":"disk"}},"ephemeral":false,"expanded_config":{"volatile.base_image":"7c0b8de47a5b4353281b8224e9b3f092eb71de64d9014cb70114c408e6912b9d","volatile.eth0.hwaddr":"00:16:3e:a0:2a:c1","volatile.eth0.name":"eth0","volatile.last_state.idmap":"[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536}]","volatile.lo.hwaddr":"00:16:3e:40:70:d2","volatile.lo.name":"eth1"},"expanded_devices":{"eth0":{"nictype":"bridged","parent":"lxcbr0","type":"nic"},"root":{"path":"/","type":"disk"}},"name":"rocketchat","profiles":["default"],"status":"Stopped","status_code":102},{"architecture":"x86_64","config":{"volatile.base_image":"09e6097a5761d830c2a15b4ed5c2eb4d1da5ea50415d070dc650ff6ff794b820","volatile.eth0.hwaddr":"00:16:3e:f3:c2:c8","volatile.eth0.name":"eth0","volatile.last_state.idmap":"[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536}]"},"created_at":"2016-02-17T05:54:44Z","devices":{"root":{"path":"/","type":"disk"}},"ephemeral":false,"expanded_config":{"volatile.base_image":"09e6097a5761d830c2a15b4ed5c2eb4d1da5ea50415d070dc650ff6ff794b820","volatile.eth0.hwaddr":"00:16:3e:f3:c2:c8","volatile.eth0.name":"eth0","volatile.last_state.idmap":"[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536}]"},"expanded_devices":{"eth0":{"nictype":"bridged","parent":"lxcbr0","type":"nic"},"root":{"path":"/","type":"disk"}},"name":"sandstorm","profiles":["default"],"status":"Stopped","status_code":102},{"architecture":"x86_64","config":{"volatile.base_image":"7c0b8de47a5b4353281b8224e9b3f092eb71de64d9014cb70114c408e6912b9d","volatile.eth0.hwaddr":"00:16:3e:16:85:ea","volatile.eth0.name":"eth0","volatile.last_state.idmap":"[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536}]"},"created_at":"2016-02-24T06:05:13Z","devices":{"root":{"path":"/","type":"disk"}},"ephemeral":false,"expanded_config":{"volatile.base_image":"7c0b8de47a5b4353281b8224e9b3f092eb71de64d9014cb70114c408e6912b9d","volatile.eth0.hwaddr":"00:16:3e:16:85:ea","volatile.eth0.name":"eth0","volatile.last_state.idmap":"[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536}]"},"expanded_devices":{"eth0":{"nictype":"bridged","parent":"lxcbr0","type":"nic"},"root":{"path":"/","type":"disk"}},"name":"vmin","profiles":["default"],"status":"Stopped","status_code":102},{"architecture":"x86_64","config":{"volatile.base_image":"09e6097a5761d830c2a15b4ed5c2eb4d1da5ea50415d070dc650ff6ff794b820","volatile.eth0.hwaddr":"00:16:3e:3a:53:e7","volatile.eth0.name":"eth0","volatile.last_state.idmap":"[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536}]","volatile.lo.hwaddr":"00:16:3e:f3:f8:71","volatile.lo.name":"eth1"},"created_at":"1970-01-01T00:00:00Z","devices":{"eth0":{"nictype":"bridged","parent":"br0","type":"nic"},"root":{"path":"/","type":"disk"}},"ephemeral":false,"expanded_config":{"volatile.base_image":"09e6097a5761d830c2a15b4ed5c2eb4d1da5ea50415d070dc650ff6ff794b820","volatile.eth0.hwaddr":"00:16:3e:3a:53:e7","volatile.eth0.name":"eth0","volatile.last_state.idmap":"[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536}]","volatile.lo.hwaddr":"00:16:3e:f3:f8:71","volatile.lo.name":"eth1"},"expanded_devices":{"eth0":{"nictype":"bridged","parent":"br0","type":"nic"},"root":{"path":"/","type":"disk"}},"name":"zabbix","profiles":["bridged"],"status":"Running","status_code":103}]}
 
DBUG[02-26|12:27:01] Raw response: {"type":"sync","status":"Success","status_code":200,"metadata":{"status":"Running","status_code":103,"disk":{},"memory":{"usage":532963328,"usage_peak":540884992,"swap_usage":0,"swap_usage_peak":0},"network":{"eth0":{"addresses":[{"family":"inet","address":"172.31.31.50","netmask":"24","scope":"global"},{"family":"inet6","address":"fe80::216:3eff:fe3a:53e7","netmask":"64","scope":"link"}],"counters":{"bytes_received":7164921,"bytes_sent":7806175,"packets_received":98613,"packets_sent":105134},"hwaddr":"00:16:3e:3a:53:e7","host_name":"vethAPOO9M","mtu":1500,"state":"up","type":"broadcast"},"lo":{"addresses":[{"family":"inet","address":"127.0.0.1","netmask":"8","scope":"local"},{"family":"inet6","address":"::1","netmask":"128","scope":"local"}],"counters":{"bytes_received":399357,"bytes_sent":399357,"packets_received":6738,"packets_sent":6738},"hwaddr":"","host_name":"","mtu":65536,"state":"up","type":"loopback"}},"pid":5301,"processes":59}}
 
DBUG[02-26|12:27:01] Raw response: {"type":"sync","status":"Success","status_code":200,"metadata":{"status":"Running","status_code":103,"disk":{},"memory":{"usage":1466306560,"usage_peak":1470828544,"swap_usage":0,"swap_usage_peak":0},"network":{"eth0":{"addresses":[{"family":"inet","address":"172.31.31.20","netmask":"16","scope":"global"},{"family":"inet6","address":"fe80::216:3eff:feca:65ea","netmask":"64","scope":"link"}],"counters":{"bytes_received":3879515,"bytes_sent":2179501,"packets_received":17337,"packets_sent":19723},"hwaddr":"00:16:3e:ca:65:ea","host_name":"vethKA0N2R","mtu":1500,"state":"up","type":"broadcast"},"lo":{"addresses":[{"family":"inet","address":"127.0.0.1","netmask":"8","scope":"local"},{"family":"inet6","address":"::1","netmask":"128","scope":"local"}],"counters":{"bytes_received":130660934,"bytes_sent":130660934,"packets_received":286572,"packets_sent":286572},"hwaddr":"","host_name":"","mtu":65536,"state":"up","type":"loopback"}},"pid":14661,"processes":78}}
 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x48 pc=0x424a41]

goroutine 1 [running]:
panic(0x8acd80, 0xc82000e130)
	/usr/lib/go/src/runtime/panic.go:464 +0x3e6
main.(*listCmd).PIDColumnData(0xc8200bb7c0, 0xc8200f0758, 0x6, 0xc8200f25d0, 0xece5a17dc, 0x0, 0xd84f00, 0xc8200f2600, 0x0, 0xc8200f2660, ...)
	/build/lxd-SxdSwY/lxd-2.0.0~beta4/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxc/list.go:429 +0x31
main.(*listCmd).PIDColumnData-fm(0xc8200f0758, 0x6, 0xc8200f25d0, 0xece5a17dc, 0x0, 0xd84f00, 0xc8200f2600, 0x0, 0xc8200f2660, 0xc8200f2690, ...)
	/build/lxd-SxdSwY/lxd-2.0.0~beta4/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxc/list.go:337 +0x92
main.(*listCmd).listContainers(0xc8200bb7c0, 0xc8200bc900, 0xc820131000, 0xb, 0xd, 0xc8200e37c8, 0x0, 0x0, 0xc8200f8ac0, 0x2, ...)
	/build/lxd-SxdSwY/lxd-2.0.0~beta4/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxc/list.go:273 +0xde3
main.(*listCmd).run(0xc8200bb7c0, 0xc8200e4060, 0x0, 0x0, 0x0, 0x0, 0x0)
	/build/lxd-SxdSwY/lxd-2.0.0~beta4/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxc/list.go:357 +0x119e
main.run(0x0, 0x0)
	/build/lxd-SxdSwY/lxd-2.0.0~beta4/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxc/main.go:159 +0x1098
main.main()
	/build/lxd-SxdSwY/lxd-2.0.0~beta4/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxc/main.go:23 +0x3a

~~~

**Comment by stgraber** [comment]
Confirmed for the pid column...
