### ISSUE TITLE
Import lxc containers

### ISSUE THREAD

**Issue by huegelc** [lxc/lxd#2175]
Hi,

I have a couple of lxc container created with 1.0.8-0ubuntu0.3. Is there a way to import this lxc container into lxd?

**Comment by tych0** [comment]
Hi, see the `/scripts/lxc-to-lxd` script in the LXD tree.

**Comment by huegelc** [comment]
Doesnt start on:
* Distribution: Ubuntu
 * Distribution version: 14.04
  * Kernel version: 3.19.0-25-generic
  * LXC version:
  * LXD version: 2.0.3
  * Storage backend in use: dir

```
Traceback (most recent call last):
  File "./lxc-to-lxd.py", line 5, in <module>
    import lxc
ImportError: No module named 'lxc'
```

**Comment by stgraber** [comment]
As the error says, you're missing the "lxc" python3 module.

sudo apt install python3-lxc

Should fix that one for you.

**Comment by huegelc** [comment]
Thank you for your reply. Well this doesnt work because I´ve installed lxd from the backport
` sudo apt -t trusty-backports install lxd` 
and now there are some unresolved dependencies:
```
The following packages have unmet dependencies:
 python3-lxc : Depends: liblxc1 (= 1.0.8-0ubuntu0.3) but 2.0.3-0ubuntu1~ubuntu14.04.1 is to be installed
               Recommends: lxc-templates (>= 0.8.0~rc1-4ubuntu43) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by stgraber** [comment]
sudo apt -t trusty-backports install python3-lxc

**Comment by huegelc** [comment]
:+1: 

```
Traceback (most recent call last):
  File "./lxc-to-lxd.py", line 8, in <module>
    from pylxd.client import Client
ImportError: No module named 'pylxd'
```

**Comment by stgraber** [comment]
pip install pylxd

**Comment by huegelc** [comment]
```
root@nas-10-cluster:~# pip install pylxd
Downloading/unpacking pylxd
  Downloading pylxd-2.0.3.tar.gz (58kB): 58kB downloaded
  Running setup.py (path:/tmp/pip_build_root/pylxd/setup.py) egg_info for package pylxd
    
    Installed /tmp/easy_install-K_ofGS/requests-unixsocket-0.1.5/.eggs/pbr-1.10.0-py2.7.egg
    
    Installed /tmp/pip_build_root/pylxd/.eggs/requests_unixsocket-0.1.5-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/pylxd/setup.py", line 34, in <module>
        pbr=True)
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 269, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 825, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1063, in best_match
        dist = working_set.find(req)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 700, in find
        raise VersionConflict(dist, req)
    pkg_resources.VersionConflict: (requests 2.2.1 (/usr/lib/python2.7/dist-packages), Requirement.parse('requests!=2.8.0,>=2.5.2'))
    Complete output from command python setup.py egg_info:
    

Installed /tmp/easy_install-K_ofGS/requests-unixsocket-0.1.5/.eggs/pbr-1.10.0-py2.7.egg



Installed /tmp/pip_build_root/pylxd/.eggs/requests_unixsocket-0.1.5-py2.7.egg

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/pylxd/setup.py", line 34, in <module>

    pbr=True)

  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 269, in __init__

    self.fetch_build_eggs(attrs['setup_requires'])

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs

    replace_conflicting=True,

  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 825, in resolve

    dist = best[req.key] = env.best_match(req, ws, installer)

  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1063, in best_match

    dist = working_set.find(req)

  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 700, in find

    raise VersionConflict(dist, req)

pkg_resources.VersionConflict: (requests 2.2.1 (/usr/lib/python2.7/dist-packages), Requirement.parse('requests!=2.8.0,>=2.5.2'))

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/pylxd
Storing debug log for failure in /root/.pip/pip.log
```
:(

**Comment by stgraber** [comment]
Looks like it's unhappy about the version of python requests.

@rockstar any suggestion?

**Comment by stgraber** [comment]
So I think the answer is to use Ubuntu 16.04 if you want all that stuff to work properly.

You can probably workaround it with:
```
apt update
apt dist-upgrade
apt -t trusty-backports install python-virtualenv python3-dev libffi-dev libssl-dev git lxc-dev pkg-config
virtualenv -p /usr/bin/python3 py3env
source py3env/bin/activate
pip install pylxd
git clone git://github.com/lxc/lxc
cd lxc/src/python-lxc
pip install .
cd
wget https://raw.githubusercontent.com/lxc/lxd/master/scripts/lxc-to-lxd
python3 lxc-to-lxd
```

Which does appear to work for me inside a LXD 14.04 container.

**Comment by stgraber** [comment]
Only thing I see we can improve on the LXD side is changing the shebang of our python3 scripts to work better with virtualenv, I'll send a patch.

**Comment by huegelc** [comment]
Thank you
