### ISSUE TITLE
lxc-to-lxd script does not work

### ISSUE THREAD

**Issue by korotovsky** [lxc/lxd#2208]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04 LTS
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-31-generic
   * LXC version: 2.0.3
   * LXD version: 2.0.3
   * Storage backend in use: dir (?)

# Issue description

I'm trying to convert my LXC containers to LXD and having various issues using this command:

```bash
./lxc-to-lxd --debug --copy-rootfs my-container
```

The first issue I faced is:

```
Traceback (most recent call last):
  File "./lxc-to-lxd.py", line 421, in <module>
    convert_container(container_name, args)
  File "./lxc-to-lxd.py", line 78, in convert_container
    lxd = Client()
  File "/usr/lib/python3/dist-packages/pylxd/client.py", line 118, in __init__
    urllib.quote(path, safe='')))
AttributeError: module 'urllib' has no attribute 'quote'
```

But I hotfixed it by modifying `urllib.quote(path, safe='')))` to `urllib.parse.quote(path, safe='')))`.
The second issue is:

```
 # ./lxc-to-lxd.py --debug --copy-rootfs my-container
==> Processing container: my-container
Parsing LXC configuration
Container configuration:
 lxc.rootfs = /var/lib/lxc/my-container/rootfs
 lxc.utsname = my-container
 lxc.arch = amd64
 lxc.network.type = veth
 lxc.network.flags = up
 lxc.network.link = br0
 lxc.network.hwaddr = 00:16:3e:b1:10:80
 lxc.network.name  =  eth0
 lxc.mount.entry  =  /var/backups/lxc-my-container var/backups none bind 0 0
 lxc.start.auto  =  1

Checking for existing containers
Validating container name
Validating container mode
Validating container rootfs
Processing network configuration
Processing environment configuration
Processing container boot configuration
Processing container apparmor configuration
Processing container seccomp configuration
Processing container SELinux configuration
Processing container capabilities configuration
Converting container architecture configuration
Unknown architecture, assuming native.
LXD container config:
{
 "config": {
  "boot.autostart": "true",
  "security.privileged": "true"
 },
 "devices": {
  "convert_mount0": {
   "path": "/var/backups",
   "source": "/var/backups/lxc-my-container",
   "type": "disk"
  },
  "convert_net0": {
   "hwaddr": "00:16:3e:b1:10:80",
   "name": "eth0",
   "nictype": "bridged",
   "parent": "br0",
   "type": "nic"
  },
  "eth0": {
   "type": "none"
  }
 },
 "name": "my-container",
 "profiles": [
  "default"
 ],
 "source": {
  "type": "none"
 }
}
Creating the container
Traceback (most recent call last):
  File "./lxc-to-lxd.py", line 421, in <module>
    convert_container(container_name, args)
  File "./lxc-to-lxd.py", line 349, in convert_container
    lxd.containers.create(new, wait=True)
  File "/usr/lib/python3/dist-packages/pylxd/container.py", line 68, in create
    Operation.wait_for_operation(client, response.json()['operation'])
  File "/usr/lib/python3/dist-packages/pylxd/operation.py", line 29, in wait_for_operation
    operation = cls.get(client, operation_id)
  File "/usr/lib/python3/dist-packages/pylxd/operation.py", line 36, in get
    return cls(_client=client, **response.json()['metadata'])
  File "/usr/lib/python3/dist-packages/pylxd/operation.py", line 40, in __init__
    for key, value in kwargs.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
```

# Information to attach

 - [x] any relevant kernel output (dmesg) (nothing relevant)
 - [x] container log (lxc info NAME --show-log) 
```
# lxc info my-container --show-log
Name: my-container
Architecture: x86_64
Created: 2016/07/17 12:51 UTC
Status: Stopped
Type: persistent
Profiles: default

Log:

```
 - [x] main daemon log (/var/log/lxd.log)
```
t=2016-07-17T14:53:42+0200 lvl=info msg=handling method=GET url=/1.0/containers/my-container ip=@
t=2016-07-17T14:53:42+0200 lvl=info msg=handling method=POST url=/1.0/containers ip=@
t=2016-07-17T14:53:42+0200 lvl=info msg=handling method=GET url=/1.0/operations/91ffc0a9-e281-4aab-9e21-3814df451364 ip=@
```
 - [x] output of the daemon with --debug
```
INFO[07-17|14:55:07] handling                                 method=GET url=/1.0/containers/my-container ip=@
DBUG[07-17|14:55:07] 
	{
		"error": "not found",
		"error_code": 404,
		"type": "error"
	} 
INFO[07-17|14:55:07] handling                                 method=POST url=/1.0/containers ip=@
DBUG[07-17|14:55:07] 
	{
		"source": {
			"type": "none"
		},
		"name": "my-container",
		"devices": {
			"eth0": {
				"type": "none"
			},
			"convert_mount0": {
				"type": "disk",
				"source": "/var/backups/lxc-my-container",
				"path": "/var/backups"
			},
			"convert_net0": {
				"type": "nic",
				"name": "eth0",
				"hwaddr": "00:16:3e:b1:10:80",
				"parent": "br0",
				"nictype": "bridged"
			}
		},
		"config": {
			"security.privileged": "true",
			"boot.autostart": "true"
		},
		"profiles": [
			"default"
		]
	 
DBUG[07-17|14:55:07] Responding to container create 
DBUG[07-17|14:55:07] New task operation: ff501994-d2ec-4a98-a649-46322772b293 
DBUG[07-17|14:55:07] Started task operation: ff501994-d2ec-4a98-a649-46322772b293 
DBUG[07-17|14:55:07] 
	{
		"type": "async",
		"status": "Operation created",
		"status_code": 100,
		"metadata": {
			"id": "ff501994-d2ec-4a98-a649-46322772b293",
			"class": "task",
			"created_at": "2016-07-17T14:55:07.465581958+02:00",
			"updated_at": "2016-07-17T14:55:07.465581958+02:00",
			"status": "Running",
			"status_code": 103,
			"resources": {
				"containers": [
					"/1.0/containers/my-container"
				]
			},
			"metadata": null,
			"may_cancel": false,
			"err": ""
		},
		"operation": "/1.0/operations/ff501994-d2ec-4a98-a649-46322772b293"
	} 
INFO[07-17|14:55:07] handling                                 method=GET url=/1.0/operations/ff501994-d2ec-4a98-a649-46322772b293 ip=@
DBUG[07-17|14:55:07] 
	{
		"type": "sync",
		"status": "Success",
		"status_code": 200,
		"metadata": {
			"id": "ff501994-d2ec-4a98-a649-46322772b293",
			"class": "task",
			"created_at": "2016-07-17T14:55:07.465581958+02:00",
			"updated_at": "2016-07-17T14:55:07.465581958+02:00",
			"status": "Running",
			"status_code": 103,
			"resources": {
				"containers": [
					"/1.0/containers/my-container"
				]
			},
			"metadata": null,
			"may_cancel": false,
			"err": ""
		}
	} 
DBUG[07-17|14:55:07] ContainerCreate                          driver=storage/dir name=my-container isPrivileged=true
DBUG[07-17|14:55:07] Success for task operation: ff501994-d2ec-4a98-a649-46322772b293 

```

**Comment by pcdummy** [comment]
Hmm try to hotfix by replacing all "iteritems()" with "items()" theres no more iteritems in python3.

**Comment by korotovsky** [comment]
@pcdummy Yes, it works! But it means that I have quite weird version of `pylxd` module. It's installed under `python3` directory, so it's definitely python3-like version :) How it might work before?

I have got PPA `ubuntu-lxc/lxc-stable`. Should I use `python3-pylxd` from there or from `pip3`? Or are they both buggy?

**Comment by pcdummy** [comment]
I use pylxd with python 2.7 this is what i know. "pip install pylxd" will get you it.

Seems the script is orginaly py2 not sure, never touched it.

**Comment by korotovsky** [comment]
The script uses python3: https://github.com/lxc/lxd/blob/stable-2.0/scripts/lxc-to-lxd

**Comment by pcdummy** [comment]
Join us [on the freenode #lxcontainers channel](https://webchat.freenode.net/?channels=#lxcontainers) i'm sure we get this running.

**Comment by pcdummy** [comment]
Now where i had a closer look, "pip3 install -U pylxd" should fix pylxd, sorry for my first "quick fix" recommendation.
