### ISSUE TITLE
dnf install fails with LXD - gpgme - Inappropriate ioctl for device

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#2240]
# Required information

 * Distribution: Ubuntu Studio 16.04
 * Container distribution: Fedora 24
 * The output of "lxc info" or if that fails:
   * Kernel version:  4.4.0-31-generic
   * LXC version: 2.0.3
   * LXD version: 2.0.3
   * Storage backend in use: dir

# Issue description

`dnf install` fails in LXD container, probably because of `gpgme`.

# Steps to reproduce
```
$ lxc launch lxc:fedora/24/amd64 dntest
$ lxc exec dntest bash
# dnf install git
...
warning: /var/cache/dnf/updates-c4f1c95f64c2b794/packages/git-2.7.4-2.fc24.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID 81b46521: NOKEY
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Traceback (most recent call last):
  File "/usr/bin/dnf", line 58, in <module>
    main.user_main(sys.argv[1:], exit_code=True)
  File "/usr/lib/python3.5/site-packages/dnf/cli/main.py", line 174, in user_main
    errcode = main(args)
  File "/usr/lib/python3.5/site-packages/dnf/cli/main.py", line 60, in main
    return _main(base, args)
  File "/usr/lib/python3.5/site-packages/dnf/cli/main.py", line 120, in _main
    ret = resolving(cli, base)
  File "/usr/lib/python3.5/site-packages/dnf/cli/main.py", line 149, in resolving
    base.do_transaction(display=displays)
  File "/usr/lib/python3.5/site-packages/dnf/cli/cli.py", line 220, in do_transaction
    self.gpgsigcheck(downloadpkgs)
  File "/usr/lib/python3.5/site-packages/dnf/cli/cli.py", line 258, in gpgsigcheck
    self._get_key_for_package(po, fn)
  File "/usr/lib/python3.5/site-packages/dnf/base.py", line 1842, in _get_key_for_package
    keys = dnf.crypto.retrieve(keyurl, repo)
  File "/usr/lib/python3.5/site-packages/dnf/crypto.py", line 124, in retrieve
    keyinfos = rawkey2infos(handle)
  File "/usr/lib/python3.5/site-packages/dnf/crypto.py", line 117, in rawkey2infos
    info.raw_key = buf.getvalue()
  File "/usr/lib64/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3.5/site-packages/dnf/crypto.py", line 95, in pubring_dir
    yield
  File "/usr/lib/python3.5/site-packages/dnf/crypto.py", line 107, in rawkey2infos
    ctx.import_(key_fo)
gpgme.GpgmeError: (7, 32870, 'Inappropriate ioctl for device')
```

**Comment by techtonik** [comment]
`dnf` bug - https://bugzilla.redhat.com/show_bug.cgi?id=1224908#c11

**Comment by techtonik** [comment]
`gpgme` bug - https://bugs.gnupg.org/gnupg/issue2426

**Comment by stgraber** [comment]
Running a quick test on Fedora 24 here to see if I can get more information on exactly what fails, but so far sounds to me like there's nothing for us to do in LXD but wait for those two bugs above to get sorted out.

**Comment by techtonik** [comment]
A temporary workaround was to run it through `tee`.

**Comment by stgraber** [comment]
Right, looks like something in gpgme is attempting to reset the terminal mode and failing.

Another workaround is to do:

    lxc exec container-name -- script /dev/null

Which will create a temporary pts console for you and workaround the problem.

This root of this issue is basically the same as #1724 but gpgme could certainly do a better job at dealing with this situation, until we can convince the C library maintainers to improve their logic for containers.

**Comment by stgraber** [comment]
Ok, so this is being tracked with both affected upstreams and the ultimate fix was sent by @hallyn a few months ago to the GNU C library. There's nothing that we could (or at least should) be doing about this in LXD, so no point keeping this bug open here.
