### ISSUE TITLE
/1.0/operations/<uuid>/websocket returns 403 sometimes

### ISSUE THREAD

**Issue by raharper** [lxc/lxd#231]
Running lxd from ppa, using socat like this for tcp bridge to unix-socket:

socat -d -d TCP-LISTEN:8080,fork UNIX:/var/lib/lxd/unix.socket

1. create a container and start it
2. run lxc exec <container> uptime to confirm it's working.
3. use the following python program to run exec via REST api:
```
#!/usr/bin/python
import json
import requests
import sys
import websocket
URL = '127.0.0.1:8080'
if len(sys.argv) < 2:
    print 'usage: lxc_state <container>'
    sys.exit(1)

u='http://%s/1.0/containers/%s/exec' % (URL, sys.argv[1])
command = {
    "command": [sys.argv[2]],
    "wait-for-websocket": True,
}
params = json.dumps(command)
r = requests.post(u, data=params)
content = json.loads(r.content)
op = content['operation']
secret = content['metadata']['websocket_secret']
wsurl = 'ws://%s%s/websocket?secret=%s' %(URL,op, secret)
ws = websocket.WebSocket()
ws.connect(wsurl)
output = ws.recv()
print output
```
Sometimes it works, other times it throws 403 response.
```
(lambic) lxc % ./execute 101 uptime
Traceback (most recent call last):
  File "./execute", line 23, in <module>
    ws.connect(wsurl)
  File "/usr/lib/python2.7/dist-packages/websocket/_core.py", line 470, in connect
    self._handshake(hostname, port, resource, **options)
  File "/usr/lib/python2.7/dist-packages/websocket/_core.py", line 531, in _handshake
    resp_headers = self._get_resp_headers()
  File "/usr/lib/python2.7/dist-packages/websocket/_core.py", line 488, in _get_resp_headers
    raise WebSocketException("Handshake status %d" % status)
websocket._exceptions.WebSocketException: Handshake status 403
(lambic) lxc % ./execute 101 uptime
 22:27:42 up 49 min,  0 users,  load average: 80.25, 61.21, 47.85
```

**Comment by tych0** [comment]
I can confirm that I see this too (although for me it almost never succeeds). I poked around and it seems like a gorilla bug, but I can't actually figure out what's going wrong. More on this later...

**Comment by stgraber** [comment]
Can you retest with the reworked /exec that got merged today?

**Comment by raharper** [comment]
Updated the test program to work with the new websocket api.  With the help of urlencode (which was the root issue since sometimes the secret key didn't include any control characters.  Now with opening all 3 fds, and encoding the URL, all is well.

```
#!/usr/bin/python
import json
import requests
import sys
import websocket
import urllib
URL = '127.0.0.1:8080'

if len(sys.argv) < 2:
    print 'usage: exec <container> cmd'
    sys.exit(1)

u='http://%s/1.0/containers/%s/exec' % (URL, sys.argv[1])
command = {
    "command": sys.argv[2:],
    "wait-for-websocket": True,
}
params = json.dumps(command)
r = requests.post(u, data=params)
content = json.loads(r.content)
op = content['operation']
fds = content['metadata']['fds']
sockets = {}

stdout = u'\x01'
stdin = u'\x00'
stderr = u'\x02'

for fd in [stdin, stdout, stderr]:
    secret = urllib.urlencode({'secret': fds[fd]})
    wsurl = 'ws://%s%s/websocket?%s' %(URL, op, secret)
    ws = websocket.WebSocket()
    ws.connect(wsurl)
    sockets[fd] = ws

# stdout = 1, stderr = 2
output = sockets[stdout].recv()
error = sockets[stderr].recv()

print output
```

Testing:
```
(lambic) lxc % ./execute 0003 uptime
 16:58:48 up 3 days, 19:04,  0 users,  load average: 0.00, 0.01, 0.05

(lambic) lxc % ./execute 0003 cat /etc/issue 
Ubuntu Vivid Vervet (development branch) \n \l

```
