### ISSUE TITLE
concurrent map read and write on exec

### ISSUE THREAD

**Issue by brauner** [lxc/lxd#2862]
So there seems to be race between connecting to the websocket and reading from it in `WebSocketExecMirror()` and I'm trying to explain this to myself. If https://github.com/lxc/lxd/blob/master/lxd/container_exec.go#L86 `allconnected` is hit before `s.conns[0]` is initialized then `WebSocketExecMirror()` will already be trying to read from the websocket when `Connect()` is still initializing it. This would mean that `allconnected` would need to move outside of the loop. @stgraber, @tych0 what do you think?

Pasting the full stacktrace for me here:

```
+ eval /lxd/build/tmp.YjknBY3Tjh/go/bin/lxc "exec" "foo" --verbose --force-local -- "/bin/rm" "-f" "root/in1"
+ /lxd/build/tmp.YjknBY3Tjh/go/bin/lxc exec foo --verbose --force-local -- /bin/rm -f root/in1
fatal error: concurrent map read and map write

goroutine 7847 [running]:
runtime.throw(0xaa2ec0, 0x21)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/runtime/panic.go:566 +0x95 fp=0xc420042f08 sp=0xc420042ee8
runtime.mapaccess1_fast64(0x9fee60, 0xc420305ce0, 0x0, 0x0)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/runtime/hashmap_fast.go:111 +0x1a7 fp=0xc420042f30 sp=0xc420042f08
main.(*execWs).Do.func2(0xc4202f5180, 0xc4204c4010, 0x1, 0x1, 0xc42020c000, 0xc4204e0110)
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/container_exec.go:204 +0x48 fp=0xc420042f90 sp=0xc420042f30
runtime.goexit()
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420042f98 sp=0xc420042f90
created by main.(*execWs).Do
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/container_exec.go:209 +0xe08

goroutine 1 [semacquire, 4 minutes]:
sync.runtime_Semacquire(0xc42001091c)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/runtime/sema.go:47 +0x30
sync.(*WaitGroup).Wait(0xc420010910)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/sync/waitgroup.go:131 +0x97
main.cmdDaemon(0x0, 0x0)
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/main_daemon.go:99 +0x351
main.run(0x2, 0xc4200fdbc0)
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/main.go:243 +0x3bc
main.main()
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/main.go:51 +0x26

goroutine 17 [syscall, 4 minutes, locked to thread]:
runtime.goexit()
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/runtime/asm_amd64.s:2086 +0x1

goroutine 20 [syscall, 4 minutes]:
os/signal.signal_recv(0x0)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/os/signal/signal_unix.go:28 +0x41

goroutine 21 [chan receive, 4 minutes]:
database/sql.(*DB).connectionOpener(0xc4200d6d10)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/database/sql/sql.go:730 +0x4a
created by database/sql.Open
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/database/sql/sql.go:493 +0x1e9

goroutine 82 [syscall]:
syscall.Syscall(0x0, 0x8, 0xc4201d6000, 0x1000, 0x2, 0xc4204fa9c0, 0xc4204fa9c0)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x8, 0xc4201d6000, 0x1000, 0x1000, 0xf33cd0, 0x2, 0xc42002ca20)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/syscall/zsyscall_linux_amd64.go:783 +0x55
syscall.Read(0x8, 0xc4201d6000, 0x1000, 0x1000, 0xc42002ca00, 0x0, 0x2)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/syscall/syscall_unix.go:161 +0x49
main.deviceNetlinkListener.func1(0x800, 0x8, 0xc4201ca000, 0xc4201ca060, 0xc4201ca0c0)
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/devices.go:339 +0xa9
created by main.deviceNetlinkListener
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/devices.go:452 +0x1a6

goroutine 8 [chan receive, 4 minutes]:
main.cmdDaemon.func4(0xc420010900, 0xc420130360, 0xc420010910)
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/main_daemon.go:92 +0x247
created by main.cmdDaemon
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/main_daemon.go:97 +0x343

goroutine 7 [chan receive, 4 minutes]:
main.cmdDaemon.func3(0xc420130360, 0xc420010900, 0xc420010910)
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/main_daemon.go:77 +0x4b
created by main.cmdDaemon
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/main_daemon.go:85 +0x30d

goroutine 9 [select, 4 minutes, locked to thread]:
runtime.gopark(0xb07a28, 0x0, 0xa8e5f2, 0x6, 0x18, 0x2)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/runtime/proc.go:259 +0x13a
runtime.selectgoImpl(0xc420194f30, 0x0, 0x18)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/runtime/select.go:423 +0x11d9
runtime.selectgo(0xc420194f30)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/runtime/signal1_unix.go:304 +0x2f3
runtime.goexit()
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/runtime/asm_amd64.s:2086 +0x1

goroutine 69 [chan receive, 4 minutes]:
main.(*Daemon).Init.func2(0xc420130360)
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/daemon.go:851 +0xf3
created by main.(*Daemon).Init
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/daemon.go:853 +0x1014

goroutine 70 [select]:
main.deviceEventListener(0xc420130360)
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/devices.go:745 +0x6eb
created by main.(*Daemon).Init
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/daemon.go:871 +0x24c0

goroutine 6 [chan receive, 4 minutes]:
main.cmdDaemon.func2(0xc420130360, 0xc420010900, 0xc420010910)
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/main_daemon.go:66 +0x100
created by main.cmdDaemon
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/main_daemon.go:74 +0x2d7

goroutine 81 [IO wait]:
net.runtime_pollWait(0x7fe231917248, 0x72, 0x0)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc42025c0d0, 0x72, 0xc420057cd0, 0xc4200920b0)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc42025c0d0, 0xf401a0, 0xc4200920b0)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).accept(0xc42025c070, 0x0, 0xf3e8a0, 0xc4204c80a0)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/net/fd_unix.go:419 +0x238
net.(*TCPListener).accept(0xc4200b2080, 0xc4204c4018, 0xc42007c000, 0x7fe23196a960)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/net/tcpsock_posix.go:132 +0x2e
net.(*TCPListener).Accept(0xc4200b2080, 0x59399e, 0xc420057dd8, 0x616a3d, 0x5b33c0)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/net/tcpsock.go:222 +0x49
crypto/tls.(*listener).Accept(0xc420202420, 0xb073c8, 0xc420018100, 0xf43ba0, 0xc4201fe3c0)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/crypto/tls/tls.go:52 +0x37
net/http.(*Server).Serve(0xc4200b6200, 0xf42ca0, 0xc420202420, 0x0, 0x0)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/net/http/server.go:2273 +0x1ce
net/http.Serve(0xf42ca0, 0xc420202420, 0xf3dc60, 0xc420238040, 0x0, 0x0)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/net/http/server.go:2091 +0x99
main.(*Daemon).UpdateHTTPsPort.func1(0x0, 0x0)
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/daemon.go:520 +0xa9
gopkg.in/tomb%2ev2.(*Tomb).run(0xc4201303d8, 0xc420202440)
	/lxd/build/tmp.YjknBY3Tjh/go/src/gopkg.in/tomb.v2/tomb.go:163 +0x2b
created by gopkg.in/tomb%2ev2.(*Tomb).Go
	/lxd/build/tmp.YjknBY3Tjh/go/src/gopkg.in/tomb.v2/tomb.go:159 +0xd0

goroutine 73 [select, 4 minutes]:
main.(*Daemon).Ready.func1(0xc420130360)
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/daemon.go:1060 +0x14f
created by main.(*Daemon).Ready
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/daemon.go:1070 +0x7f

goroutine 74 [select, 4 minutes]:
main.(*Daemon).Ready.func2(0xc420130360)
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/daemon.go:1088 +0x208
created by main.(*Daemon).Ready
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/daemon.go:1101 +0xd7

goroutine 77 [IO wait]:
net.runtime_pollWait(0x7fe2319173c8, 0x72, 0x0)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc420274bc0, 0x72, 0xc42030ad28, 0xc4200920b0)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc420274bc0, 0xf401a0, 0xc4200920b0)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).accept(0xc420274b60, 0x0, 0xf3e8a0, 0xc4204fa0e0)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/net/fd_unix.go:419 +0x238
net.(*UnixListener).accept(0xc420241da0, 0x59399e, 0xc42030ade8, 0x616a3d)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/net/unixsock_posix.go:158 +0x32
net.(*UnixListener).Accept(0xc420241da0, 0xb073c8, 0xc420018200, 0xf43ba0, 0xc420304060)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/net/unixsock.go:229 +0x49
net/http.(*Server).Serve(0xc4202f4000, 0xf43060, 0xc420241da0, 0x0, 0x0)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/net/http/server.go:2273 +0x1ce
net/http.Serve(0xf43060, 0xc420241da0, 0xf3dc60, 0xc4202ee000, 0x0, 0x0)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/net/http/server.go:2091 +0x99
main.(*Daemon).Init.func5.1(0x0, 0x592578)
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/daemon.go:1027 +0x9b
gopkg.in/tomb%2ev2.(*Tomb).run(0xc4201303d8, 0xc4202c4050)
	/lxd/build/tmp.YjknBY3Tjh/go/src/gopkg.in/tomb.v2/tomb.go:163 +0x2b
created by gopkg.in/tomb%2ev2.(*Tomb).Go
	/lxd/build/tmp.YjknBY3Tjh/go/src/gopkg.in/tomb.v2/tomb.go:159 +0xd0

goroutine 78 [IO wait, 4 minutes]:
net.runtime_pollWait(0x7fe231917488, 0x72, 0x0)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc420152df0, 0x72, 0xc420069d68, 0xc4200920b0)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc420152df0, 0xf401a0, 0xc4200920b0)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).accept(0xc420152d90, 0x0, 0xf3e8a0, 0xc4202b2860)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/net/fd_unix.go:419 +0x238
net.(*UnixListener).accept(0xc42019e3a0, 0xc400000001, 0xc420277170, 0x9f9480)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/net/unixsock_posix.go:158 +0x32
net.(*UnixListener).Accept(0xc42019e3a0, 0xc420277140, 0x9f9480, 0xf2d310, 0xa30c00)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/net/unixsock.go:229 +0x49
net/http.(*Server).Serve(0xc42024ba00, 0xf43060, 0xc42019e3a0, 0x0, 0x0)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/net/http/server.go:2273 +0x1ce
main.(*Daemon).Init.func5.3(0x0, 0x592578)
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/daemon.go:1037 +0x5a
gopkg.in/tomb%2ev2.(*Tomb).run(0xc4201303d8, 0xc4202c4060)
	/lxd/build/tmp.YjknBY3Tjh/go/src/gopkg.in/tomb.v2/tomb.go:163 +0x2b
created by gopkg.in/tomb%2ev2.(*Tomb).Go
	/lxd/build/tmp.YjknBY3Tjh/go/src/gopkg.in/tomb.v2/tomb.go:159 +0xd0

goroutine 7048 [select]:
main.(*lxcContainerOperation).Create.func1(0xc4202ea2c0)
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/container_lxc.go:54 +0x1b8
created by main.(*lxcContainerOperation).Create
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/container_lxc.go:62 +0xdd

goroutine 6321 [select]:
main.(*lxcContainerOperation).Create.func1(0xc420140380)
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/container_lxc.go:54 +0x1b8
created by main.(*lxcContainerOperation).Create
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/container_lxc.go:62 +0xdd

goroutine 7846 [chan receive]:
main.(*execWs).Do.func1(0xc4201ca480, 0xc4202f5180, 0xc4201ca420, 0xc4204c4010, 0x1, 0x1)
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/container_exec.go:142 +0x98
created by main.(*execWs).Do
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/container_exec.go:201 +0xda8

goroutine 7813 [chan receive]:
main.(*operationWebSocket).Render(0xc4204e02e0, 0xf431e0, 0xc420096000, 0xc4204e02e0, 0xffffffffffffff01)
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/operations.go:536 +0x94
main.(*Daemon).createCmd.func1(0xf431e0, 0xc420096000, 0xc4201003c0)
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/daemon.go:332 +0x3ca
net/http.HandlerFunc.ServeHTTP(0xc4201e7d60, 0xf431e0, 0xc420096000, 0xc4201003c0)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/net/http/server.go:1726 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc4201e6820, 0xf431e0, 0xc420096000, 0xc4201003c0)
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/gorilla/mux/mux.go:114 +0x10d
main.(*lxdHttpServer).ServeHTTP(0xc4202ee000, 0xf431e0, 0xc420096000, 0xc4201000f0)
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/daemon.go:1381 +0x237
net/http.serverHandler.ServeHTTP(0xc4202f4000, 0xf431e0, 0xc420096000, 0xc4201000f0)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc4202f4180, 0xf43ae0, 0xc4202ea300)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/net/http/server.go:2293 +0x44d

goroutine 6608 [select]:
main.(*lxcContainerOperation).Create.func1(0xc420298180)
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/container_lxc.go:54 +0x1b8
created by main.(*lxcContainerOperation).Create
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/container_lxc.go:62 +0xdd

goroutine 7843 [syscall]:
syscall.Syscall(0x0, 0x11, 0xc420260000, 0x200, 0x19, 0x7fe231917d48, 0x5b1230)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x11, 0xc420260000, 0x200, 0x200, 0x1, 0x101000000000000, 0x0)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/syscall/zsyscall_linux_amd64.go:783 +0x55
syscall.Read(0x11, 0xc420260000, 0x200, 0x200, 0x0, 0x58e8b0, 0xc4204f4a78)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/syscall/syscall_unix.go:161 +0x49
os.(*File).read(0xc4204c4030, 0xc420260000, 0x200, 0x200, 0xc420054a01, 0xc420260000, 0xc4202fe240)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/os/file_unix.go:228 +0x4f
os.(*File).Read(0xc4204c4030, 0xc420260000, 0x200, 0x200, 0x0, 0x200, 0xc41ffd8563)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/os/file.go:101 +0x59
encoding/json.(*Decoder).refill(0xc4204f51e0, 0x1a0, 0xa67c80)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/encoding/json/stream.go:152 +0xfa
encoding/json.(*Decoder).readValue(0xc4204f51e0, 0x0, 0x0, 0x1a0)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/encoding/json/stream.go:128 +0x198
encoding/json.(*Decoder).Decode(0xc4204f51e0, 0x9bde20, 0xc4202ee0b0, 0x0, 0xc4202eb440)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/encoding/json/stream.go:57 +0x8e
main.(*containerLXC).Exec(0xc420106000, 0xc4202eb440, 0x3, 0x4, 0xc420305680, 0xc4204c4020, 0xc4204c4020, 0xc4204c4020, 0x0, 0x0, ...)
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/container_lxc.go:4684 +0xade
main.(*execWs).Do(0xc4202f5180, 0xc4204a0580, 0x4, 0xc42046df98)
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/container_exec.go:257 +0x5ad
main.(*execWs).Do-fm(0xc4204a0580, 0xc42020cbd0, 0xc4201540a0)
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/container_exec.go:395 +0x34
main.(*operation).Run.func1(0xc4204a0580, 0xc4202c6a20)
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/operations.go:112 +0x4a
created by main.(*operation).Run
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/operations.go:139 +0x2f9

goroutine 6548 [select]:
main.(*lxcContainerOperation).Create.func1(0xc420298f40)
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/container_lxc.go:54 +0x1b8
created by main.(*lxcContainerOperation).Create
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/container_lxc.go:62 +0xdd

goroutine 7386 [select]:
main.(*lxcContainerOperation).Create.func1(0xc420506d80)
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/container_lxc.go:54 +0x1b8
created by main.(*lxcContainerOperation).Create
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/container_lxc.go:62 +0xdd

goroutine 6109 [select]:
main.(*lxcContainerOperation).Create.func1(0xc4205121c0)
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/container_lxc.go:54 +0x1b8
created by main.(*lxcContainerOperation).Create
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/container_lxc.go:62 +0xdd

goroutine 6153 [select]:
main.(*lxcContainerOperation).Create.func1(0xc4202980c0)
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/container_lxc.go:54 +0x1b8
created by main.(*lxcContainerOperation).Create
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/container_lxc.go:62 +0xdd

goroutine 7814 [runnable]:
sync.(*Mutex).Unlock(0xc4202f51c8)
	/lxd/build/tmp.YjknBY3Tjh/go/golang/src/sync/mutex.go:102
main.(*execWs).Connect(0xc4202f5180, 0xc4204a0580, 0xc4201003c0, 0xf431e0, 0xc420096000, 0xc42046ceb8, 0x59a8ec)
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/container_exec.go:70 +0x23a
main.(*execWs).Connect-fm(0xc4204a0580, 0xc4201003c0, 0xf431e0, 0xc420096000, 0xc42046cf90, 0x837057)
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/container_exec.go:395 +0x52
main.(*operation).Connect.func1(0xc4201003c0, 0xf431e0, 0xc420096000, 0xc4204a0580, 0xc4201ca960)
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/operations.go:226 +0x6e
created by main.(*operation).Connect
	/lxd/build/tmp.YjknBY3Tjh/go/src/github.com/lxc/lxd/lxd/operations.go:237 +0xe9
```

**Comment by stgraber** [comment]
The error here is about concurrent read and write to the map (s.conns), changes to the structs that the map points to wouldn't cause that error so even if a websocket mirror was already operating on one of the connections that the map points to, this wouldn't cause the problem.

**Comment by stgraber** [comment]
I think I figured it out, allConnected will trigger even if the control socket isn't connected (fd -1), that's on purpose as the control socket isn't mandatory, but this means that s.conns will be modified whenever the control socket does get connected and that can be much after allConnected was triggered.

As a result, all reads and writes to this map must be protected.

**Comment by stgraber** [comment]
Well, not quite all. If the access to s.conns is done after controlConnected has triggered, then it's not necessary.

**Comment by stgraber** [comment]
But we should just protect them all so that we're less likely to introduce that bug again.
