### ISSUE TITLE
Infinite random crashes (on updating images?)

### ISSUE THREAD

**Issue by n0guest** [lxc/lxd#3521]
# Required information

 * Distribution: Ubuntu
 * Distribution version:  16.04/xenial 64bit
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-83-generic
   * LXC version: 2.0.8-0ubuntu3~ubuntu16.04.1~ppa1
   * LXD version: 2.15-0ubuntu6~ubuntu16.04.1~ppa1
   * Storage backend in use: zfs

# Issue description

It looks like random crashes on background images update. Here is what i've found in logs via journalctl:

```
Jul 10 22:57:22 servername.tld systemd[1]: Started LXD - main daemon.
Jul 10 22:57:23 servername.tld lxd[4781]: panic: runtime error: invalid memory address or nil pointer dereference
Jul 10 22:57:23 servername.tld lxd[4781]: [signal 0xb code=0x1 addr=0x0 pc=0x97da86]
Jul 10 22:57:23 servername.tld lxd[4781]: goroutine 804 [running]:
Jul 10 22:57:23 servername.tld lxd[4781]: panic(0xc0dec0, 0xc82000e090)
Jul 10 22:57:23 servername.tld lxd[4781]:         /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
Jul 10 22:57:23 servername.tld lxd[4781]: github.com/lxc/lxd/shared/cancel.CancelableDownload.func1(0x0, 0xc8201f07b0, 0xc8203e0700, 0xc82043c8a0)
Jul 10 22:57:23 servername.tld lxd[4781]:         /build/lxd-UCLCzg/lxd-2.15/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/shared/cancel/canceler.go:37 +0x66
Jul 10 22:57:23 servername.tld lxd[4781]: created by github.com/lxc/lxd/shared/cancel.CancelableDownload
Jul 10 22:57:23 servername.tld lxd[4781]:         /build/lxd-UCLCzg/lxd-2.15/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/shared/cancel/canceler.go:47 +0x81
Jul 10 22:57:23 servername.tld systemd[1]: lxd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 10 22:57:23 servername.tld systemd[1]: lxd.service: Unit entered failed state.
Jul 10 22:57:23 servername.tld systemd[1]: lxd.service: Failed with result 'exit-code'.
Jul 10 22:57:23 servername.tld systemd[1]: lxd.service: Service hold-off time over, scheduling restart.
Jul 10 22:57:23 servername.tld systemd[1]: Stopped LXD - main daemon.

```

# Information to attach

And in the same time in /var/log/lxd/lxd.log:

```
lvl=info msg="LXD 2.15 is starting in normal mode" path=/var/lib/lxd t=2017-07-10T22:57:22+0300
lvl=info msg="Kernel uid/gid map:" t=2017-07-10T22:57:22+0300
lvl=info msg=" - u 0 0 4294967295" t=2017-07-10T22:57:22+0300
lvl=info msg=" - g 0 0 4294967295" t=2017-07-10T22:57:22+0300
lvl=info msg="Configured LXD uid/gid map:" t=2017-07-10T22:57:22+0300
lvl=info msg=" - u 0 100000 65536" t=2017-07-10T22:57:22+0300
lvl=info msg=" - g 0 100000 65536" t=2017-07-10T22:57:22+0300
lvl=info msg="Connecting to a remote simplestreams server" t=2017-07-10T22:57:22+0300
lvl=info msg="Connecting to a remote simplestreams server" t=2017-07-10T22:57:22+0300
lvl=info msg="Expiring log files" t=2017-07-10T22:57:22+0300
lvl=info msg="Done expiring log files" t=2017-07-10T22:57:22+0300
lvl=info msg="Starting /dev/lxd handler" t=2017-07-10T22:57:22+0300
lvl=info msg="LXD is socket activated" t=2017-07-10T22:57:22+0300
lvl=info msg="REST API daemon:" t=2017-07-10T22:57:22+0300
lvl=info msg=" - binding Unix socket" socket=/var/lib/lxd/unix.socket t=2017-07-10T22:57:22+0300
lvl=info msg=" - binding TCP socket" socket=[::]:8443 t=2017-07-10T22:57:22+0300
lvl=info msg="Pruning expired images" t=2017-07-10T22:57:22+0300
lvl=info msg="Updating images" t=2017-07-10T22:57:22+0300
lvl=info msg="Done pruning expired images" t=2017-07-10T22:57:22+0300
lvl=info msg="Connecting to a remote simplestreams server" t=2017-07-10T22:57:22+0300
alias=debian/wheezy lvl=info msg="Downloading image" server=https://images.linuxcontainers.org t=2017-07-10T22:57:23+0300
lvl=info msg="LXD 2.15 is starting in normal mode" path=/var/lib/lxd t=2017-07-10T22:57:23+0300
lvl=info msg="Kernel uid/gid map:" t=2017-07-10T22:57:23+0300
lvl=info msg=" - u 0 0 4294967295" t=2017-07-10T22:57:23+0300
lvl=info msg=" - g 0 0 4294967295" t=2017-07-10T22:57:23+0300
lvl=info msg="Configured LXD uid/gid map:" t=2017-07-10T22:57:23+0300
lvl=info msg=" - u 0 100000 65536" t=2017-07-10T22:57:23+0300
lvl=info msg=" - g 0 100000 65536" t=2017-07-10T22:57:23+0300
lvl=info msg="Connecting to a remote simplestreams server" t=2017-07-10T22:57:24+0300
lvl=info msg="Connecting to a remote simplestreams server" t=2017-07-10T22:57:24+0300
lvl=info msg="Expiring log files" t=2017-07-10T22:57:24+0300
lvl=info msg="Done expiring log files" t=2017-07-10T22:57:24+0300
lvl=info msg="Starting /dev/lxd handler" t=2017-07-10T22:57:24+0300
lvl=info msg="LXD is socket activated" t=2017-07-10T22:57:24+0300
lvl=info msg="REST API daemon:" t=2017-07-10T22:57:24+0300
lvl=info msg=" - binding Unix socket" socket=/var/lib/lxd/unix.socket t=2017-07-10T22:57:24+0300
lvl=info msg=" - binding TCP socket" socket=[::]:8443 t=2017-07-10T22:57:24+0300
lvl=info msg="Pruning expired images" t=2017-07-10T22:57:24+0300
lvl=info msg="Updating images" t=2017-07-10T22:57:24+0300
lvl=info msg="Done pruning expired images" t=2017-07-10T22:57:24+0300
lvl=info msg="Connecting to a remote simplestreams server" t=2017-07-10T22:57:24+0300
alias=debian/wheezy lvl=info msg="Downloading image" server=https://images.linuxcontainers.org t=2017-07-10T22:57:25+0300
```

BTW, on this server there are only "official images" from https://cloud-images.ubuntu.com/releases and https://images.linuxcontainers.org:

```
# lxc image list
+-------+--------------+--------+-----------------------------------------------+--------+----------+------------------------------+
| ALIAS | FINGERPRINT  | PUBLIC |                  DESCRIPTION                  |  ARCH  |   SIZE   |         UPLOAD DATE          |
+-------+--------------+--------+-----------------------------------------------+--------+----------+------------------------------+
|       | 2ccf68b4c9ce | no     | Debian jessie amd64 (20170709_22:42)          | x86_64 | 102.75MB | Jul 10, 2017 at 7:59pm (UTC) |
+-------+--------------+--------+-----------------------------------------------+--------+----------+------------------------------+
|       | 745354737c38 | no     | ubuntu 14.04 LTS amd64 (release) (20170629)   | x86_64 | 120.62MB | Jun 30, 2017 at 6:28pm (UTC) |
+-------+--------------+--------+-----------------------------------------------+--------+----------+------------------------------+
|       | 7a7ff654cbd8 | no     | ubuntu 16.04 LTS amd64 (release) (20170619.1) | x86_64 | 153.83MB | Jun 30, 2017 at 6:28pm (UTC) |
+-------+--------------+--------+-----------------------------------------------+--------+----------+------------------------------+
|       | 806f892f7756 | no     | Centos 6 amd64 (20170709_02:16)               | x86_64 | 66.31MB  | Jul 10, 2017 at 7:59pm (UTC) |
+-------+--------------+--------+-----------------------------------------------+--------+----------+------------------------------+
|       | be44a88990ae | no     | Debian wheezy amd64 (20170709_22:42)          | x86_64 | 92.65MB  | Jul 10, 2017 at 7:58pm (UTC) |
+-------+--------------+--------+-----------------------------------------------+--------+----------+------------------------------+
|       | c46db73ecfa6 | no     | Debian stretch amd64 (20170709_22:42)         | x86_64 | 103.39MB | Jul 10, 2017 at 7:59pm (UTC) |
+-------+--------------+--------+-----------------------------------------------+--------+----------+------------------------------+
|       | fd45db64e6cc | no     | Centos 7 amd64 (20170709_02:31)               | x86_64 | 65.39MB  | Jul 10, 2017 at 7:58pm (UTC) |
+-------+--------------+--------+-----------------------------------------------+--------+----------+------------------------------+
```
Is there any other information required?

**Comment by stgraber** [comment]
Can you include /var/lib/dpkg.log? I'm wondering what exact version of the package you had installed at the time of the crash as we fixed something that looks identical to your problem a week or so ago.

**Comment by n0guest** [comment]
Here is grep'ed selection from all dpkg logs:

```
# grep -E 'lxc|lxd' log | grep -v status
2017-05-27 18:14:05 install lxc-common:amd64 <none> 2.0.7-0ubuntu1~16.04.2
2017-05-27 18:14:07 install liblxc1:amd64 <none> 2.0.7-0ubuntu1~16.04.2
2017-05-27 18:14:08 install lxd-client:amd64 <none> 2.0.9-0ubuntu1~16.04.2
2017-05-27 18:14:09 install lxcfs:amd64 <none> 2.0.6-0ubuntu1~16.04.1
2017-05-27 18:14:13 install lxd:amd64 <none> 2.0.9-0ubuntu1~16.04.2
2017-05-27 18:18:53 configure lxcfs:amd64 2.0.6-0ubuntu1~16.04.1 <none>
2017-05-27 18:18:53 configure lxd-client:amd64 2.0.9-0ubuntu1~16.04.2 <none>
2017-05-27 18:20:28 configure liblxc1:amd64 2.0.7-0ubuntu1~16.04.2 <none>
2017-05-27 18:20:28 configure lxd:amd64 2.0.9-0ubuntu1~16.04.2 <none>
2017-05-27 18:20:34 configure lxc-common:amd64 2.0.7-0ubuntu1~16.04.2 <none>
2017-05-28 13:59:47 upgrade lxd:amd64 2.0.9-0ubuntu1~16.04.2 2.13-0ubuntu3~ubuntu16.04.1~ppa1
2017-05-28 13:59:49 upgrade lxd-client:amd64 2.0.9-0ubuntu1~16.04.2 2.13-0ubuntu3~ubuntu16.04.1~ppa1
2017-05-28 13:59:53 configure lxd:amd64 2.13-0ubuntu3~ubuntu16.04.1~ppa1 <none>
2017-05-28 13:59:53 configure lxd-client:amd64 2.13-0ubuntu3~ubuntu16.04.1~ppa1 <none>
2017-05-28 14:17:39 purge lxd:amd64 2.13-0ubuntu3~ubuntu16.04.1~ppa1 <none>
2017-05-28 14:17:39 remove lxd:amd64 2.13-0ubuntu3~ubuntu16.04.1~ppa1 <none>
2017-05-28 14:17:54 install lxd:amd64 <none> 2.13-0ubuntu3~ubuntu16.04.1~ppa1
2017-05-28 14:17:56 configure lxd:amd64 2.13-0ubuntu3~ubuntu16.04.1~ppa1 <none>
2017-06-29 00:58:45 upgrade liblxc1:amd64 2.0.7-0ubuntu1~16.04.2 2.0.8-0ubuntu3~ubuntu16.04.1~ppa1
2017-06-29 00:58:46 upgrade lxc-common:amd64 2.0.7-0ubuntu1~16.04.2 2.0.8-0ubuntu3~ubuntu16.04.1~ppa1
2017-06-29 00:59:14 upgrade lxcfs:amd64 2.0.6-0ubuntu1~16.04.1 2.0.7-0ubuntu4~ubuntu16.04.1~ppa1
2017-06-29 00:59:15 upgrade lxd:amd64 2.13-0ubuntu3~ubuntu16.04.1~ppa1 2.15-0ubuntu1~ubuntu16.04.1~ppa1
2017-06-29 00:59:16 upgrade lxd-client:amd64 2.13-0ubuntu3~ubuntu16.04.1~ppa1 2.15-0ubuntu1~ubuntu16.04.1~ppa1
2017-06-29 01:01:21 configure lxcfs:amd64 2.0.7-0ubuntu4~ubuntu16.04.1~ppa1 <none>
2017-06-29 01:01:22 configure lxd-client:amd64 2.15-0ubuntu1~ubuntu16.04.1~ppa1 <none>
2017-06-29 01:01:34 configure liblxc1:amd64 2.0.8-0ubuntu3~ubuntu16.04.1~ppa1 <none>
2017-06-29 01:01:34 configure lxc-common:amd64 2.0.8-0ubuntu3~ubuntu16.04.1~ppa1 <none>
2017-06-29 01:01:35 configure lxd:amd64 2.15-0ubuntu1~ubuntu16.04.1~ppa1 <none>
2017-06-29 02:15:06 remove lxd:amd64 2.15-0ubuntu1~ubuntu16.04.1~ppa1 <none>
2017-06-29 02:15:07 purge lxd:amd64 2.15-0ubuntu1~ubuntu16.04.1~ppa1 <none>
2017-06-29 02:15:20 install lxd:amd64 <none> 2.15-0ubuntu1~ubuntu16.04.1~ppa1
2017-06-29 02:15:22 configure lxd:amd64 2.15-0ubuntu1~ubuntu16.04.1~ppa1 <none>
2017-06-30 20:51:52 upgrade lxd:amd64 2.15-0ubuntu1~ubuntu16.04.1~ppa1 2.15-0ubuntu2~ubuntu16.04.1~ppa1
2017-06-30 20:51:55 upgrade lxd-client:amd64 2.15-0ubuntu1~ubuntu16.04.1~ppa1 2.15-0ubuntu2~ubuntu16.04.1~ppa1
2017-06-30 20:51:59 configure lxd:amd64 2.15-0ubuntu2~ubuntu16.04.1~ppa1 <none>
2017-06-30 20:51:59 configure lxd-client:amd64 2.15-0ubuntu2~ubuntu16.04.1~ppa1 <none>
2017-07-10 22:58:33 upgrade lxd:amd64 2.15-0ubuntu2~ubuntu16.04.1~ppa1 2.15-0ubuntu6~ubuntu16.04.1~ppa1
2017-07-10 22:58:35 upgrade lxd-client:amd64 2.15-0ubuntu2~ubuntu16.04.1~ppa1 2.15-0ubuntu6~ubuntu16.04.1~ppa1
2017-07-10 22:58:37 configure lxd-client:amd64 2.15-0ubuntu6~ubuntu16.04.1~ppa1 <none>
2017-07-10 22:58:38 configure lxd:amd64 2.15-0ubuntu6~ubuntu16.04.1~ppa1 <none>
```

Few "purges" in the log above are my experiments. But i doubt, that they can related to current issue somehow.

**Comment by stgraber** [comment]
Ok, so you were on -0ubuntu1 until 22:58 on the 10th, which means that you indeed had the bug and now have the fixed LXD.

**Comment by stgraber** [comment]
Let us know if you see any such crash after 22:58 on the 10th of July, if so, it means there's another bug in that part of the code that's not fixed with -0ubuntu6.
