### ISSUE TITLE
Unable to import containers from ZFS storage after reinstall

### ISSUE THREAD

**Issue by timbalmer** [lxc/lxd#3612]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
   * Kernel version: 4.4.0-87-generic
   * LXC version: 2.16 (I'm using ppa:ubuntu-lxc/lxd-stable)
   * LXD version: 2.16
   * Storage backend in use: ZFS

# Issue description

I'm testing some scenario's in my lab regarding lxc /lxd and one of those was deleting my LXD host VM, then install a new host server with a fresh Ubuntu 16.04 installation and then try to get the containers up and running again by importing the ZFS pool and containers.

Importing the ZFS pool is successful, I also mounted the storage on the right location but when I try to import the container I get the error message: "error: Post http://unix.socket/internal/containers: EOF" 

Tried to google this error but I found no results so I decided to open an issue here. 

# Steps to reproduce

 1. Reinstall the host (or simply purging lxd and reinstalling it gives the same result) 
 2. Import the ZFS pool and mount:
```
root@mcs-01:~# zpool list
no pools available
root@mcs-01:~# zpool import
   pool: zfs-disk1
     id: 11737840692433131060
  state: ONLINE
 action: The pool can be imported using its name or numeric identifier.
 config:

        zfs-disk1   ONLINE
          sdb       ONLINE
root@mcs-01:~# zpool import zfs-disk1
root@mcs-01:~# zpool list
NAME        SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
zfs-disk1  24.9G   405M  24.5G         -     0%     1%  1.00x  ONLINE  -
root@mcs-01:~# zfs list
NAME                                                                                USED  AVAIL  REFER  MOUNTPOINT
zfs-disk1                                                                           405M  23.7G    19K  none
zfs-disk1/containers                                                                104M  23.7G    19K  none
zfs-disk1/containers/scnd-serv                                                     90.9M  23.7G   376M  /var/lib/lxd/storage-pools/zfs-disk1/containers/scnd-serv
zfs-disk1/containers/thrt-serv                                                     12.8M  23.7G   301M  /var/lib/lxd/storage-pools/zfs-disk1/containers/thrt-serv
zfs-disk1/custom                                                                     19K  23.7G    19K  none
zfs-disk1/deleted                                                                    19K  23.7G    19K  none
zfs-disk1/images                                                                    300M  23.7G    19K  none
zfs-disk1/images/8220e89e33e6f62b56cb451cfed61574074416a66a6e7c61ff574d95572e6661   300M  23.7G   300M  none
zfs-disk1/snapshots                                                                  19K  23.7G    19K  none
root@mcs-01:~# zfs mount zfs-disk1/containers/scnd-serv
root@mcs-01:~# zfs mount
zfs-disk1/containers/scnd-serv  /var/lib/lxd/storage-pools/zfs-disk1/containers/scnd-serv
root@mcs-01:~# ls -l /var/lib/lxd/storage-pools/zfs-disk1/containers/scnd-serv
total 6
-r--------  1 root   root   2373 Jul 30 18:44 backup.yaml
-rw-r--r--  1 root   root   1566 Jul 21 17:37 metadata.yaml
drwxr-xr-x 22 100000 100000   22 Jul 21 16:38 rootfs
drwxr-xr-x  2 root   root      8 Jul 21 17:37 templates


```

 3.  Try to import the container:
```
root@mcs-01:~# lxd import scnd-serv
error: Post http://unix.socket/internal/containers: EOF
root@mcs-01:~# lxd import scnd-serv --force
error: Post http://unix.socket/internal/containers: EOF
```

# Information to attach

In syslog I see this errors when I run the lxd import command.

```
Jul 31 15:18:17 mcs-01 lxd[4733]: 2017/07/31 15:18:17 http: panic serving @: runtime error: invalid memory address or nil pointer dereference
Jul 31 15:18:17 mcs-01 lxd[4733]: goroutine 288 [running]:
Jul 31 15:18:17 mcs-01 lxd[4733]: net/http.(*conn).serve.func1(0xc82024e280)
Jul 31 15:18:17 mcs-01 lxd[4733]: #011/usr/lib/go-1.6/src/net/http/server.go:1389 +0xc1
Jul 31 15:18:17 mcs-01 lxd[4733]: panic(0xc732c0, 0xc82000e090)
Jul 31 15:18:17 mcs-01 lxd[4733]: #011/usr/lib/go-1.6/src/runtime/panic.go:443 +0x4e9
Jul 31 15:18:17 mcs-01 lxd[4733]: main.internalImport(0xc8200cca20, 0xc82026a0e0, 0x0, 0x0)
Jul 31 15:18:17 mcs-01 lxd[4733]: #011/build/lxd-vUaaF7/lxd-2.16/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxd/api_internal.go:207 +0x39b9
Jul 31 15:18:17 mcs-01 lxd[4733]: main.(*Daemon).createCmd.func1(0x7ff845df4440, 0xc8201140d0, 0xc82026a0e0)
Jul 31 15:18:17 mcs-01 lxd[4733]: #011/build/lxd-vUaaF7/lxd-2.16/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxd/daemon.go:260 +0x7d0
Jul 31 15:18:17 mcs-01 lxd[4733]: net/http.HandlerFunc.ServeHTTP(0xc820263770, 0x7ff845df4440, 0xc8201140d0, 0xc82026a0e0)
Jul 31 15:18:17 mcs-01 lxd[4733]: #011/usr/lib/go-1.6/src/net/http/server.go:1618 +0x3a
Jul 31 15:18:17 mcs-01 lxd[4733]: github.com/gorilla/mux.(*Router).ServeHTTP(0xc820210c80, 0x7ff845df4440, 0xc8201140d0, 0xc82026a0e0)
Jul 31 15:18:17 mcs-01 lxd[4733]: #011/build/lxd-vUaaF7/lxd-2.16/obj-x86_64-linux-gnu/src/github.com/gorilla/mux/mux.go:114 +0x2a8
Jul 31 15:18:17 mcs-01 lxd[4733]: main.(*lxdHttpServer).ServeHTTP(0xc8202b4750, 0x7ff845df4440, 0xc8201140d0, 0xc82026a0e0)
Jul 31 15:18:17 mcs-01 lxd[4733]: #011/build/lxd-vUaaF7/lxd-2.16/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxd/daemon.go:1394 +0x4ad
Jul 31 15:18:17 mcs-01 lxd[4733]: net/http.serverHandler.ServeHTTP(0xc8202b2280, 0x7ff845df4440, 0xc8201140d0, 0xc82026a0e0)
Jul 31 15:18:17 mcs-01 lxd[4733]: #011/usr/lib/go-1.6/src/net/http/server.go:2081 +0x19e
Jul 31 15:18:17 mcs-01 lxd[4733]: net/http.(*conn).serve(0xc82024e280)
Jul 31 15:18:17 mcs-01 lxd[4733]: #011/usr/lib/go-1.6/src/net/http/server.go:1472 +0xf2e
Jul 31 15:18:17 mcs-01 lxd[4733]: created by net/http.(*Server).Serve
Jul 31 15:18:17 mcs-01 lxd[4733]: #011/usr/lib/go-1.6/src/net/http/server.go:2137 +0x44e
```

**Comment by stgraber** [comment]
Doh, pretty obvious bug...

**Comment by stgraber** [comment]
I just sent a branch to fix this. In the mean time, you can use this custom build of LXD 2.16 which includes this fix: https://dl.stgraber.org/lxd-3612 (sha256: 762fb704c558d688858ffea9fafbce7152ba68a8750f449240736134170d6345)

**Comment by timbalmer** [comment]
Thanks for the quick response and fix! I can confirm it's resolved with the custom binary you provided:

```
root@mcs-01:~# lxd import scnd-serv
root@mcs-01:~# lxc list
+-----------+---------+------+------+------------+-----------+
|   NAME    |  STATE  | IPV4 | IPV6 |    TYPE    | SNAPSHOTS |
+-----------+---------+------+------+------------+-----------+
| scnd-serv | STOPPED |      |      | PERSISTENT | 0         |
+-----------+---------+------+------+------------+-----------+
```
