### ISSUE TITLE
container not available after migrate

### ISSUE THREAD

**Issue by huegelc** [lxc/lxd#4220]
# Required information

 * Distribution: Ubuntu
 * Distribution version: Trusty
 * The output of "lxc info" or if that fails:
 ```
config: {}
api_extensions:
- id_map
- id_map_base
- resource_limits
api_status: stable
api_version: "1.0"
auth: trusted
auth_methods: []
public: false
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
  
    -----END CERTIFICATE-----
  certificate_fingerprint: 
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 3.13.0-137-generic
  server: lxd
  server_pid: 534
  server_version: 2.0.11
  storage: dir
  storage_version: ""
```

# Issue description

I´m using `lxc-to.lxd`script to import containers from lxc:

```
./lxc-to-lxd.py example.com
==> Processing container: example.com
Parsing LXC configuration
Checking for unsupported LXC configuration keys
Checking whether container has already been migrated
Checking for existing containers
Validating container mode
Validating container name
Validating whether incomplete AppArmor support is enabled
Validating whether mounting a minimal /dev is enabled
Validating that no custom haltsignal is set
Validating that no custom rebootsignal is set
Validating that no custom stopsignal is set
Validating container rootfs
Processing network configuration
Processing environment configuration
Processing container boot configuration
Processing container apparmor configuration
Processing container seccomp configuration
Processing container SELinux configuration
Processing container capabilities configuration
Processing container architecture configuration
Unknown architecture, assuming native.
Creating the container
Copying container rootfs
Container is ready to use

==> Migration summary
example.com: SUCCESS
```

but `lxc list`doesnt show the container at all.

```
+--------+---------+------------------+------+------------+-----------+
|  NAME  |  STATE  |       IPV4       | IPV6 |    TYPE    | SNAPSHOTS |
+--------+---------+------------------+------+------------+-----------+
+--------+---------+------------------+------+------------+-----------+
```

# Steps to reproduce

 1. migrate container with lxc-to-lxd script
 2. lxc list

**Comment by stgraber** [comment]
Hmm, that's odd, do you maybe have both the LXD snap and deb installed together on the same system?

That would explain why "lxc list" won't show it (it shows the containers managed by the snap) even though lxc-to-lxd succeeded (to move it to the deb LXD path).

**Comment by huegelc** [comment]
Thank for your reply. Yes, I had snapd installed once bute removed/purged it.

```
which lxc
/usr/bin/lxc
```
```
lxc --version
2.0.11
```

```
uname -a
Linux Ubuntu-1404-trusty-64-minimal 3.13.0-137-generic #186-Ubuntu SMP Mon Dec 4 19:09:19 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by huegelc** [comment]
I dont know if its relevant but prior to migration I had to create the rootfs manually:
```
Copying container rootfs
Traceback (most recent call last):
  File "./lxc-to-lxd.py", line 621, in <module>
    container_name, args)
  File "./lxc-to-lxd.py", line 556, in convert_container
    os.mkdir(lxd_rootfs)
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/lxd/containers/example.com/rootfs'
```

**Comment by stgraber** [comment]
Oh, hold on, that's not a valid container name, not sure why it didn't fail earlier...
LXD doesn't allow dots in container names.

**Comment by huegelc** [comment]
You´re absolutely right. Thank you
