### ISSUE TITLE
Unable to access containers after reboot 

### ISSUE THREAD

**Issue by HW-Siew** [lxc/lxd#4465]
# Required information

 * Distribution: ubuntu 
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-1054-aws x86_64
   * LXC version: 3.0.0
   * LXD version: 3.0.0
   * Storage backend in use : zfs

# Issue description

After reboot my machine, I tried to list the containers on the machine. it showed an error message below. 

lxc list
`Error: Get http://unix.socket/1.0: dial unix /var/snap/lxd/common/lxd/unix.socket: connect: connection refused`

Not really sure how to reproduce this. It happens right after I rebooted my machine.

Additional information

```
sudo lxd --group lxd
`goroutine 31 [running]:
github.com/CanonicalLtd/dqlite/internal/trace.(*Tracer).Panic(0xc4202b8dc0, 0xfbfd61, 0xd, 0x0, 0x0, 0x0)
        /build/lxd-latest-candidate/parts/lxd/go/src/github.com/CanonicalLtd/dqlite/internal/trace/tracer.go:57 +0x12c
github.com/CanonicalLtd/dqlite/internal/replication.(*FSM).applyUndo(0xc4202815e0, 0xc4202b8dc0, 0xc421163058, 0x1, 0xc4202b8c80)
        /build/lxd-latest-candidate/parts/lxd/go/src/github.com/CanonicalLtd/dqlite/internal/replication/fsm.go:296 +0x209
github.com/CanonicalLtd/dqlite/internal/replication.(*FSM).apply(0xc4202815e0, 0xc4202b8c80, 0xc420ff47b0, 0x6, 0x2ae219f700000001)
        /build/lxd-latest-candidate/parts/lxd/go/src/github.com/CanonicalLtd/dqlite/internal/replication/fsm.go:116 +0x4b6
github.com/CanonicalLtd/dqlite/internal/replication.(*FSM).Apply(0xc4202815e0, 0xc420ff47b0, 0x0, 0x0)
        /build/lxd-latest-candidate/parts/lxd/go/src/github.com/CanonicalLtd/dqlite/internal/replication/fsm.go:81 +0xe2
github.com/hashicorp/raft.(*Raft).runFSM.func1(0xc42023f360)
        /build/lxd-latest-candidate/parts/lxd/go/src/github.com/hashicorp/raft/fsm.go:57 +0x15a
github.com/hashicorp/raft.(*Raft).runFSM(0xc42020d080)
        /build/lxd-latest-candidate/parts/lxd/go/src/github.com/hashicorp/raft/fsm.go:120 +0x2fa
github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.runFSM)-fm()
        /build/lxd-latest-candidate/parts/lxd/go/src/github.com/hashicorp/raft/api.go:506 +0x2a
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc42020d080, 0xc42018fe40)
        /build/lxd-latest-candidate/parts/lxd/go/src/github.com/hashicorp/raft/state.go:146 +0x53
created by github.com/hashicorp/raft.(*raftState).goFunc
        /build/lxd-latest-candidate/parts/lxd/go/src/github.com/hashicorp/raft/state.go:144 +0x66`
```

**Comment by freeekanayaka** [comment]
Please could you run "sudo lxd --group lxd --verbose --debug" instead of just "sudo lxd --group lxd" ?

**Comment by freeekanayaka** [comment]
I think this is most probably a issue we fixed in the snap (which sports a newer version of dqlite)

**Comment by freeekanayaka** [comment]
We'd need you to either migrate to the snap version, or wait for @stgraber to release an update for the deb package in bionic (which should happen soon).

**Comment by HW-Siew** [comment]
Hi @fedordikarev, thanks for the prompt reply.

'sudo lxd --group lxd --verbose --debug' shows the same thing as 'sudo lxd --group lxd'. Except at the beginning which is attached as follow.

```
DBUG[04-17|10:50:02] Connecting to a local LXD over a Unix socket
DBUG[04-17|10:50:02] Sending request to LXD                   etag= method=GET url=http://unix.socket/1.0
INFO[04-17|10:50:02] LXD 3.0.0 is starting in normal mode     path=/var/snap/lxd/common/lxd
INFO[04-17|10:50:02] Kernel uid/gid map:
INFO[04-17|10:50:02]  - u 0 0 4294967295
INFO[04-17|10:50:02]  - g 0 0 4294967295
INFO[04-17|10:50:02] Configured LXD uid/gid map:
INFO[04-17|10:50:02]  - u 0 1000000 1000000000
INFO[04-17|10:50:02]  - g 0 1000000 1000000000
WARN[04-17|10:50:02] CGroup memory swap accounting is disabled, swap limits will be ignored.
INFO[04-17|10:50:02] Initializing database gateway
INFO[04-17|10:50:02] Start database node                      address= id=1
INFO[04-17|10:50:02] Raft: Restored from snapshot 1-16470-1523938012459
INFO[04-17|10:50:02] Raft: Initial configuration (index=1): [{Suffrage:Voter ID:1 Address:0}]
INFO[04-17|10:50:02] LXD isn't socket activated
DBUG[04-17|10:50:02] Connecting to a local LXD over a Unix socket
DBUG[04-17|10:50:02] Sending request to LXD                   etag= method=GET url=http://unix.socket/1.0
DBUG[04-17|10:50:02] Detected stale unix socket, deleting
DBUG[04-17|10:50:02] Detected stale unix socket, deleting
INFO[04-17|10:50:02] Starting /dev/lxd handler:
INFO[04-17|10:50:02]  - binding devlxd socket                 socket=/var/snap/lxd/common/lxd/devlxd/sock
INFO[04-17|10:50:02] REST API daemon:
INFO[04-17|10:50:02]  - binding Unix socket                   socket=/var/snap/lxd/common/lxd/unix.socket
INFO[04-17|10:50:02]  - binding TCP socket                    socket=[::]:8443
INFO[04-17|10:50:02] Raft: Node at 0 [Leader] entering Leader state`
```

**Comment by freeekanayaka** [comment]
Actually the dqlite fix I've mentioned seems to be included in the latest bionic package 3.0.0-0ubuntu3. How did you get LXD 3.0.0 running on 16.04? I don't think we released backports for that yet. Are you perhaps using the LXD snap already? If so, which revision? (snap info lxd)

**Comment by stgraber** [comment]
@freeekanayaka based on the error and logs above, this is using the snap.

**Comment by HW-Siew** [comment]
Hi @freeekanayaka, yes i am using snap lxd. the result of snap info lxd is attached below.

```
name:      lxd
summary:   System container manager and API
publisher: canonical
contact:   https://github.com/lxc/lxd/issues
license:   unknown
description: |
  LXD is a container manager for system containers.

  It offers a REST API to remotely manage containers over the network, using an image based workflow
  and with support for live migration.

  Images are available for all Ubuntu releases and architectures as well as for a wide number of other
  Linux distributions.

  LXD containers are lightweight, secure by default and a great alternative to virtual machines.
commands:
  - lxd.benchmark
  - lxd.check-kernel
  - lxd.database
  - lxd.lxc
  - lxd
  - lxd.migrate
services:
  lxd.daemon: simple, enabled, active
snap-id:   J60k4JY0HppjwOjW8dZdYc8obXKxujRu
tracking:  stable
refreshed: 2018-04-09T23:13:08Z
installed:       3.0.0       (6643) 56MB -
channels:
  stable:        3.0.0       (6643) 56MB -
  candidate:     3.0.0       (6729) 56MB -
  beta:          ↑
  edge:          git-7c74528 (6747) 56MB -
  2.0/stable:    2.0.11      (6627) 27MB -
  2.0/candidate: 2.0.11      (6627) 27MB -
  2.0/beta:      ↑
  2.0/edge:      git-d71807e (6630) 25MB -
  3.0/stable:    3.0.0       (6649) 56MB -
  3.0/candidate: 3.0.0       (6730) 56MB -
  3.0/beta:      ↑
  3.0/edge:      git-bd47a49 (6716) 56MB -
```

**Comment by HW-Siew** [comment]
hi @stgraber, I tried to run `lxd --debug --group lxd` in one terminal and it existed with code 2 (echo $?). I then tried to run `lxc list` in another terminal, unfortunately, it doesn't work still. It shows the same error message,

`Error: Get http://unix.socket/1.0: dial unix /var/snap/lxd/common/lxd/unix.socket: connect: connection refused`

Anything else I can try?

Thanks

**Comment by stgraber** [comment]
What did it print when it exited? The `lxc list` output is expected if lxd isn't running, but LXD exiting on startup appears different than what you reported before.

Can you try again:
 - sudo systemctl stop snap.lxd.daemon
 - sudo lxd --debug --group lxd

If that's hanging after initialization, then try `lxc list` from another terminal.
In either case, please show the full output.

**Comment by stgraber** [comment]
Sorry, should have commented... I'm not super familiar with the new DB code so it'd be best if @freeekanayaka took a look. He'll be back on Friday.

If you still have this system around, I'm sure a tarball of /var/lib/lxd/raft would be appreciated. Feel free to send privately.

**Comment by HW-Siew** [comment]
Hi @stgraber, that is weird. my system doesnt have the folder or file to the path'/var/lib/lxd/raft'.

**Comment by stgraber** [comment]
@HW-Siew not so weird since I gave you the wrong path, on your system, that'd be `/var/snap/lxd/common/lxd/raft`

**Comment by HW-Siew** [comment]
tarball is sent to your email stgraber@ubuntu.com. Thanks

**Comment by tchwpkgorg** [comment]
I'm seeing a similar issue, with Ubuntu 16.04 and LXD 3.0 from snap.

I've described it a bit more in this thread:

https://lists.linuxcontainers.org/pipermail/lxc-users/2018-May/014243.html

What other information should I provide? My system also doesn't have /var/snap/lxd/common/lxd/raft/ directory.

**Comment by stgraber** [comment]
Closing this issue as we didn't get the needed information over the past 12 days.

@tchwpkgorg for your problem, your best bet is to run `lxd --debug --group lxd` that should give you some more details on what's going on. If the error you get indicates something wrong with LXD, please file a seperate issue.

**Comment by HW-Siew** [comment]
Sorry for late reply. Unfortunately, the server was deleted. I was told by freeekanayaka that this issue has been fixed in the latest 3.1 release. I will find time to have a try.

**Comment by krzysztofp** [comment]
Same issue here. We are using the 3.0.1 version on ubuntu 16.04:

```
$ sudo lxd --debug --group lxd
DBUG[07-20|17:34:51] Connecting to a local LXD over a Unix socket 
DBUG[07-20|17:34:51] Sending request to LXD                   etag= method=GET url=http://unix.socket/1.0
INFO[07-20|17:34:51] LXD 3.0.1 is starting in normal mode     path=/var/lib/lxd
INFO[07-20|17:34:51] Kernel uid/gid map: 
INFO[07-20|17:34:51]  - u 0 0 4294967295 
INFO[07-20|17:34:51]  - g 0 0 4294967295 
INFO[07-20|17:34:51] Configured LXD uid/gid map: 
INFO[07-20|17:34:51]  - u 0 3901088 65536 
INFO[07-20|17:34:51]  - g 0 3901088 65536 
INFO[07-20|17:34:51] Initializing local database 
INFO[07-20|17:34:51] Initializing database gateway 
INFO[07-20|17:34:51] Start database node                      address= id=1
INFO[07-20|17:34:51] Raft: Restored from snapshot 1-232-1532073073593 
INFO[07-20|17:34:51] Raft: Initial configuration (index=1): [{Suffrage:Voter ID:1 Address:0}] 
INFO[07-20|17:34:51] Raft: Node at 0 [Leader] entering Leader state 
INFO[07-20|17:34:51] LXD isn't socket activated 
DBUG[07-20|17:34:51] Connecting to a local LXD over a Unix socket 
DBUG[07-20|17:34:51] Sending request to LXD                   etag= method=GET url=http://unix.socket/1.0
DBUG[07-20|17:34:51] Detected stale unix socket, deleting 
DBUG[07-20|17:34:51] Detected stale unix socket, deleting 
INFO[07-20|17:34:51] Starting /dev/lxd handler: 
INFO[07-20|17:34:51]  - binding devlxd socket                 socket=/var/lib/lxd/devlxd/sock
INFO[07-20|17:34:51] REST API daemon: 
INFO[07-20|17:34:51]  - binding Unix socket                   socket=/var/lib/lxd/unix.socket
INFO[07-20|17:34:51] Initializing global database 
panic: txn not found

trace:
2018-07-20 17:34:51.32803: fsm: restore=232 start
2018-07-20 17:34:51.32803: fsm: restore=232 database size: 4096
2018-07-20 17:34:51.32804: fsm: restore=232 wal size: 247232
2018-07-20 17:34:51.32812: fsm: restore=232 filename: db.bin
2018-07-20 17:34:51.32812: fsm: restore=232 transaction ID: 
2018-07-20 17:34:51.32836: fsm: restore=232 open follower: db.bin
2018-07-20 17:34:51.32891: fsm: restore=232 done
2018-07-20 17:34:51.33019: fsm: term=1 index=233 cmd=frames txn=232 pages=3 commit=1 start
2018-07-20 17:34:51.33065: fsm: term=1 index=233 cmd=frames txn=232 pages=3 commit=1 unregister txn
2018-07-20 17:34:51.33065: fsm: term=1 index=233 cmd=frames txn=232 pages=3 commit=1 done
2018-07-20 17:34:51.33066: fsm: term=1 index=234 cmd=frames txn=233 pages=2 commit=1 start
2018-07-20 17:34:51.33091: fsm: term=1 index=234 cmd=frames txn=233 pages=2 commit=1 unregister txn
2018-07-20 17:34:51.33091: fsm: term=1 index=234 cmd=frames txn=233 pages=2 commit=1 done
2018-07-20 17:34:51.33092: fsm: term=1 index=235 cmd=frames txn=234 pages=3 commit=1 start
2018-07-20 17:34:51.33114: fsm: term=1 index=235 cmd=frames txn=234 pages=3 commit=1 unregister txn
2018-07-20 17:34:51.33114: fsm: term=1 index=235 cmd=frames txn=234 pages=3 commit=1 done
2018-07-20 17:34:51.33115: fsm: term=1 index=236 cmd=frames txn=235 pages=2 commit=1 start
2018-07-20 17:34:51.33136: fsm: term=1 index=236 cmd=frames txn=235 pages=2 commit=1 unregister txn
2018-07-20 17:34:51.33136: fsm: term=1 index=236 cmd=frames txn=235 pages=2 commit=1 done
2018-07-20 17:34:51.33138: fsm: term=1 index=237 cmd=frames txn=236 pages=3 commit=1 start
2018-07-20 17:34:51.33950: fsm: term=1 index=237 cmd=frames txn=236 pages=3 commit=1 unregister txn
2018-07-20 17:34:51.33950: fsm: term=1 index=237 cmd=frames txn=236 pages=3 commit=1 done
2018-07-20 17:34:51.33951: fsm: term=1 index=238 cmd=frames txn=237 pages=3 commit=1 start
2018-07-20 17:34:51.34762: fsm: term=1 index=238 cmd=frames txn=237 pages=3 commit=1 unregister txn
2018-07-20 17:34:51.34762: fsm: term=1 index=238 cmd=frames txn=237 pages=3 commit=1 done
2018-07-20 17:34:51.34811: fsm: term=1 index=239 cmd=frames txn=238 pages=2 commit=1 start
2018-07-20 17:34:51.35572: fsm: term=1 index=239 cmd=frames txn=238 pages=2 commit=1 unregister txn
2018-07-20 17:34:51.35573: fsm: term=1 index=239 cmd=frames txn=238 pages=2 commit=1 done
2018-07-20 17:34:51.35575: fsm: term=1 index=240 cmd=frames txn=239 pages=3 commit=1 start
2018-07-20 17:34:51.36384: fsm: term=1 index=240 cmd=frames txn=239 pages=3 commit=1 unregister txn
2018-07-20 17:34:51.36384: fsm: term=1 index=240 cmd=frames txn=239 pages=3 commit=1 done
2018-07-20 17:34:51.36393: fsm: term=1 index=241 cmd=frames txn=240 pages=3 commit=1 start
2018-07-20 17:34:51.38808: fsm: term=1 index=241 cmd=frames txn=240 pages=3 commit=1 unregister txn
2018-07-20 17:34:51.38808: fsm: term=1 index=241 cmd=frames txn=240 pages=3 commit=1 done
2018-07-20 17:34:51.38810: fsm: term=1 index=242 cmd=frames txn=241 pages=3 commit=1 start
2018-07-20 17:34:51.38832: fsm: term=1 index=242 cmd=frames txn=241 pages=3 commit=1 unregister txn
2018-07-20 17:34:51.38832: fsm: term=1 index=242 cmd=frames txn=241 pages=3 commit=1 done
2018-07-20 17:34:51.38833: fsm: term=1 index=243 cmd=undo txn=241 start


goroutine 38 [running]:
github.com/CanonicalLtd/dqlite/internal/trace.(*Tracer).Panic(0xc420571180, 0x1016aa8, 0xd, 0x0, 0x0, 0x0)
	/build/lxd-8ASgP_/lxd-3.0.1/obj-x86_64-linux-gnu/src/github.com/CanonicalLtd/dqlite/internal/trace/tracer.go:59 +0x12c
github.com/CanonicalLtd/dqlite/internal/replication.(*FSM).applyUndo(0xc420362ce0, 0xc420571180, 0xc4204b9888, 0x1, 0xc420571040)
	/build/lxd-8ASgP_/lxd-3.0.1/obj-x86_64-linux-gnu/src/github.com/CanonicalLtd/dqlite/internal/replication/fsm.go:335 +0x200
github.com/CanonicalLtd/dqlite/internal/replication.(*FSM).apply(0xc420362ce0, 0xc420571040, 0xc420574240, 0xc41725620c, 0x1725620c00000003)
	/build/lxd-8ASgP_/lxd-3.0.1/obj-x86_64-linux-gnu/src/github.com/CanonicalLtd/dqlite/internal/replication/fsm.go:116 +0x4b6
github.com/CanonicalLtd/dqlite/internal/replication.(*FSM).Apply(0xc420362ce0, 0xc420574240, 0x0, 0x0)
	/build/lxd-8ASgP_/lxd-3.0.1/obj-x86_64-linux-gnu/src/github.com/CanonicalLtd/dqlite/internal/replication/fsm.go:81 +0xaf
github.com/hashicorp/raft.(*Raft).runFSM.func1(0xc42052c060)
	/build/lxd-8ASgP_/lxd-3.0.1/obj-x86_64-linux-gnu/src/github.com/hashicorp/raft/fsm.go:57 +0x15a
github.com/hashicorp/raft.(*Raft).runFSM(0xc420225340)
	/build/lxd-8ASgP_/lxd-3.0.1/obj-x86_64-linux-gnu/src/github.com/hashicorp/raft/fsm.go:120 +0x2fa
github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.runFSM)-fm()
	/build/lxd-8ASgP_/lxd-3.0.1/obj-x86_64-linux-gnu/src/github.com/hashicorp/raft/api.go:506 +0x2a
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc420225340, 0xc420347100)
	/build/lxd-8ASgP_/lxd-3.0.1/obj-x86_64-linux-gnu/src/github.com/hashicorp/raft/state.go:146 +0x53
created by github.com/hashicorp/raft.(*raftState).goFunc
	/build/lxd-8ASgP_/lxd-3.0.1/obj-x86_64-linux-gnu/src/github.com/hashicorp/raft/state.go:144 +0x66
```

**Comment by stgraber** [comment]
@krzysztofp @freeekanayaka may be able to help here. The easiest way for us to track this down and get you online as fast as possible is to make a tarball of /var/lib/lxd/database and send that to us.

You can send it to me at stgraber_at_ubuntu_dot_com and I'll forward it to @freeekanayaka

**Comment by krzysztofp** [comment]
@stgraber just sent it over to you! Many thanks.

The funny thing I observed is when I delete the /var/lib/lxd/lxd.db I am getting above, and when I recreate it from backup I'm getting:

```Error: Both legacy and new local database files exists```.

**Comment by stgraber** [comment]
Yeah, /var/lib/lxd/lxd.db and /var/lib/lxd/raft aren't thing anymore, they should be /var/lib/lxd/database/local.db and /var/lib/lxd/database/global instead

**Comment by freeekanayaka** [comment]
@krzysztofp I've sent you back the tarball with the recovered database. Do you recall anything in particular that happened before this crash? If you still have the logs of LXD from around the time it happened the first time, that'd be useful too.
