### ISSUE TITLE
CRIU in LXD inside LXD

### ISSUE THREAD

**Issue by gabrik** [lxc/lxd#4980]
Hi all,

During the writing integration testing for https://github.com/lxc/pylxd/pull/319 I found an issue when try to live migrate a container between two hosts.
```
======================================================================
ERROR: A running container is migrated.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pylxd/integration/test_containers.py", line 208, in test_migrate
    an_migrated_container = an_container.migrate(client2, wait=True)
  File "/opt/pylxd/pylxd/models/container.py", line 434, in migrate
    raise e
  File "/opt/pylxd/pylxd/models/container.py", line 428, in migrate
    self.generate_migration_data(), wait=wait)
  File "/opt/pylxd/pylxd/models/container.py", line 265, in create
    client.operations.wait_for_operation(response.json()['operation'])
  File "/opt/pylxd/pylxd/models/operation.py", line 32, in wait_for_operation
    operation.wait()
  File "/opt/pylxd/pylxd/models/operation.py", line 63, in wait
    raise exceptions.LXDAPIException(response)
pylxd.exceptions.LXDAPIException: migration dump failed
(00.040792) Error (criu/ptrace.c:64): suspending seccomp failed: Operation not permitted
(00.040920) Error (criu/ptrace.c:54): Unable to detach from 1313: No such process
(00.040947) Error (criu/cr-dump.c:1628): Dumping FAILED.
```

The testing environment is composed by two LXD containers.

Ubuntu 16.04
Kernel: 4.4.0-134-generic
LXD: 2.0.11
CRIU: 2.6
LXC info:

```
config: {}
api_extensions:
- id_map
- id_map_base
- resource_limits
api_status: stable
api_version: "1.0"
auth: trusted
auth_methods: []
public: false
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: | ...
  certificate_fingerprint: dd4b789ea2e1cd32dc699e18aa087ba9e173423e7618a2cdca56b79b0eff0ce3
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-134-generic
  server: lxd
  server_pid: 1730
  server_version: 2.0.11
  storage: dir
  storage_version: ""
```

How to reproduce:

- clone the code from the PR
- ./run_integration_tests

**Comment by stgraber** [comment]
CRIU will only work as real root with all privileges on the host. It will not work inside containers, at least not anytime soon.

It's possible to maybe abuse a privileged container enough to make it work, but even that seems somewhat unlikely.

Frankly given CRIU's still pretty experimental status, I'd recommend you not have your testsuite require it. It's fine to have an extra target for the testsuite to test it though, as we do in LXD itself.

Closing this issue as it's really more about CRIU's current shortcomings than about LXD :)
