### ISSUE TITLE
container failed to start - transaction within a transaction

### ISSUE THREAD

**Issue by raharper** [lxc/lxd#504]
2015-04-13 19:38:55.365 26488 INFO nclxd.nova.virt.lxd.container [-] [instance: a9f2da66-43ef-462f-a4ce-de085fd4fe50] Spawning new instance
2015-04-13 19:38:55.510 26488 ERROR nclxd.nova.virt.lxd.container [-] Failed to setup container a9f2da66-43ef-462f-a4ce-de085fd4fe50. LXD response {u'type': u'error', u'error_code': 500, u'error': u'cannot start a transaction within a transaction'}
2015-04-13 19:38:55.510 26488 ERROR nclxd.nova.virt.lxd.container [-] Failed to setup container for: a9f2da66-43ef-462f-a4ce-de085fd4fe50
2015-04-13 19:38:55.510 26488 TRACE nclxd.nova.virt.lxd.container Traceback (most recent call last):
2015-04-13 19:38:55.510 26488 TRACE nclxd.nova.virt.lxd.container   File "/usr/lib/python2.7/dist-packages/nclxd/nova/virt/lxd/container.py", line 93, in container_start
2015-04-13 19:38:55.510 26488 TRACE nclxd.nova.virt.lxd.container     self.setup_container(instance)
2015-04-13 19:38:55.510 26488 TRACE nclxd.nova.virt.lxd.container   File "/usr/lib/python2.7/dist-packages/nclxd/nova/virt/lxd/container.py", line 156, in setup_container
2015-04-13 19:38:55.510 26488 TRACE nclxd.nova.virt.lxd.container     'response': resp})
2015-04-13 19:38:55.510 26488 TRACE nclxd.nova.virt.lxd.container   File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 85, in __exit__
2015-04-13 19:38:55.510 26488 TRACE nclxd.nova.virt.lxd.container     six.reraise(self.type_, self.value, self.tb)
2015-04-13 19:38:55.510 26488 TRACE nclxd.nova.virt.lxd.container   File "/usr/lib/python2.7/dist-packages/nclxd/nova/virt/lxd/container.py", line 151, in setup_container
2015-04-13 19:38:55.510 26488 TRACE nclxd.nova.virt.lxd.container     raise exception.NovaException
2015-04-13 19:38:55.510 26488 TRACE nclxd.nova.virt.lxd.container NovaException: An unknown exception occurred.
2015-04-13 19:38:55.510 26488 TRACE nclxd.nova.virt.lxd.container

**Comment by hallyn** [comment]
Thanks - this *should* be fixed by https://github.com/lxc/lxd/pull/503 .  Please re-open if you see this again.
