### ISSUE TITLE
Proxy device cannot reconnect to GPG socket after container was stopped

### ISSUE THREAD

**Issue by quater** [lxc/lxd#5054]
# Issue description

GPG2 cannot access the proxied GPG2 socket anymore after the container was stopped and started.

# Steps to reproduce

Pre-requisites
* GPG2 installed on LXD host machine
* Public and private GPG key loaded into GPG2 on the LXD host machine
* Determine the location of your GPG socket by running `gpgconf --list-dirs`. Adjust below script if it differs.

Below Bash script creates the LXD image with GPG2 installed and the public GPG key imported (adjust PATH_TO_PUBLIC_GPG_KEY variable accordingly). Note, it also enables linger for login control.

It then creates the `c123456-gpg2` container and adds the proxy device.

```BASH
#!/bin/bash

PATH_TO_PUBLIC_GPG_KEY=john.doe@example.org.asc
CONTAINER_NAME=c123456
IMAGE_ALIAS=i123456-gpg2

lxc launch ubuntu:18.04 $CONTAINER_NAME
sleep 5
lxc exec $CONTAINER_NAME -- sudo --user ubuntu /bin/bash -c "sudo loginctl enable-linger ubuntu"
lxc exec $CONTAINER_NAME -- sudo --user ubuntu /bin/bash -c "sudo apt update && sudo apt install gnupg2 -y"
lxc exec $CONTAINER_NAME -- sudo --user ubuntu /bin/bash -c "mkdir /home/ubuntu/.gnupg && chmod 0700 /home/ubuntu/.gnupg/"
lxc file push $PATH_TO_PUBLIC_GPG_KEY $CONTAINER_NAME/home/ubuntu/.gnupg/public_key.asc
lxc exec $CONTAINER_NAME -- sudo --user ubuntu --set-home /bin/bash -c "gpg2 --import /home/ubuntu/.gnupg/public_key.asc"
lxc stop $CONTAINER_NAME
lxc publish $CONTAINER_NAME --alias $IMAGE_ALIAS
lxc rm $CONTAINER_NAME

sleep 3
lxc launch i123456-gpg2 c123456-gpg2
sleep 5
lxc config device add c123456-gpg2 gpg-agent proxy \
connect=unix:///run/user/1000/gnupg/S.gpg-agent.extra \
listen=unix:///run/user/1000/gnupg/S.gpg-agent \
bind=container \
uid=1000 \
gid=1000 \
mode=0600 \
security.uid=0 \
security.gid=1000
```

## Manual steps from here on...
IMPORTANT: Make sure you replace `john.doe@example.org` with your GPG key name!!

```BASH
$ lxc exec c123456-gpg2 -- sudo --user ubuntu --login
ubuntu@c123456-gpg2:~$ echo 'Here is some cool text' | gpg2 -ear john.doe@example.org --trust-model always | gpg2 -d
gpg: encrypted with 4096-bit RSA key, ID 1111111111111111, created 2018-09-09
      "John Doe <john.doe@example.org>"
Here is some cool text
```
==>> All working fine up to this point

```BASH
ubuntu@c123456-gpg2:~$ logout
$ lxc exec c123456-gpg2 -- sudo --user ubuntu --login
ubuntu@c123456-gpg2:~$ echo 'Here is some cool text' | gpg2 -ear john.doe@example.org --trust-model always | gpg2 -d
gpg: encrypted with 4096-bit RSA key, ID 1111111111111111, created 2018-09-09
      "John Doe <john.doe@example.org>"
Here is some cool text
ubuntu@c123456-gpg2:~$ logout
```

==> Review proxy.gpg-agent.log
```BASH
$ sudo cat /var/snap/lxd/common/lxd/logs/c123456-gpg2/proxy.gpg-agent.log
Disconnected during read: read unix ///run/user/1000/gnupg/S.gpg-agent->@: EOF
Disconnected during read: read unix ///run/user/1000/gnupg/S.gpg-agent->@: EOF
```
==>> Still working due to 'linger' enabled with login control

Stop and start container
```BASH
$ lxc stop c123456-gpg2 && lxc start c123456-gpg2
```

==> Review proxy.gpg-agent.log
```BASH
$ sudo cat /var/snap/lxd/common/lxd/logs/c123456-gpg2/proxy.gpg-agent.log
Error: Failed to listen on ///run/user/1000/gnupg/S.gpg-agent: listen unix ///run/user/1000/gnupg/S.gpg-agent: bind: address already in use
Invalid argument - Failed to receive file descriptor
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5a1078]

goroutine 1 [running]:
os.(*File).Name(...)
  /build/lxd/parts/go/build/src/os/file.go:50
net.FileListener(0x0, 0xc000272d10, 0x0, 0xc0002b8420, 0x1)
  /build/lxd/parts/go/build/src/net/file.go:36 +0x88
main.(*cmdForkproxy).Run(0xc000164278, 0xc0002bea00, 0xc0001903c0, 0xc, 0xc, 0x0, 0x0)
  /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/main_forkproxy.go:583 +0xf47
main.(*cmdForkproxy).Run-fm(0xc0002bea00, 0xc0001903c0, 0xc, 0xc, 0x0, 0x0)
  /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/main_forkproxy.go:321 +0x52
github.com/spf13/cobra.(*Command).execute(0xc0002bea00, 0xc000190300, 0xc, 0xc, 0xc0002bea00, 0xc000190300)
  /build/lxd/parts/lxd/go/src/github.com/spf13/cobra/command.go:762 +0x473
github.com/spf13/cobra.(*Command).ExecuteC(0xc000275b80, 0x1144220, 0x0, 0xc0002c0500)
  /build/lxd/parts/lxd/go/src/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0xc000275b80, 0xc0002a3ec8, 0x1)
  /build/lxd/parts/lxd/go/src/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
  /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/main.go:164 +0xe13
```

# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info":
```
$ lxc info
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFcTCCA1mgAwIBAgIRANVtOarPMU7+Xrmw7UCB1HgwDQYJKoZIhvcNAQELBQAw
    truncated
    1DzWbFuwJjtt/JKegcDpcNJUcat3uuRMxQg2S7oB7yM9sZLXkFfLvJZBFeYQ9eXb
    +iSRYoI=
    -----END CERTIFICATE-----
  certificate_fingerprint: 44bca71truncated366b
  driver: lxc
  driver_version: 3.0.2
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-34-generic
  server: lxd
  server_pid: 4374
  server_version: "3.5"
  storage: zfs
  storage_version: 0.7.5-1ubuntu16.3
  server_clustered: false
  server_name: mymachinename
```

**Comment by stgraber** [comment]
That's expected. You're mounting it on top of /run in the container, but most container init systems are going to mount a tmpfs on /run during boot time, effectively hiding that mount.

Try mounting it somewhere else which isn't a tmpfs and isn't wiped at boot (as /run and /tmp) are.

**Comment by quater** [comment]
Based on your suggestion, I have moved it to the user's home directory. With that in place it worked perfectly. In the light of this, I will close this.
