### ISSUE TITLE
Crash when having multiple ip addresses

### ISSUE THREAD

**Issue by peter-held** [lxc/lxd#5076]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
# lxc info
config:
  images.auto_update_interval: "0"
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  driver: lxc
  driver_version: 3.0.2
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-34-generic
  server: lxd
  server_pid: 7567
  server_version: "3.5"
  storage: zfs
  storage_version: 0.7.5-1ubuntu16.3
  server_clustered: false
  server_name: c2.test.dom

# Issue description

lxc info doesn't show the ip address for containers with multiple ip addresses.
All lxc containers have ip addresses in own /etc/network/interfaces. No dhcp is used.
Also when running lxc list the following crash is logged:
Sep 27 07:22:22 c2.test.dom lxd.daemon[6145]: container=mail1 lvl=eror msg="Error calling 'lxd forkgetnet" output="panic: runtime error: invalid memory address or nil pointer dereference\n[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x786336]\n\ngoroutine 1 [running]:\ngithub.com/lxc/lxd/shared.NetnsGetifaddrs(0xffffffff, 0x0, 0x0, 0x0)\n\t/build/lxd/parts/lxd/go/src/github.com/lxc/lxd/shared/network_linux.go:68 +0x226\nmain.(*cmdForknet).RunInfo(0xc00000e708, 0xc000299900, 0xc000292450, 0x1, 0x1, 0x0, 0x0)\n\t/build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/main_forknet.go:96 +0x2d\nmain.(*cmdForknet).RunInfo-fm(0xc000299900, 0xc000292450, 0x1, 0x1, 0x0, 0x0)\n\t/build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/main_forknet.go:89 +0x52\ngithub.com/spf13/cobra.(*Command).execute(0xc000299900, 0xc000292410, 0x1, 0x1, 0xc000299900, 0xc000292410)\n\t/build/lxd/parts/lxd/go/src/github.com/spf13/cobra/command.go:762 +0x473\ngithub.com/spf13/cobra.(*Command).ExecuteC(0xc000286f00, 0x114b906, 0x0, 0xc00029b680)\n\t/build/lxd/parts/lxd/go/src/github.com/spf13/cobra/command.go:852 +0x2fd\ngithub.com/spf13/cobra.(*Command).Execute(0xc000286f00, 0xc00027dec8, 0x1)\n\t/build/lxd/parts/lxd/go/src/github.com/spf13/cobra/command.go:800 +0x2b\nmain.main()\n\t/build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/main.go:164 +0xe13\n" pid=10553 t=2018-09-27T07:22:22+0000

# Steps to reproduce

 1. Step one
 2. Step two
 3. Step three

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
Can you show `ifconfig -a` from inside the container, that should be enough for me to reproduce the issue

**Comment by peter-held** [comment]
Sure:

eth0      Link encap:Ethernet  HWaddr 00:11:22:33:44:55  
          inet addr:11.22.33.44  Bcast:11.22.33.223  Mask:255.255.255.224
          inet6 addr: 1111::222:3333:4444:5555/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:45731 errors:0 dropped:0 overruns:0 frame:0
          TX packets:36749 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:23500070 (23.5 MB)  TX bytes:22847445 (22.8 MB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

vpn       Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          inet addr:10.10.10.10  P-t-P:10.10.10.10  Mask:255.255.255.0
          inet6 addr: 2222::333:4444:5555:6666/64 Scope:Link
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1
          RX packets:34659 errors:0 dropped:0 overruns:0 frame:0
          TX packets:34651 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:500 
          RX bytes:39580792 (39.5 MB)  TX bytes:39144367 (39.1 MB)

Thank you.

**Comment by stgraber** [comment]
Looks like the tunnel devices are the problem somehow, looking into it.

**Comment by stgraber** [comment]
@brauner FYI

**Comment by peter-held** [comment]
The vpn interface is configured like this:

auto vpn
iface vpn inet static
    address 10.10.10.10
    netmask 24
    pre-up ip tuntap add dev vpn mode tun pi
    post-down ip tuntap del dev vpn mode tun

I'm using it with tinc:
https://www.tinc-vpn.org/

**Comment by stgraber** [comment]
Perfect, that does trigger the issue here

**Comment by stgraber** [comment]
Sent a fix

**Comment by peter-held** [comment]
The fix will enter in the next release ?
I am using snap.

**Comment by stgraber** [comment]
we'll update the snap once the fix is merged, so should hopefully be fixed later today

**Comment by peter-held** [comment]
Thank you.

**Comment by sladkani** [comment]
Hi @stgraber 
Will this get into 3.0/stable channel?
We're using the 3.0.2 lxd snap and hitting this issue in our systems.
Thanks.

**Comment by stgraber** [comment]
Pushed the fix to the candidate channel now, assuming all tests pass, it should be available in the next couple of days.
