### ISSUE TITLE
Bug: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by turtle0x1** [lxc/lxd#5388]
I managed to cause an `invalid memory address or nil pointer dereference` when playing around with projects param on requests, syslog shows me;

```
Dec 30 16:21:21 pc-name lxd.daemon[2785]: 2018/12/30 16:21:21 http: TLS handshake error from 192.168.1.5:55210: read tcp 192.168.1.5:8443->192.168.1.5:55210: read: connection reset by peer
Dec 30 16:21:30 pc-name lxd.daemon[2785]: 2018/12/30 16:21:30 http: TLS handshake error from 192.168.1.5:60964: tls: client offered an unsupported, maximum protocol version of 300
Dec 30 16:22:56 pc-name lxd.daemon[2785]: 2018/12/30 16:22:56 http: TLS handshake error from 192.168.1.5:35258: tls: no cipher suite supported by both client and server
Dec 30 16:22:59 pc-name lxd.daemon[2785]: 2018/12/30 16:22:59 http: TLS handshake error from 192.168.1.5:36126: tls: no cipher suite supported by both client and server
Dec 30 16:22:59 pc-name lxd.daemon[2785]: 2018/12/30 16:22:59 http: TLS handshake error from 192.168.1.5:36148: tls: unsupported SSLv2 handshake received
Dec 30 16:25:26 pc-name lxd.daemon[2785]: 2018/12/30 16:25:26 http: panic serving 127.0.0.1:47974: runtime error: invalid memory address or nil pointer dereference
Dec 30 16:25:26 pc-name lxd.daemon[2785]: goroutine 5558 [running]:
Dec 30 16:25:26 pc-name lxd.daemon[2785]: net/http.(*conn).serve.func1(0xc0003bb7c0)
Dec 30 16:25:26 pc-name lxd.daemon[2785]: #011/build/lxd/parts/go/build/src/net/http/server.go:1746 +0xd0
Dec 30 16:25:26 pc-name lxd.daemon[2785]: panic(0x1078260, 0x1ce8020)
Dec 30 16:25:26 pc-name lxd.daemon[2785]: #011/build/lxd/parts/go/build/src/runtime/panic.go:513 +0x1b9
Dec 30 16:25:26 pc-name lxd.daemon[2785]: github.com/lxc/lxd/lxd/db/query.SelectURIs(0xc00013a6c0, 0x0, 0xc0012fd668, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
Dec 30 16:25:26 pc-name lxd.daemon[2785]: #011/build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/db/query/slices.go:44 +0x2d5
Dec 30 16:25:26 pc-name lxd.daemon[2785]: github.com/lxc/lxd/lxd/db.(*ClusterTx).ProjectURIs(0xc000592420, 0x0, 0x0, 0xc0000380a8, 0x0, 0xc0012fd801, 0xc000043580, 0x0)
Dec 30 16:25:26 pc-name lxd.daemon[2785]: #011/build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/db/projects.mapper.go:110 +0x1ef
Dec 30 16:25:26 pc-name lxd.daemon[2785]: main.apiProjectsGet.func1(0xc000592420, 0x0, 0x0)
Dec 30 16:25:26 pc-name lxd.daemon[2785]: #011/build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/api_project.go:47 +0x12f
Dec 30 16:25:26 pc-name lxd.daemon[2785]: github.com/lxc/lxd/lxd/db.(*Cluster).transaction.func1.1(0xc000043580, 0xc000043580, 0x0)
Dec 30 16:25:26 pc-name lxd.daemon[2785]: #011/build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/db/db.go:338 +0x41
Dec 30 16:25:26 pc-name lxd.daemon[2785]: github.com/lxc/lxd/lxd/db/query.Transaction(0xc000208900, 0xc0012fd920, 0x4184f8, 0x18)
Dec 30 16:25:26 pc-name lxd.daemon[2785]: #011/build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/db/query/transaction.go:17 +0x5a
Dec 30 16:25:26 pc-name lxd.daemon[2785]: github.com/lxc/lxd/lxd/db.(*Cluster).transaction.func1(0x7f78d699b000, 0x0)
Dec 30 16:25:26 pc-name lxd.daemon[2785]: #011/build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/db/db.go:336 +0x66
Dec 30 16:25:26 pc-name lxd.daemon[2785]: github.com/lxc/lxd/lxd/db/query.Retry(0xc0012fd9d0, 0xc000592420, 0x436e52)
Dec 30 16:25:26 pc-name lxd.daemon[2785]: #011/build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/db/query/retry.go:20 +0xad
Dec 30 16:25:26 pc-name lxd.daemon[2785]: github.com/lxc/lxd/lxd/db.(*Cluster).transaction(0xc000573bf0, 0xc0012fda78, 0xc000573c00, 0x1371660)
Dec 30 16:25:26 pc-name lxd.daemon[2785]: #011/build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/db/db.go:335 +0x8f
Dec 30 16:25:26 pc-name lxd.daemon[2785]: github.com/lxc/lxd/lxd/db.(*Cluster).Transaction(0xc000573bf0, 0xc0012fda78, 0x0, 0x0)
Dec 30 16:25:26 pc-name lxd.daemon[2785]: #011/build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/db/db.go:298 +0x80
Dec 30 16:25:26 pc-name lxd.daemon[2785]: main.apiProjectsGet(0xc000234a20, 0xc001e34900, 0x11a2f10, 0x3)
Dec 30 16:25:26 pc-name lxd.daemon[2785]: #011/build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/api_project.go:41 +0x89
Dec 30 16:25:26 pc-name lxd.daemon[2785]: main.(*Daemon).createCmd.func1(0x137be20, 0xc0009bc460, 0xc001e34900)
Dec 30 16:25:26 pc-name lxd.daemon[2785]: #011/build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/daemon.go:327 +0x762
Dec 30 16:25:26 pc-name lxd.daemon[2785]: net/http.HandlerFunc.ServeHTTP(0xc00027c8c0, 0x137be20, 0xc0009bc460, 0xc001e34900)
Dec 30 16:25:26 pc-name lxd.daemon[2785]: #011/build/lxd/parts/go/build/src/net/http/server.go:1964 +0x44
Dec 30 16:25:26 pc-name lxd.daemon[2785]: github.com/gorilla/mux.(*Router).ServeHTTP(0xc0002080c0, 0x137be20, 0xc0009bc460, 0xc000138400)
Dec 30 16:25:26 pc-name lxd.daemon[2785]: #011/build/lxd/parts/lxd/go/src/github.com/gorilla/mux/mux.go:212 +0xd0
Dec 30 16:25:26 pc-name lxd.daemon[2785]: main.(*lxdHttpServer).ServeHTTP(0xc000315570, 0x137be20, 0xc0009bc460, 0xc000138400)
Dec 30 16:25:26 pc-name lxd.daemon[2785]: #011/build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/api.go:79 +0x96
Dec 30 16:25:26 pc-name lxd.daemon[2785]: net/http.serverHandler.ServeHTTP(0xc0002f20d0, 0x137be20, 0xc0009bc460, 0xc000138400)
Dec 30 16:25:26 pc-name lxd.daemon[2785]: #011/build/lxd/parts/go/build/src/net/http/server.go:2741 +0xab
Dec 30 16:25:26 pc-name lxd.daemon[2785]: net/http.(*conn).serve(0xc0003bb7c0, 0x137ef60, 0xc0009b0d40)
Dec 30 16:25:26 pc-name lxd.daemon[2785]: #011/build/lxd/parts/go/build/src/net/http/server.go:1847 +0x646
Dec 30 16:25:26 pc-name lxd.daemon[2785]: created by net/http.(*Server).Serve
Dec 30 16:25:26 pc-name lxd.daemon[2785]: #011/build/lxd/parts/go/build/src/net/http/server.go:2851 +0x2f5
```
If I try to run `sudo lxd.lxc list --debug` I get

```
DBUG[12-30|16:32:36] Connecting to a local LXD over a Unix socket 
DBUG[12-30|16:32:36] Sending request to LXD                   method=GET url=http://unix.socket/1.0 etag=
```

Which just hangs and then I try `sudo snap restart lxd` which shows;
```
restart of [lxd.activate lxd.daemon]                                                                                                                                                                              |error: cannot perform the following tasks:
- restart of [lxd.activate lxd.daemon] (# systemctl restart snap.lxd.activate.service snap.lxd.daemon.service

<exceeded maximum runtime of 1m1s>)
- restart of [lxd.activate lxd.daemon] (exceeded maximum runtime of 1m1s)
```

 Ill see if I can replicate the conditions again soon but Im 99% sure it because I was playing around with attaching `project` param (it may have even been attaching a `project` param while calling `/1.0/projects`

Edit: 
To cause the lxd server to crash you just have to call `/projects/?project=test` which is not something I should be sending but causes the server to crash regardless!

**Comment by stgraber** [comment]
```
DBUG[01-07|17:00:05] handling                                 url="/1.0/projects?project=test" ip=@ method=GET
2019/01/07 17:00:05 http: panic serving @: runtime error: invalid memory address or nil pointer dereference
goroutine 2514 [running]:
net/http.(*conn).serve.func1(0xc42048a500)
	/usr/lib/go-1.10/src/net/http/server.go:1726 +0xd0
panic(0xfe4b20, 0x16fdfc0)
	/usr/lib/go-1.10/src/runtime/panic.go:502 +0x229
github.com/lxc/lxd/lxd/db/query.SelectURIs(0xc42050a1b0, 0x0, 0xc42205b678, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/stgraber/data/code/go/src/github.com/lxc/lxd/lxd/db/query/slices.go:44 +0x2da
github.com/lxc/lxd/lxd/db.(*ClusterTx).ProjectURIs(0xc4204ab300, 0x0, 0x0, 0xc4200b2030, 0x0, 0x1, 0xc420f7ef80, 0x0)
	/home/stgraber/data/code/go/src/github.com/lxc/lxd/lxd/db/projects.mapper.go:110 +0x1f3
main.apiProjectsGet.func1(0xc4204ab300, 0x0, 0x0)
	/home/stgraber/data/code/go/src/github.com/lxc/lxd/lxd/api_project.go:47 +0x11d
github.com/lxc/lxd/lxd/db.(*Cluster).transaction.func1.1(0xc420f7ef80, 0xc420f7ef80, 0x0)
	/home/stgraber/data/code/go/src/github.com/lxc/lxd/lxd/db/db.go:343 +0x42
github.com/lxc/lxd/lxd/db/query.Transaction(0xc4202fc140, 0xc42205b930, 0x41d108, 0x18)
	/home/stgraber/data/code/go/src/github.com/lxc/lxd/lxd/db/query/transaction.go:17 +0x5a
github.com/lxc/lxd/lxd/db.(*Cluster).transaction.func1(0x7fa4837f7458, 0x0)
	/home/stgraber/data/code/go/src/github.com/lxc/lxd/lxd/db/db.go:341 +0x55
github.com/lxc/lxd/lxd/db/query.Retry(0xc42205b9e0, 0xc4204ab300, 0x435de9)
	/home/stgraber/data/code/go/src/github.com/lxc/lxd/lxd/db/query/retry.go:20 +0xae
github.com/lxc/lxd/lxd/db.(*Cluster).transaction(0xc4202bdd70, 0xc42205ba88, 0xc4202bdd80, 0x12472e0)
	/home/stgraber/data/code/go/src/github.com/lxc/lxd/lxd/db/db.go:340 +0x87
github.com/lxc/lxd/lxd/db.(*Cluster).Transaction(0xc4202bdd70, 0xc42205ba88, 0x0, 0x0)
	/home/stgraber/data/code/go/src/github.com/lxc/lxd/lxd/db/db.go:303 +0x80
main.apiProjectsGet(0xc42024cea0, 0xc4202a7d00, 0x1113424, 0x3)
	/home/stgraber/data/code/go/src/github.com/lxc/lxd/lxd/api_project.go:41 +0x72
main.(*Daemon).createCmd.func1(0x1250860, 0xc42062c460, 0xc4202a7d00)
	/home/stgraber/data/code/go/src/github.com/lxc/lxd/lxd/daemon.go:327 +0x793
net/http.HandlerFunc.ServeHTTP(0xc42040e8c0, 0x1250860, 0xc42062c460, 0xc4202a7d00)
	/usr/lib/go-1.10/src/net/http/server.go:1947 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc42022cf50, 0x1250860, 0xc42062c460, 0xc4202a7d00)
	/home/stgraber/data/code/go/src/github.com/gorilla/mux/mux.go:162 +0xed
main.(*lxdHttpServer).ServeHTTP(0xc420424f80, 0x1250860, 0xc42062c460, 0xc420174700)
	/home/stgraber/data/code/go/src/github.com/lxc/lxd/lxd/api.go:79 +0xa4
net/http.serverHandler.ServeHTTP(0xc4200a9520, 0x1250860, 0xc42062c460, 0xc420174700)
	/usr/lib/go-1.10/src/net/http/server.go:2697 +0xbc
net/http.(*conn).serve(0xc42048a500, 0x12535a0, 0xc420321e40)
	/usr/lib/go-1.10/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/lib/go-1.10/src/net/http/server.go:2798 +0x27b
```

Will look into the cause soon.
