### ISSUE TITLE
Unable to access containers after disk full

### ISSUE THREAD

**Issue by smilekat** [lxc/lxd#5469]
# Required information

 * Distribution: ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-133-generic
   * LXC version: 3.0.1
   * LXD version: 3.0.1
   * Storage backend in use: zfs

# Issue description

"no space left on device" error occurred while copying container image using "lxc publish" command. After that lxc is not working anymore.

After the error occurred, I deleted some old container images for free disk space. I rebooted the server again but could not recover it. Could you give some advice how to recover.

```
root@server:~$ lxc list
Error: Get http://unix.socket/1.0: EOF
```

```
root@server:/# dpkg -l | grep lxd
ii  lxd  3.0.1-0ubuntu1~16.04.4  amd64  Container hypervisor based on LXC - daemon
ii  lxd-client  3.0.1-0ubuntu1~16.04.4  amd64 Container hypervisor based on LXC - client
```

```
root@server:/# lxd --group lxd --verbose --debug
lvl=dbug msg="Connecting to a local LXD over a Unix socket" t=2019-01-31T07:42:10+0100
etag= lvl=dbug method=GET msg="Sending request to LXD" t=2019-01-31T07:42:10+0100 url=http://unix.socket/1.0
lvl=info msg="LXD 3.0.1 is starting in normal mode" path=/var/lib/lxd t=2019-01-31T07:51:56+0100
lvl=info msg="Kernel uid/gid map:" t=2019-01-31T07:51:56+0100
lvl=info msg=" - u 0 0 4294967295" t=2019-01-31T07:51:56+0100
lvl=info msg=" - g 0 0 4294967295" t=2019-01-31T07:51:56+0100
lvl=info msg="Configured LXD uid/gid map:" t=2019-01-31T07:51:56+0100
lvl=info msg=" - u 0 165536 65536" t=2019-01-31T07:51:56+0100
lvl=info msg=" - g 0 165536 65536" t=2019-01-31T07:51:56+0100
lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." t=2019-01-31T07:51:56+0100
lvl=info msg="Initializing local database" t=2019-01-31T07:51:56+0100
lvl=info msg="Initializing database gateway" t=2019-01-31T07:51:56+0100
address= id=1 lvl=info msg="Start database node" t=2019-01-31T07:51:56+0100
lvl=info msg="Raft: Restored from snapshot 1-13090-1516601829209" t=2019-01-31T07:51:56+0100
lvl=info msg="Raft: Initial configuration (index=1): [{Suffrage:Voter ID:1 Address:0}]" t=2019-01-31T07:51:56+0100
lvl=info msg="Raft: Node at 0 [Leader] entering Leader state" t=2019-01-31T07:51:56+0100
lvl=info msg="LXD isn't socket activated" t=2019-01-31T07:51:56+0100
lvl=dbug msg="Connecting to a local LXD over a Unix socket" t=2019-01-31T07:51:56+0100
etag= lvl=dbug method=GET msg="Sending request to LXD" t=2019-01-31T07:51:56+0100 url=http://unix.socket/1.0
panic: txn not found

trace:
2019-01-31 07:51:56.42910: fsm: restore=13090 start
2019-01-31 07:51:56.42911: fsm: restore=13090 database size: 4096
2019-01-31 07:51:56.42911: fsm: restore=13090 wal size: 313152
2019-01-31 07:51:56.42929: fsm: restore=13090 filename: db.bin
2019-01-31 07:51:56.42930: fsm: restore=13090 transaction ID: 
2019-01-31 07:51:56.42992: fsm: restore=13090 open follower: db.bin
2019-01-31 07:51:56.43097: fsm: restore=13090 done
2019-01-31 07:51:56.43437: fsm: term=1 index=13091 cmd=frames txn=13090 pages=3 commit=1 start
2019-01-31 07:51:56.43501: fsm: term=1 index=13091 cmd=frames txn=13090 pages=3 commit=1 unregister txn
2019-01-31 07:51:56.43501: fsm: term=1 index=13091 cmd=frames txn=13090 pages=3 commit=1 done
2019-01-31 07:51:56.43530: fsm: term=1 index=13092 cmd=frames txn=13091 pages=6 commit=1 start
2019-01-31 07:51:56.43585: fsm: term=1 index=13092 cmd=frames txn=13091 pages=6 commit=1 unregister txn
2019-01-31 07:51:56.43585: fsm: term=1 index=13092 cmd=frames txn=13091 pages=6 commit=1 done
2019-01-31 07:51:56.43587: fsm: term=1 index=13093 cmd=frames txn=13092 pages=2 commit=1 start
2019-01-31 07:51:56.43604: fsm: term=1 index=13093 cmd=frames txn=13092 pages=2 commit=1 unregister txn
2019-01-31 07:51:56.43604: fsm: term=1 index=13093 cmd=frames txn=13092 pages=2 commit=1 done
2019-01-31 07:51:56.43605: fsm: term=1 index=13094 cmd=frames txn=13093 pages=2 commit=1 start
2019-01-31 07:51:56.43620: fsm: term=1 index=13094 cmd=frames txn=13093 pages=2 commit=1 unregister txn
2019-01-31 07:51:56.43620: fsm: term=1 index=13094 cmd=frames txn=13093 pages=2 commit=1 done
2019-01-31 07:51:56.43622: fsm: term=1 index=13095 cmd=frames txn=13094 pages=3 commit=1 start
2019-01-31 07:51:56.43638: fsm: term=1 index=13095 cmd=frames txn=13094 pages=3 commit=1 unregister txn
2019-01-31 07:51:56.43639: fsm: term=1 index=13095 cmd=frames txn=13094 pages=3 commit=1 done
2019-01-31 07:51:56.43641: fsm: term=1 index=13096 cmd=frames txn=13095 pages=11 commit=1 start
2019-01-31 07:51:56.43669: fsm: term=1 index=13096 cmd=frames txn=13095 pages=11 commit=1 unregister txn
2019-01-31 07:51:56.43669: fsm: term=1 index=13096 cmd=frames txn=13095 pages=11 commit=1 done
2019-01-31 07:51:56.43670: fsm: term=1 index=13097 cmd=frames txn=13096 pages=2 commit=1 start
2019-01-31 07:51:56.43686: fsm: term=1 index=13097 cmd=frames txn=13096 pages=2 commit=1 unregister txn
2019-01-31 07:51:56.43686: fsm: term=1 index=13097 cmd=frames txn=13096 pages=2 commit=1 done
2019-01-31 07:51:56.43687: fsm: term=1 index=13098 cmd=frames txn=13097 pages=2 commit=1 start
2019-01-31 07:51:56.43701: fsm: term=1 index=13098 cmd=frames txn=13097 pages=2 commit=1 unregister txn
2019-01-31 07:51:56.43701: fsm: term=1 index=13098 cmd=frames txn=13097 pages=2 commit=1 done
2019-01-31 07:51:56.43702: fsm: term=1 index=13099 cmd=checkpoint file=db.bin start
2019-01-31 07:51:56.43789: fsm: term=1 index=13099 cmd=checkpoint file=db.bin done
2019-01-31 07:51:56.43791: fsm: term=1 index=13100 cmd=frames txn=13099 pages=2 commit=1 start
2019-01-31 07:51:56.43827: fsm: term=1 index=13100 cmd=frames txn=13099 pages=2 commit=1 unregister txn
2019-01-31 07:51:56.43827: fsm: term=1 index=13100 cmd=frames txn=13099 pages=2 commit=1 done
2019-01-31 07:51:56.43828: fsm: term=1 index=13101 cmd=frames txn=13100 pages=2 commit=1 start
2019-01-31 07:51:56.43848: fsm: term=1 index=13101 cmd=frames txn=13100 pages=2 commit=1 unregister txn
2019-01-31 07:51:56.43848: fsm: term=1 index=13101 cmd=frames txn=13100 pages=2 commit=1 done
2019-01-31 07:51:56.43849: fsm: term=1 index=13102 cmd=frames txn=13101 pages=3 commit=1 start
2019-01-31 07:51:56.43870: fsm: term=1 index=13102 cmd=frames txn=13101 pages=3 commit=1 unregister txn
2019-01-31 07:51:56.43870: fsm: term=1 index=13102 cmd=frames txn=13101 pages=3 commit=1 done
2019-01-31 07:51:56.43871: fsm: term=1 index=13103 cmd=frames txn=13102 pages=2 commit=1 start
2019-01-31 07:51:56.43891: fsm: term=1 index=13103 cmd=frames txn=13102 pages=2 commit=1 unregister txn
2019-01-31 07:51:56.43891: fsm: term=1 index=13103 cmd=frames txn=13102 pages=2 commit=1 done
2019-01-31 07:51:56.43892: fsm: term=1 index=13104 cmd=frames txn=13103 pages=3 commit=1 start
2019-01-31 07:51:56.43913: fsm: term=1 index=13104 cmd=frames txn=13103 pages=3 commit=1 unregister txn
2019-01-31 07:51:56.43913: fsm: term=1 index=13104 cmd=frames txn=13103 pages=3 commit=1 done
2019-01-31 07:51:56.43914: fsm: term=1 index=13105 cmd=frames txn=13104 pages=2 commit=1 start
2019-01-31 07:51:56.43933: fsm: term=1 index=13105 cmd=frames txn=13104 pages=2 commit=1 unregister txn
2019-01-31 07:51:56.43933: fsm: term=1 index=13105 cmd=frames txn=13104 pages=2 commit=1 done
2019-01-31 07:51:56.43934: fsm: term=1 index=13106 cmd=frames txn=13105 pages=3 commit=1 start
2019-01-31 07:51:56.43954: fsm: term=1 index=13106 cmd=frames txn=13105 pages=3 commit=1 unregister txn
2019-01-31 07:51:56.43954: fsm: term=1 index=13106 cmd=frames txn=13105 pages=3 commit=1 done
2019-01-31 07:51:56.43955: fsm: term=1 index=13107 cmd=frames txn=13106 pages=2 commit=1 start
2019-01-31 07:51:56.43971: fsm: term=1 index=13107 cmd=frames txn=13106 pages=2 commit=1 unregister txn
2019-01-31 07:51:56.43971: fsm: term=1 index=13107 cmd=frames txn=13106 pages=2 commit=1 done
2019-01-31 07:51:56.43972: fsm: term=1 index=13108 cmd=frames txn=13107 pages=3 commit=1 start
2019-01-31 07:51:56.43987: fsm: term=1 index=13108 cmd=frames txn=13107 pages=3 commit=1 unregister txn
2019-01-31 07:51:56.43987: fsm: term=1 index=13108 cmd=frames txn=13107 pages=3 commit=1 done
2019-01-31 07:51:56.43989: fsm: term=1 index=13109 cmd=frames txn=13108 pages=11 commit=1 start
2019-01-31 07:51:56.44016: fsm: term=1 index=13109 cmd=frames txn=13108 pages=11 commit=1 unregister txn
2019-01-31 07:51:56.44016: fsm: term=1 index=13109 cmd=frames txn=13108 pages=11 commit=1 done
2019-01-31 07:51:56.44018: fsm: term=1 index=13110 cmd=frames txn=13109 pages=3 commit=1 start
2019-01-31 07:51:56.44033: fsm: term=1 index=13110 cmd=frames txn=13109 pages=3 commit=1 unregister txn
2019-01-31 07:51:56.44033: fsm: term=1 index=13110 cmd=frames txn=13109 pages=3 commit=1 done
2019-01-31 07:51:56.44036: fsm: term=1 index=13111 cmd=frames txn=13110 pages=12 commit=1 start
2019-01-31 07:51:56.44062: fsm: term=1 index=13111 cmd=frames txn=13110 pages=12 commit=1 unregister txn
2019-01-31 07:51:56.44062: fsm: term=1 index=13111 cmd=frames txn=13110 pages=12 commit=1 done
2019-01-31 07:51:56.44064: fsm: term=1 index=13112 cmd=frames txn=13111 pages=12 commit=1 start
2019-01-31 07:51:56.44089: fsm: term=1 index=13112 cmd=frames txn=13111 pages=12 commit=1 unregister txn
2019-01-31 07:51:56.44089: fsm: term=1 index=13112 cmd=frames txn=13111 pages=12 commit=1 done
2019-01-31 07:51:56.44090: fsm: term=1 index=13113 cmd=frames txn=13112 pages=2 commit=1 start
2019-01-31 07:51:56.44105: fsm: term=1 index=13113 cmd=frames txn=13112 pages=2 commit=1 unregister txn
2019-01-31 07:51:56.44105: fsm: term=1 index=13113 cmd=frames txn=13112 pages=2 commit=1 done
2019-01-31 07:51:56.44106: fsm: term=1 index=13114 cmd=frames txn=13113 pages=3 commit=1 start
2019-01-31 07:51:56.44126: fsm: term=1 index=13114 cmd=frames txn=13113 pages=3 commit=1 unregister txn
2019-01-31 07:51:56.44126: fsm: term=1 index=13114 cmd=frames txn=13113 pages=3 commit=1 done
2019-01-31 07:51:56.44128: fsm: term=1 index=13115 cmd=frames txn=13114 pages=3 commit=1 start
2019-01-31 07:51:56.44143: fsm: term=1 index=13115 cmd=frames txn=13114 pages=3 commit=1 unregister txn
2019-01-31 07:51:56.44143: fsm: term=1 index=13115 cmd=frames txn=13114 pages=3 commit=1 done
2019-01-31 07:51:56.44145: fsm: term=1 index=13116 cmd=frames txn=13115 pages=11 commit=1 start
2019-01-31 07:51:56.44168: fsm: term=1 index=13116 cmd=frames txn=13115 pages=11 commit=1 unregister txn
2019-01-31 07:51:56.44168: fsm: term=1 index=13116 cmd=frames txn=13115 pages=11 commit=1 done
2019-01-31 07:51:56.44169: fsm: term=1 index=13117 cmd=frames txn=13116 pages=3 commit=1 start
2019-01-31 07:51:56.44184: fsm: term=1 index=13117 cmd=frames txn=13116 pages=3 commit=1 unregister txn
2019-01-31 07:51:56.44184: fsm: term=1 index=13117 cmd=frames txn=13116 pages=3 commit=1 done
2019-01-31 07:51:56.44188: fsm: term=1 index=13118 cmd=frames txn=13117 pages=13 commit=1 start
2019-01-31 07:51:56.44214: fsm: term=1 index=13118 cmd=frames txn=13117 pages=13 commit=1 unregister txn
2019-01-31 07:51:56.44214: fsm: term=1 index=13118 cmd=frames txn=13117 pages=13 commit=1 done
2019-01-31 07:51:56.44218: fsm: term=1 index=13119 cmd=frames txn=13118 pages=10 commit=1 start
2019-01-31 07:51:56.44279: fsm: term=1 index=13119 cmd=frames txn=13118 pages=10 commit=1 unregister txn
2019-01-31 07:51:56.44279: fsm: term=1 index=13119 cmd=frames txn=13118 pages=10 commit=1 done
2019-01-31 07:51:56.44283: fsm: term=1 index=13120 cmd=frames txn=13119 pages=2 commit=1 start
2019-01-31 07:51:56.44308: fsm: term=1 index=13120 cmd=frames txn=13119 pages=2 commit=1 unregister txn
2019-01-31 07:51:56.44308: fsm: term=1 index=13120 cmd=frames txn=13119 pages=2 commit=1 done
2019-01-31 07:51:56.44310: fsm: term=1 index=13121 cmd=frames txn=13120 pages=2 commit=1 start
2019-01-31 07:51:56.44328: fsm: term=1 index=13121 cmd=frames txn=13120 pages=2 commit=1 unregister txn
2019-01-31 07:51:56.44328: fsm: term=1 index=13121 cmd=frames txn=13120 pages=2 commit=1 done
2019-01-31 07:51:56.44330: fsm: term=1 index=13122 cmd=frames txn=13121 pages=3 commit=1 start
2019-01-31 07:51:56.44347: fsm: term=1 index=13122 cmd=frames txn=13121 pages=3 commit=1 unregister txn
2019-01-31 07:51:56.44347: fsm: term=1 index=13122 cmd=frames txn=13121 pages=3 commit=1 done
2019-01-31 07:51:56.44349: fsm: term=1 index=13123 cmd=frames txn=13122 pages=7 commit=1 start
2019-01-31 07:51:56.44367: fsm: term=1 index=13123 cmd=frames txn=13122 pages=7 commit=1 unregister txn
2019-01-31 07:51:56.44367: fsm: term=1 index=13123 cmd=frames txn=13122 pages=7 commit=1 done
2019-01-31 07:51:56.44369: fsm: term=1 index=13124 cmd=frames txn=13123 pages=3 commit=1 start
2019-01-31 07:51:56.44384: fsm: term=1 index=13124 cmd=frames txn=13123 pages=3 commit=1 unregister txn
2019-01-31 07:51:56.44384: fsm: term=1 index=13124 cmd=frames txn=13123 pages=3 commit=1 done
2019-01-31 07:51:56.44385: fsm: term=1 index=13125 cmd=frames txn=13124 pages=6 commit=1 start
2019-01-31 07:51:56.44409: fsm: term=1 index=13125 cmd=frames txn=13124 pages=6 commit=1 unregister txn
2019-01-31 07:51:56.44409: fsm: term=1 index=13125 cmd=frames txn=13124 pages=6 commit=1 done
2019-01-31 07:51:56.44411: fsm: term=1 index=13126 cmd=frames txn=13125 pages=6 commit=1 start
2019-01-31 07:51:56.44429: fsm: term=1 index=13126 cmd=frames txn=13125 pages=6 commit=1 unregister txn
2019-01-31 07:51:56.44429: fsm: term=1 index=13126 cmd=frames txn=13125 pages=6 commit=1 done
2019-01-31 07:51:56.44430: fsm: term=1 index=13127 cmd=frames txn=13126 pages=2 commit=1 start
2019-01-31 07:51:56.44444: fsm: term=1 index=13127 cmd=frames txn=13126 pages=2 commit=1 unregister txn
2019-01-31 07:51:56.44444: fsm: term=1 index=13127 cmd=frames txn=13126 pages=2 commit=1 done
2019-01-31 07:51:56.44446: fsm: term=1 index=13128 cmd=frames txn=13127 pages=3 commit=1 start
2019-01-31 07:51:56.44461: fsm: term=1 index=13128 cmd=frames txn=13127 pages=3 commit=1 unregister txn
2019-01-31 07:51:56.44461: fsm: term=1 index=13128 cmd=frames txn=13127 pages=3 commit=1 done
2019-01-31 07:51:56.44463: fsm: term=1 index=13129 cmd=frames txn=13128 pages=3 commit=1 start
2019-01-31 07:51:56.44478: fsm: term=1 index=13129 cmd=frames txn=13128 pages=3 commit=1 unregister txn
2019-01-31 07:51:56.44478: fsm: term=1 index=13129 cmd=frames txn=13128 pages=3 commit=1 done
2019-01-31 07:51:56.44480: fsm: term=1 index=13130 cmd=frames txn=13129 pages=3 commit=1 start
2019-01-31 07:51:56.44495: fsm: term=1 index=13130 cmd=frames txn=13129 pages=3 commit=1 unregister txn
2019-01-31 07:51:56.44495: fsm: term=1 index=13130 cmd=frames txn=13129 pages=3 commit=1 done
2019-01-31 07:51:56.44496: fsm: term=1 index=13131 cmd=frames txn=13130 pages=5 commit=1 start
2019-01-31 07:51:56.44513: fsm: term=1 index=13131 cmd=frames txn=13130 pages=5 commit=1 unregister txn
2019-01-31 07:51:56.44513: fsm: term=1 index=13131 cmd=frames txn=13130 pages=5 commit=1 done
2019-01-31 07:51:56.44514: fsm: term=1 index=13132 cmd=frames txn=13131 pages=3 commit=1 start
2019-01-31 07:51:56.44529: fsm: term=1 index=13132 cmd=frames txn=13131 pages=3 commit=1 unregister txn
2019-01-31 07:51:56.44529: fsm: term=1 index=13132 cmd=frames txn=13131 pages=3 commit=1 done
2019-01-31 07:51:56.44530: fsm: term=1 index=13133 cmd=frames txn=13132 pages=2 commit=1 start
2019-01-31 07:51:56.44544: fsm: term=1 index=13133 cmd=frames txn=13132 pages=2 commit=1 unregister txn
2019-01-31 07:51:56.44544: fsm: term=1 index=13133 cmd=frames txn=13132 pages=2 commit=1 done
2019-01-31 07:51:56.44545: fsm: term=1 index=13134 cmd=frames txn=13133 pages=2 commit=1 start
2019-01-31 07:51:56.44559: fsm: term=1 index=13134 cmd=frames txn=13133 pages=2 commit=1 unregister txn
2019-01-31 07:51:56.44559: fsm: term=1 index=13134 cmd=frames txn=13133 pages=2 commit=1 done
2019-01-31 07:51:56.44560: fsm: term=1 index=13135 cmd=frames txn=13134 pages=3 commit=1 start
2019-01-31 07:51:56.44576: fsm: term=1 index=13135 cmd=frames txn=13134 pages=3 commit=1 unregister txn
2019-01-31 07:51:56.44576: fsm: term=1 index=13135 cmd=frames txn=13134 pages=3 commit=1 done
2019-01-31 07:51:56.44577: fsm: term=1 index=13136 cmd=frames txn=13135 pages=3 commit=1 start
2019-01-31 07:51:56.44595: fsm: term=1 index=13136 cmd=frames txn=13135 pages=3 commit=1 unregister txn
2019-01-31 07:51:56.44595: fsm: term=1 index=13136 cmd=frames txn=13135 pages=3 commit=1 done
2019-01-31 07:51:56.44596: fsm: term=1 index=13137 cmd=frames txn=13136 pages=3 commit=1 start
2019-01-31 07:51:56.44611: fsm: term=1 index=13137 cmd=frames txn=13136 pages=3 commit=1 unregister txn
2019-01-31 07:51:56.44611: fsm: term=1 index=13137 cmd=frames txn=13136 pages=3 commit=1 done
2019-01-31 07:51:56.44612: fsm: term=1 index=13138 cmd=frames txn=13137 pages=2 commit=1 start
2019-01-31 07:51:56.44626: fsm: term=1 index=13138 cmd=frames txn=13137 pages=2 commit=1 unregister txn
2019-01-31 07:51:56.44626: fsm: term=1 index=13138 cmd=frames txn=13137 pages=2 commit=1 done
2019-01-31 07:51:56.44627: fsm: term=1 index=13139 cmd=undo txn=13137 start


goroutine 57 [running]:
github.com/CanonicalLtd/dqlite/internal/trace.(*Tracer).Panic(0xc420107b80, 0x1016e88, 0xd, 0x0, 0x0, 0x0)
	/build/lxd-qbUNPi/lxd-3.0.1/obj-x86_64-linux-gnu/src/github.com/CanonicalLtd/dqlite/internal/trace/tracer.go:59 +0x12c
github.com/CanonicalLtd/dqlite/internal/replication.(*FSM).applyUndo(0xc42036de40, 0xc420107b80, 0xc4203aa458, 0x1, 0xc420107a40)
	/build/lxd-qbUNPi/lxd-3.0.1/obj-x86_64-linux-gnu/src/github.com/CanonicalLtd/dqlite/internal/replication/fsm.go:335 +0x200
github.com/CanonicalLtd/dqlite/internal/replication.(*FSM).apply(0xc42036de40, 0xc420107a40, 0xc4205f4120, 0xc41a997aaa, 0x1a997aaa00000003)
	/build/lxd-qbUNPi/lxd-3.0.1/obj-x86_64-linux-gnu/src/github.com/CanonicalLtd/dqlite/internal/replication/fsm.go:116 +0x4b6
github.com/CanonicalLtd/dqlite/internal/replication.(*FSM).Apply(0xc42036de40, 0xc4205f4120, 0x0, 0x0)
	/build/lxd-qbUNPi/lxd-3.0.1/obj-x86_64-linux-gnu/src/github.com/CanonicalLtd/dqlite/internal/replication/fsm.go:81 +0xaf
github.com/hashicorp/raft.(*Raft).runFSM.func1(0xc4201b6420)
	/build/lxd-qbUNPi/lxd-3.0.1/obj-x86_64-linux-gnu/src/github.com/hashicorp/raft/fsm.go:57 +0x15a
github.com/hashicorp/raft.(*Raft).runFSM(0xc4203e2000)
	/build/lxd-qbUNPi/lxd-3.0.1/obj-x86_64-linux-gnu/src/github.com/hashicorp/raft/fsm.go:120 +0x2fa
github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.runFSM)-fm()
	/build/lxd-qbUNPi/lxd-3.0.1/obj-x86_64-linux-gnu/src/github.com/hashicorp/raft/api.go:506 +0x2a
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc4203e2000, 0xc4204e09d0)
	/build/lxd-qbUNPi/lxd-3.0.1/obj-x86_64-linux-gnu/src/github.com/hashicorp/raft/state.go:146 +0x53
created by github.com/hashicorp/raft.(*raftState).goFunc
	/build/lxd-qbUNPi/lxd-3.0.1/obj-x86_64-linux-gnu/src/github.com/hashicorp/raft/state.go:144 +0x66
```

**Comment by stgraber** [comment]
@freeekanayaka may be able to help you here. The short version is that your database got corrupted as it couldn't fully save a transaction when your disk got full, but it's often possible to manually remove that last transaction and get things working again.

**Comment by stgraber** [comment]
Once your database is fixed, you should really be updating your system, you're running 3.0.1 when 3.0.3 is available with significant improvements to database handling which may have avoided this situation entirely.

Note that I wouldn't recommend attempting an update until the database is back to a readable state though. That's unless @freeekanayaka says it should be safe.

**Comment by freeekanayaka** [comment]
What @stgraber said is accurate. Please @smilekat can you send me a tarball of your /var/lib/lxd/database/ directory? I'll then try to fix it and send you back the amended tarball. My email is free.ekanayaka at canonical dot com.

**Comment by smilekat** [comment]
I sent e-mail to freeekanayka so, please check my e-mail. If you did not receive it or need more data, I can send again. 
Thank you !

**Comment by freeekanayaka** [comment]
@smilekat can you send me the tarball again? I don't think I received it. free dot ekanayaka at canonical dot com.

**Comment by smilekat** [comment]
I sent again. please check my e-mail. Thank you!

**Comment by stgraber** [comment]
@freeekanayaka update on this?

**Comment by smilekat** [comment]
@freeekanayaka Do you have any problem when checking the files, or if you need further information please inform us. We look forward to your reply.

**Comment by freeekanayaka** [comment]
@smilekat @smilekat : sorry, I'm stupid, now that I look closer I see both the original email with the tarball and the new one, and also the notification for this issue. I somehow misconfigured my mail filter. Apologies, I'll look into this shortly.

**Comment by freeekanayaka** [comment]
@smilekat I replied you by email, attaching a recovered version of the database.

We have seen this issue before in LXD 3.0.1. If everything works again, please upgrade to LXD 3.0.3.

**Comment by smilekat** [comment]
I did successfully recovery containers. I really appreciate your support.
