### ISSUE TITLE
Rename missing backup gives empty response

### ISSUE THREAD

**Issue by turtle0x1** [lxc/lxd#5762]
If  you try to rename a backup that doesn't exist you get an empty response from the server, could some sort of error be returned ?

Thanks

**Comment by stgraber** [comment]
What do you mean exactly?

```
stgraber@castiana:~$ lxc query -X POST /1.0/containers/limits/snapshots/snap0 -d '{"name": "snap1"}' --wait
{
	"class": "task",
	"created_at": "2019-05-16T01:04:41.521237499+02:00",
	"description": "Renaming snapshot",
	"err": "",
	"id": "18a688aa-ddcb-4d2f-bc3f-ce0637d18bb7",
	"location": "none",
	"may_cancel": false,
	"metadata": null,
	"resources": {
		"containers": [
			"/1.0/containers/limits"
		]
	},
	"status": "Success",
	"status_code": 200,
	"updated_at": "2019-05-16T01:04:41.521237499+02:00"
}

stgraber@castiana:~$ lxc query -X POST /1.0/containers/limits/snapshots/snap0 -d '{"name": "snap1"}' --wait
Error: not found
```

**Comment by turtle0x1** [comment]
sorry thats a snap shot not a backup as defined here https://github.com/lxc/lxd/blob/master/doc/rest-api.md#post-5

**Comment by stgraber** [comment]
Oh, sorry, I misread, I'll look into the backup case, thanks.

**Comment by tomponline** [comment]
@stgraber not only that but I can crash LXD trying to rename a missing backup:

`testmissing` doesn't exist as a container:

```
lxc query -X POST /1.0/containers/testmissing/backups/test -d '{"name": "test1b"}' --wait
Error: not found
```

`test1` exists as a container but has not backups:

```
lxc query -X POST /1.0/containers/test1/backups/test1 -d '{"name": "test1b"}' --wait
Error: Post http://unix.socket/1.0/containers/test1/backups/test1: dial unix /var/lib/lxd/unix.socket: connect: connection refused
```

Oh dear:

```
DBUG[05-16|11:50:51] Handling                                 ip=@ user= method=GET url=/1.0
DBUG[05-16|11:50:51] Handling                                 ip=@ user= method=POST url=/1.0/containers/test1/backups/test1
DBUG[05-16|11:50:51] Database error: &errors.errorString{s:"sql: no rows in result set"} 
DBUG[05-16|11:50:51] New task operation: a35dde60-81bd-4acc-8c18-848c4c1534fc 
DBUG[05-16|11:50:51] Started task operation: a35dde60-81bd-4acc-8c18-848c4c1534fc 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xccad39]

goroutine 1460 [running]:
main.(*backup).Rename(0x0, 0xc4200de190, 0xc, 0x6b83a0, 0xc4200ca240)
	/home/user/go/src/github.com/lxc/lxd/lxd/backup.go:108 +0x59
main.containerBackupPost.func1(0xc42033a1e0, 0xc4206aa000, 0xc420019508)
	/home/user/go/src/github.com/lxc/lxd/lxd/container_backup.go:235 +0x3c
main.(*operation).Run.func1(0xc42033a1e0, 0xc420338cc0)
	/home/user/go/src/github.com/lxc/lxd/lxd/operations.go:145 +0x4a
created by main.(*operation).Run
	/home/user/go/src/github.com/lxc/lxd/lxd/operations.go:144 +0x3c1
```
