### ISSUE TITLE
Panic of LXD v3.14 (rev 11098)

### ISSUE THREAD

**Issue by leonklingele** [lxc/lxd#5946]
# Required information

 * Distribution: Debian
 * Distribution version: Buster 
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.19.0-5-amd64
   * LXC version: ?
   * LXD version: 3.14, rev 11098 (snap)
   * Storage backend in use: dir

# Issue description

While browsing through the journal, I found a panic of LXD. It might have paniced when I tried to restart it (`snap restart lxd`).

# Information to attach

Relevant journal excerpt:

```
Jul 11 21:10:51 HOST lxd.daemon[4421]: fatal error: unexpected signal during runtime execution
Jul 11 21:10:51 HOST lxd.daemon[4421]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x39e5e70 pc=0x7f19e66c2bc1]
Jul 11 21:10:51 HOST lxd.daemon[4421]: runtime stack:
Jul 11 21:10:51 HOST lxd.daemon[4421]: runtime.throw(0x12b1784, 0x2a)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /snap/go/3947/src/runtime/panic.go:617 +0x72
Jul 11 21:10:51 HOST lxd.daemon[4421]: runtime.sigpanic()
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /snap/go/3947/src/runtime/signal_unix.go:374 +0x4a9
Jul 11 21:10:51 HOST lxd.daemon[4421]: goroutine 25 [syscall, locked to thread]:
Jul 11 21:10:51 HOST lxd.daemon[4421]: runtime.cgocall(0x102a1b0, 0xc000067f10, 0xc000052f60)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /snap/go/3947/src/runtime/cgocall.go:128 +0x5b fp=0xc000067ee0 sp=0xc000067ea8 pc=0x40f40b
Jul 11 21:10:51 HOST lxd.daemon[4421]: github.com/lxc/lxd/vendor/github.com/CanonicalLtd/go-dqlite/internal/bindings._Cfunc_dqlite_server_run(0x36a7760, 0x0)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         _cgo_gotypes.go:432 +0x49 fp=0xc000067f10 sp=0xc000067ee0 pc=0x8a3a89
Jul 11 21:10:51 HOST lxd.daemon[4421]: github.com/lxc/lxd/vendor/github.com/CanonicalLtd/go-dqlite/internal/bindings.(*Server).Run.func1(0x36a7760, 0x55)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/vendor/github.com/CanonicalLtd/go-dqlite/internal/bindings/server.go:151 +0x56 fp=0xc000067f48 sp=0xc000067f10 pc=0x8aa076
Jul 11 21:10:51 HOST lxd.daemon[4421]: github.com/lxc/lxd/vendor/github.com/CanonicalLtd/go-dqlite/internal/bindings.(*Server).Run(0x36a7760, 0x1304738, 0x1)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/vendor/github.com/CanonicalLtd/go-dqlite/internal/bindings/server.go:151 +0x2f fp=0xc000067fa0 sp=0xc000067f48 pc=0x8a747f
Jul 11 21:10:51 HOST lxd.daemon[4421]: github.com/lxc/lxd/vendor/github.com/CanonicalLtd/go-dqlite.(*Server).run(0xc000a662d0)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/vendor/github.com/CanonicalLtd/go-dqlite/server.go:131 +0x54 fp=0xc000067fd8 sp=0xc000067fa0 pc=0x9f5e64
Jul 11 21:10:51 HOST lxd.daemon[4421]: runtime.goexit()
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /snap/go/3947/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000067fe0 sp=0xc000067fd8 pc=0x469461
Jul 11 21:10:51 HOST lxd.daemon[4421]: created by github.com/lxc/lxd/vendor/github.com/CanonicalLtd/go-dqlite.NewServer
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/vendor/github.com/CanonicalLtd/go-dqlite/server.go:88 +0x367
Jul 11 21:10:51 HOST lxd.daemon[4421]: goroutine 1 [runnable]:
Jul 11 21:10:51 HOST lxd.daemon[4421]: github.com/mattn/go-sqlite3._Cfunc_sqlite3_close_v2(0x355c2a0, 0x0)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         _cgo_gotypes.go:611 +0x49
Jul 11 21:10:51 HOST lxd.daemon[4421]: github.com/mattn/go-sqlite3.(*SQLiteConn).Close.func1(0xc0001ff4a0, 0x0)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/mattn/go-sqlite3/sqlite3.go:1652 +0x5f
Jul 11 21:10:51 HOST lxd.daemon[4421]: github.com/mattn/go-sqlite3.(*SQLiteConn).Close(0xc0001ff4a0, 0x8, 0xc000971740)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/mattn/go-sqlite3/sqlite3.go:1652 +0x2f
Jul 11 21:10:51 HOST lxd.daemon[4421]: database/sql.(*driverConn).finalClose.func2()
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /snap/go/3947/src/database/sql/sql.go:521 +0x49
Jul 11 21:10:51 HOST lxd.daemon[4421]: database/sql.withLock(0x14ac420, 0xc000214780, 0xc0003d1870)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /snap/go/3947/src/database/sql/sql.go:3097 +0x63
Jul 11 21:10:51 HOST lxd.daemon[4421]: database/sql.(*driverConn).finalClose(0xc000214780, 0xc000465f80, 0xc0002147a0)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /snap/go/3947/src/database/sql/sql.go:519 +0x130
Jul 11 21:10:51 HOST lxd.daemon[4421]: database/sql.(*DB).Close(0xc0000f69c0, 0x0, 0x0)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /snap/go/3947/src/database/sql/sql.go:778 +0x267
Jul 11 21:10:51 HOST lxd.daemon[4421]: github.com/lxc/lxd/lxd/db.(*Node).Close(...)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/db/db.go:133
Jul 11 21:10:51 HOST lxd.daemon[4421]: main.(*Daemon).Stop(0xc00017e5a0, 0x0, 0x0)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/daemon.go:1072 +0x82e
Jul 11 21:10:51 HOST lxd.daemon[4421]: main.(*cmdDaemon).Run(0xc000193480, 0xc0001d3180, 0xc000121ac0, 0x0, 0x4, 0x0, 0x0)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/main_daemon.go:90 +0x5d1
Jul 11 21:10:51 HOST lxd.daemon[4421]: github.com/spf13/cobra.(*Command).execute(0xc0001d3180, 0xc000032060, 0x4, 0x4, 0xc0001d3180, 0xc000032060)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/spf13/cobra/command.go:826 +0x465
Jul 11 21:10:51 HOST lxd.daemon[4421]: github.com/spf13/cobra.(*Command).ExecuteC(0xc0001d3180, 0xc0001c9f60, 0x1, 0x1)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/spf13/cobra/command.go:914 +0x2fc
Jul 11 21:10:51 HOST lxd.daemon[4421]: github.com/spf13/cobra.(*Command).Execute(...)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/spf13/cobra/command.go:864
Jul 11 21:10:51 HOST lxd.daemon[4421]: main.main()
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/main.go:176 +0xe82
Jul 11 21:10:51 HOST lxd.daemon[4421]: goroutine 5 [syscall]:
Jul 11 21:10:51 HOST lxd.daemon[4421]: os/signal.signal_recv(0x0)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /snap/go/3947/src/runtime/sigqueue.go:139 +0x9c
Jul 11 21:10:51 HOST lxd.daemon[4421]: os/signal.loop()
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /snap/go/3947/src/os/signal/signal_unix.go:23 +0x22
Jul 11 21:10:51 HOST lxd.daemon[4421]: created by os/signal.init.0
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /snap/go/3947/src/os/signal/signal_unix.go:29 +0x41
Jul 11 21:10:51 HOST lxd.daemon[4421]: goroutine 9 [select]:
Jul 11 21:10:51 HOST lxd.daemon[4421]: database/sql.(*DB).connectionOpener(0xc0000f69c0, 0x14c1ee0, 0xc0002074c0)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /snap/go/3947/src/database/sql/sql.go:1000 +0xe8
Jul 11 21:10:51 HOST lxd.daemon[4421]: created by database/sql.OpenDB
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /snap/go/3947/src/database/sql/sql.go:670 +0x15e
Jul 11 21:10:51 HOST lxd.daemon[4421]: goroutine 10 [select]:
Jul 11 21:10:51 HOST lxd.daemon[4421]: database/sql.(*DB).connectionResetter(0xc0000f69c0, 0x14c1ee0, 0xc0002074c0)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /snap/go/3947/src/database/sql/sql.go:1013 +0xfb
Jul 11 21:10:51 HOST lxd.daemon[4421]: created by database/sql.OpenDB
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /snap/go/3947/src/database/sql/sql.go:671 +0x194
Jul 11 21:10:51 HOST lxd.daemon[4421]: goroutine 26 [IO wait]:
Jul 11 21:10:51 HOST lxd.daemon[4421]: internal/poll.runtime_pollWait(0x7f19e89cdf08, 0x72, 0x0)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /snap/go/3947/src/runtime/netpoll.go:182 +0x56
Jul 11 21:10:51 HOST lxd.daemon[4421]: internal/poll.(*pollDesc).wait(0xc0000f2198, 0x72, 0x0, 0x0, 0x1279a8c)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /snap/go/3947/src/internal/poll/fd_poll_runtime.go:87 +0x9b
Jul 11 21:10:51 HOST lxd.daemon[4421]: internal/poll.(*pollDesc).waitRead(...)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /snap/go/3947/src/internal/poll/fd_poll_runtime.go:92
Jul 11 21:10:51 HOST lxd.daemon[4421]: internal/poll.(*FD).Accept(0xc0000f2180, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /snap/go/3947/src/internal/poll/fd_unix.go:384 +0x1ba
Jul 11 21:10:51 HOST lxd.daemon[4421]: net.(*netFD).accept(0xc0000f2180, 0x0, 0x0, 0xc000011690)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /snap/go/3947/src/net/fd_unix.go:238 +0x42
Jul 11 21:10:51 HOST lxd.daemon[4421]: net.(*UnixListener).accept(0xc00001e1e0, 0xc000011690, 0x0, 0x0)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /snap/go/3947/src/net/unixsock_posix.go:162 +0x32
Jul 11 21:10:51 HOST lxd.daemon[4421]: net.(*UnixListener).Accept(0xc00001e1e0, 0x14d6d00, 0xc000011690, 0x0, 0x0)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /snap/go/3947/src/net/unixsock.go:260 +0x48
Jul 11 21:10:51 HOST lxd.daemon[4421]: github.com/lxc/lxd/vendor/github.com/CanonicalLtd/go-dqlite.(*Server).acceptLoop(0xc000a662d0)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/vendor/github.com/CanonicalLtd/go-dqlite/server.go:138 +0x7b
Jul 11 21:10:51 HOST lxd.daemon[4421]: created by github.com/lxc/lxd/vendor/github.com/CanonicalLtd/go-dqlite.NewServer
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/vendor/github.com/CanonicalLtd/go-dqlite/server.go:94 +0x454
Jul 11 21:10:51 HOST lxd.daemon[4421]: goroutine 24 [select]:
Jul 11 21:10:51 HOST lxd.daemon[4421]: github.com/lxc/lxd/vendor/github.com/hashicorp/raft.(*Raft).runSnapshots(0xc000238600)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/vendor/github.com/hashicorp/raft/snapshot.go:71 +0x115
Jul 11 21:10:51 HOST lxd.daemon[4421]: github.com/lxc/lxd/vendor/github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc000238600, 0xc000111870)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/vendor/github.com/hashicorp/raft/state.go:146 +0x53
Jul 11 21:10:51 HOST lxd.daemon[4421]: created by github.com/lxc/lxd/vendor/github.com/hashicorp/raft.(*raftState).goFunc
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/vendor/github.com/hashicorp/raft/state.go:144 +0x66
Jul 11 21:10:51 HOST lxd.daemon[4421]: goroutine 23 [select]:
Jul 11 21:10:51 HOST lxd.daemon[4421]: github.com/lxc/lxd/vendor/github.com/hashicorp/raft.(*Raft).runFSM(0xc000238600)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/vendor/github.com/hashicorp/raft/fsm.go:116 +0x1e5
Jul 11 21:10:51 HOST lxd.daemon[4421]: github.com/lxc/lxd/vendor/github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc000238600, 0xc000111860)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/vendor/github.com/hashicorp/raft/state.go:146 +0x53
Jul 11 21:10:51 HOST lxd.daemon[4421]: created by github.com/lxc/lxd/vendor/github.com/hashicorp/raft.(*raftState).goFunc
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/vendor/github.com/hashicorp/raft/state.go:144 +0x66
Jul 11 21:10:51 HOST lxd.daemon[4421]: goroutine 22 [select]:
Jul 11 21:10:51 HOST lxd.daemon[4421]: github.com/lxc/lxd/vendor/github.com/hashicorp/raft.(*Raft).leaderLoop(0xc000238600)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/vendor/github.com/hashicorp/raft/raft.go:502 +0x2ff
Jul 11 21:10:51 HOST lxd.daemon[4421]: github.com/lxc/lxd/vendor/github.com/hashicorp/raft.(*Raft).runLeader(0xc000238600)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/vendor/github.com/hashicorp/raft/raft.go:419 +0x379
Jul 11 21:10:51 HOST lxd.daemon[4421]: github.com/lxc/lxd/vendor/github.com/hashicorp/raft.(*Raft).run(0xc000238600)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/vendor/github.com/hashicorp/raft/raft.go:140 +0x66
Jul 11 21:10:51 HOST lxd.daemon[4421]: github.com/lxc/lxd/vendor/github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc000238600, 0xc000111850)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/vendor/github.com/hashicorp/raft/state.go:146 +0x53
Jul 11 21:10:51 HOST lxd.daemon[4421]: created by github.com/lxc/lxd/vendor/github.com/hashicorp/raft.(*raftState).goFunc
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/vendor/github.com/hashicorp/raft/state.go:144 +0x66
Jul 11 21:10:51 HOST lxd.daemon[4421]: goroutine 35 [runnable]:
Jul 11 21:10:51 HOST lxd.daemon[4421]: database/sql.(*DB).connectionOpener(0xc0000f6b40, 0x14c1ee0, 0xc000a65300)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /snap/go/3947/src/database/sql/sql.go:1000 +0xe8
Jul 11 21:10:51 HOST lxd.daemon[4421]: created by database/sql.OpenDB
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /snap/go/3947/src/database/sql/sql.go:670 +0x15e
Jul 11 21:10:51 HOST lxd.daemon[4421]: goroutine 36 [runnable]:
Jul 11 21:10:51 HOST lxd.daemon[4421]: database/sql.(*DB).connectionResetter(0xc0000f6b40, 0x14c1ee0, 0xc000a65300)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /snap/go/3947/src/database/sql/sql.go:1013 +0xfb
Jul 11 21:10:51 HOST lxd.daemon[4421]: created by database/sql.OpenDB
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /snap/go/3947/src/database/sql/sql.go:671 +0x194
Jul 11 21:10:51 HOST lxd.daemon[4421]: goroutine 1251 [chan receive]:
Jul 11 21:10:51 HOST lxd.daemon[4421]: main.deviceInotifyHandler(0xc00023ce40)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/devices.go:2277 +0x56
Jul 11 21:10:51 HOST lxd.daemon[4421]: created by main.(*Daemon).init
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/daemon.go:874 +0x1751
Jul 11 21:10:51 HOST lxd.daemon[4421]: goroutine 1252 [syscall]:
Jul 11 21:10:51 HOST lxd.daemon[4421]: syscall.Syscall(0x0, 0x3, 0xc0002b2000, 0x64640, 0x4504fc, 0x66000, 0x10dc4e0)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /snap/go/3947/src/syscall/asm_linux_amd64.s:18 +0x5
Jul 11 21:10:51 HOST lxd.daemon[4421]: golang.org/x/sys/unix.read(0x3, 0xc0002b2000, 0x64640, 0x64640, 0x0, 0x442026, 0x13048c8)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/golang.org/x/sys/unix/zsyscall_linux_amd64.go:1219 +0x5a
Jul 11 21:10:51 HOST lxd.daemon[4421]: golang.org/x/sys/unix.Read(...)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/golang.org/x/sys/unix/syscall_unix.go:157
Jul 11 21:10:51 HOST lxd.daemon[4421]: main.deviceInotifyWatcher.func1(0xc00023ce40, 0xc0003dcd80)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/devices.go:1922 +0x7e
Jul 11 21:10:51 HOST lxd.daemon[4421]: created by main.deviceInotifyWatcher
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/devices.go:1919 +0x67
Jul 11 21:10:51 HOST lxd.daemon[4421]: goroutine 1226 [select]:
Jul 11 21:10:51 HOST lxd.daemon[4421]: main.deviceEventListener(0xc00020c6c0)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/devices.go:1049 +0x1bf
Jul 11 21:10:51 HOST lxd.daemon[4421]: created by main.(*Daemon).init
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/daemon.go:865 +0x15aa
Jul 11 21:10:51 HOST lxd.daemon[4421]: goroutine 1227 [syscall]:
Jul 11 21:10:51 HOST lxd.daemon[4421]: syscall.Syscall(0x0, 0x15, 0xc000225000, 0x1000, 0x0, 0xc000a38ea0, 0x0)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /snap/go/3947/src/syscall/asm_linux_amd64.s:18 +0x5
Jul 11 21:10:51 HOST lxd.daemon[4421]: golang.org/x/sys/unix.read(0x15, 0xc000225000, 0x1000, 0x1000, 0xc000a38f28, 0x1, 0xc00046bf80)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/golang.org/x/sys/unix/zsyscall_linux_amd64.go:1219 +0x5a
Jul 11 21:10:51 HOST lxd.daemon[4421]: golang.org/x/sys/unix.Read(...)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/golang.org/x/sys/unix/syscall_unix.go:157
Jul 11 21:10:51 HOST lxd.daemon[4421]: main.deviceNetlinkListener.func1(0x800, 0x15, 0xc0004f8840, 0xc0003dcae0, 0xc0003dcb40)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/devices.go:612 +0x9f
Jul 11 21:10:51 HOST lxd.daemon[4421]: created by main.deviceNetlinkListener
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/devices.go:609 +0x1d2
Jul 11 21:10:51 HOST lxd.daemon[4421]: goroutine 3184 [select]:
Jul 11 21:10:51 HOST lxd.daemon[4421]: main.(*lxcContainerOperation).Create.func1(0xc0009c2ec0)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/container_lxc.go:67 +0xc8
Jul 11 21:10:51 HOST lxd.daemon[4421]: created by main.(*lxcContainerOperation).Create
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/container_lxc.go:65 +0xd2
Jul 11 21:10:51 HOST lxd.daemon[4421]: goroutine 3172 [select]:
Jul 11 21:10:51 HOST lxd.daemon[4421]: main.(*lxcContainerOperation).Create.func1(0xc00028de80)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/container_lxc.go:67 +0xc8
Jul 11 21:10:51 HOST lxd.daemon[4421]: created by main.(*lxcContainerOperation).Create
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/container_lxc.go:65 +0xd2
Jul 11 21:10:51 HOST lxd.daemon[4421]: goroutine 3169 [select]:
Jul 11 21:10:51 HOST lxd.daemon[4421]: main.(*lxcContainerOperation).Create.func1(0xc00028d9c0)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/container_lxc.go:67 +0xc8
Jul 11 21:10:51 HOST lxd.daemon[4421]: created by main.(*lxcContainerOperation).Create
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/container_lxc.go:65 +0xd2
Jul 11 21:10:51 HOST lxd.daemon[4421]: goroutine 3133 [chan receive]:
Jul 11 21:10:51 HOST lxd.daemon[4421]: main.eventsSocket(0xc00017e5a0, 0xc0008e4900, 0x14bc120, 0xc000a4ed20, 0xc0008e4900, 0xc00017e5a0)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/events.go:140 +0x518
Jul 11 21:10:51 HOST lxd.daemon[4421]: main.(*eventsServe).Render(0xc0008d0370, 0x14bc120, 0xc000a4ed20, 0x14ad220, 0xc0008d0370)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/events.go:88 +0x4b
Jul 11 21:10:51 HOST lxd.daemon[4421]: main.(*Daemon).createCmd.func1(0x14bc120, 0xc000a4ed20, 0xc0008e4900)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/daemon.go:446 +0xba1
Jul 11 21:10:51 HOST lxd.daemon[4421]: net/http.HandlerFunc.ServeHTTP(0xc00088d230, 0x14bc120, 0xc000a4ed20, 0xc0008e4800)
Jul 11 21:10:51 HOST systemd[1]: snap.lxd.daemon.service: Main process exited, code=exited, status=1/FAILURE
Jul 11 21:10:51 HOST lxd.daemon[5508]: => Stopping LXCFS
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /snap/go/3947/src/net/http/server.go:1995 +0x44
Jul 11 21:10:51 HOST lxd.daemon[4421]: github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000f6300, 0x14bc120, 0xc000a4ed20, 0xc0008e4500)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/gorilla/mux/mux.go:212 +0xe3
Jul 11 21:10:51 HOST lxd.daemon[4421]: main.(*lxdHttpServer).ServeHTTP(0xc00021cc10, 0x14bc120, 0xc000a4ed20, 0xc0008e4500)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/api.go:79 +0x94
Jul 11 21:10:51 HOST lxd.daemon[4421]: net/http.serverHandler.ServeHTTP(0xc000097e10, 0x14bc120, 0xc000a4ed20, 0xc0008e4500)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /snap/go/3947/src/net/http/server.go:2774 +0xa8
Jul 11 21:10:51 HOST lxd.daemon[4421]: net/http.(*conn).serve(0xc000351900, 0x14c1ee0, 0xc000206b80)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /snap/go/3947/src/net/http/server.go:1878 +0x851
Jul 11 21:10:51 HOST lxd.daemon[4421]: created by net/http.(*Server).Serve
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /snap/go/3947/src/net/http/server.go:2884 +0x2f4
Jul 11 21:10:51 HOST lxd.daemon[4421]: goroutine 3179 [select]:
Jul 11 21:10:51 HOST lxd.daemon[4421]: main.(*lxcContainerOperation).Create.func1(0xc0009c2700)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/container_lxc.go:67 +0xc8
Jul 11 21:10:51 HOST lxd.daemon[4421]: created by main.(*lxcContainerOperation).Create
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/container_lxc.go:65 +0xd2
Jul 11 21:10:51 HOST lxd.daemon[4421]: goroutine 3175 [select]:
Jul 11 21:10:51 HOST lxd.daemon[4421]: main.(*lxcContainerOperation).Create.func1(0xc0009c2340)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/container_lxc.go:67 +0xc8
Jul 11 21:10:51 HOST lxd.daemon[4421]: created by main.(*lxcContainerOperation).Create
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/container_lxc.go:65 +0xd2
Jul 11 21:10:51 HOST lxd.daemon[4421]: goroutine 3181 [select]:
Jul 11 21:10:51 HOST lxd.daemon[4421]: main.(*lxcContainerOperation).Create.func1(0xc0009c27c0)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/container_lxc.go:67 +0xc8
Jul 11 21:10:51 HOST lxd.daemon[4421]: created by main.(*lxcContainerOperation).Create
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/container_lxc.go:65 +0xd2
Jul 11 21:10:51 HOST lxd.daemon[4421]: goroutine 3166 [select]:
Jul 11 21:10:51 HOST lxd.daemon[4421]: main.(*lxcContainerOperation).Create.func1(0xc00028d600)
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/container_lxc.go:67 +0xc8
Jul 11 21:10:51 HOST lxd.daemon[4421]: created by main.(*lxcContainerOperation).Create
Jul 11 21:10:51 HOST lxd.daemon[4421]:         /build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/container_lxc.go:65 +0xd2
Jul 11 21:10:51 HOST lxd.daemon[4421]: => LXD failed with return code 2
```

**Comment by stgraber** [comment]
Let us know if this is preventing LXD from starting up on your system and we'll help get you back online if that's the case.

Otherwise, we're not going to be looking into this issue as we've entirely replaced that dqlite code in LXD 3.15 (which was released a few hours ago) and so it's extremely unlikely that this particular bug would still be present.

**Comment by leonklingele** [comment]
No, it's starting up and working fine. Just something I've noticed which might be of interest.
Thanks for your support @stgraber! I will keep you posted once this issue strikes again.
