### ISSUE TITLE
panic when starting lxd: checking the version of dnsmasq fails

### ISSUE THREAD

**Issue by nicolas33** [lxc/lxd#6109]
# Required information

 * Distribution: manjaro (archlinux AUR: aur/lxd)
 * The output of "lxc info" or if that fails:
   * LXD version: 3.15

# Issue description

```
août 21 10:47:22 nsebrecht-desktop lxd[29743]: panic: runtime error: invalid memory address or nil pointer dereference
août 21 10:47:22 nsebrecht-desktop lxd[29743]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x896f36]
août 21 10:47:22 nsebrecht-desktop lxd[29743]: goroutine 1 [running]:
août 21 10:47:22 nsebrecht-desktop lxd[29743]: github.com/lxc/lxd/shared/version.(*DottedVersion).Compare(0x0, 0xc00003c540, 0xc00003c540)
août 21 10:47:22 nsebrecht-desktop lxd[29743]:         /home/nicolas/.cache/pikaur/build/lxd/src/go/src/github.com/lxc/lxd/shared/version/version.go:71 +0x6
août 21 10:47:22 nsebrecht-desktop lxd[29743]: main.(*network).Start(0xc0003363c0, 0xc000312536, 0x6)
août 21 10:47:22 nsebrecht-desktop lxd[29743]:         /home/nicolas/.cache/pikaur/build/lxd/src/go/src/github.com/lxc/lxd/lxd/networks.go:1295 +0xe08
août 21 10:47:22 nsebrecht-desktop lxd[29743]: main.networkStartup(0xc000325ec0, 0xc000325ec0, 0x0)
août 21 10:47:22 nsebrecht-desktop lxd[29743]:         /home/nicolas/.cache/pikaur/build/lxd/src/go/src/github.com/lxc/lxd/lxd/networks.go:879 +0x13a
août 21 10:47:22 nsebrecht-desktop lxd[29743]: main.(*Daemon).init(0xc000204640, 0x411190, 0x60)
août 21 10:47:22 nsebrecht-desktop lxd[29743]:         /home/nicolas/.cache/pikaur/build/lxd/src/go/src/github.com/lxc/lxd/lxd/daemon.go:788 +0x125d
août 21 10:47:22 nsebrecht-desktop lxd[29743]: main.(*Daemon).Init(0xc000204640, 0xc000204640, 0xc0000d6960)
août 21 10:47:22 nsebrecht-desktop lxd[29743]:         /home/nicolas/.cache/pikaur/build/lxd/src/go/src/github.com/lxc/lxd/lxd/daemon.go:499 +0x2f
août 21 10:47:22 nsebrecht-desktop lxd[29743]: main.(*cmdDaemon).Run(0xc000270820, 0xc0001d9900, 0xc000270920, 0x0, 0x2, 0x0, 0x0)
août 21 10:47:22 nsebrecht-desktop lxd[29743]:         /home/nicolas/.cache/pikaur/build/lxd/src/go/src/github.com/lxc/lxd/lxd/main_daemon.go:65 +0x417
août 21 10:47:22 nsebrecht-desktop lxd[29743]: github.com/spf13/cobra.(*Command).execute(0xc0001d9900, 0xc0000ae160, 0x2, 0x2, 0xc0001d9900, 0xc0000ae160)
août 21 10:47:22 nsebrecht-desktop lxd[29743]:         /home/nicolas/.cache/pikaur/build/lxd/src/go/src/github.com/spf13/cobra/command.go:829 +0x465
août 21 10:47:22 nsebrecht-desktop lxd[29743]: github.com/spf13/cobra.(*Command).ExecuteC(0xc0001d9900, 0xc0001edf60, 0x1, 0x1)
août 21 10:47:22 nsebrecht-desktop lxd[29743]:         /home/nicolas/.cache/pikaur/build/lxd/src/go/src/github.com/spf13/cobra/command.go:917 +0x2fc
août 21 10:47:22 nsebrecht-desktop lxd[29743]: github.com/spf13/cobra.(*Command).Execute(...)
août 21 10:47:22 nsebrecht-desktop lxd[29743]:         /home/nicolas/.cache/pikaur/build/lxd/src/go/src/github.com/spf13/cobra/command.go:867
août 21 10:47:22 nsebrecht-desktop lxd[29743]: main.main()
août 21 10:47:22 nsebrecht-desktop lxd[29743]:         /home/nicolas/.cache/pikaur/build/lxd/src/go/src/github.com/lxc/lxd/lxd/main.go:176 +0xe82
août 21 10:47:22 nsebrecht-desktop systemd[1]: lxd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

# Steps to reproduce

 1. systemctl restart lxd

# Possible fix

Adding the following line to `/etc/systemd/system/multi-user.target.wants/lxd.service` fixes the issue:
`Environment="LANG=C"`

I guess this is the best thing to do to avoid parsing many possible translated version strings. However, this could be done in the code while getting the version of the dependencies.

At least, lxd should not fail with a panic because of this.

Also, I couldn't find a systemd service file for lxd in this repository. If it's missing I wonder this should be something to add.

**Comment by stgraber** [comment]
@tomponline can you look into this? We'd want to run all such version info commands without locales (so using LANG=C.UTF-8) to avoid such issues. We may need another small RunCommand type function for that (RunCommandC or something).

**Comment by tomponline** [comment]
@stgraber will take a look at this first thing tomorrow.

**Comment by nicolas33** [comment]
Thanks!
