### ISSUE TITLE
armhf debugging using gdb does not work

### ISSUE THREAD

**Issue by srkunze** [lxc/lxd#8401]
Here we go. Let's start from this to avoid confusing with the other issues (https://github.com/haproxy/haproxy/issues/1035, https://github.com/lxc/lxd/issues/8395)

```
- buy a Raspberry Pi 4 Model B Rev 1.2
- install Ubuntu 20.04.1 LTS (arm64)
```

```
root@raspi:~# apt install lxd
root@raspi:~# lxc launch ubuntu:20.04/armhf haproxy

root@raspi:~# lxc shell haproxy
root@haproxy:~# apt install gdb
root@haproxy:~# gdb  -ex run --args /bin/id
Ctrl - C
t a a bt
```

Should result in
```
root@haproxy:~# gdb -ex run --args /bin/id
[....]
(No debugging symbols found in /bin/id)
Starting program: /usr/bin/id 
^C
Program received signal SIGINT, Interrupt.
0xf7fd12fe in ?? () from /lib/ld-linux-armhf.so.3
(gdb) t a a bt

Thread 1 (process 8339):
#0  0xf7fd12fe in ?? () from /lib/ld-linux-armhf.so.3
#1  0xf7fc81e4 in ?? () from /lib/ld-linux-armhf.so.3
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

```

Checks for the setup
```
root@raspi:~# uname -a
Linux raspi 5.4.0-1026-raspi #29-Ubuntu SMP PREEMPT Mon Dec 14 17:01:16 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux

root@raspi:~# lxc shell haproxy
root@haproxy:~# uname -a
Linux haproxy 5.4.0-1026-raspi #29-Ubuntu SMP PREEMPT Mon Dec 14 17:01:16 UTC 2020 armv8l armv8l armv8l GNU/Linux

```

**Comment by stgraber** [comment]
```
root@buildd02:~/chroot# uname -a
Linux buildd02 5.4.0-64-generic #72~18.04.1-Ubuntu SMP Fri Jan 15 14:04:56 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
root@buildd02:~/chroot# wget http://cdimage.ubuntu.com/ubuntu-base/focal/daily/current/focal-base-armhf.tar.gz
--2021-01-29 15:28:58--  http://cdimage.ubuntu.com/ubuntu-base/focal/daily/current/focal-base-armhf.tar.gz
Resolving cdimage.ubuntu.com (cdimage.ubuntu.com)... 2001:67c:1562::28, 2001:67c:1360:8001::34, 2001:67c:1360:8001::33, ...
Connecting to cdimage.ubuntu.com (cdimage.ubuntu.com)|2001:67c:1562::28|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 23269993 (22M) [application/x-gzip]
Saving to: ‘focal-base-armhf.tar.gz’

focal-base-armhf.tar.gz                 100%[==============================================================================>]  22.19M  34.6MB/s    in 0.6s    

2021-01-29 15:28:58 (34.6 MB/s) - ‘focal-base-armhf.tar.gz’ saved [23269993/23269993]

root@buildd02:~/chroot# tar zxf focal-base-armhf.tar.gz 
root@buildd02:~/chroot# cat /run/systemd/resolve/resolv.conf > etc/resolv.conf 
root@buildd02:~/chroot# chroot . /bin/sh
# setarch linux32 bash
root@buildd02:/# uname -a
Linux buildd02 5.4.0-64-generic #72~18.04.1-Ubuntu SMP Fri Jan 15 14:04:56 UTC 2021 armv7l armv7l armv7l GNU/Linux
root@buildd02:/# apt-get update
Get:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease [265 kB]
Get:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease [114 kB]
0% [Working]gpgv: Signature made Thu Apr 23 17:34:17 2020 UTC
gpgv:                using RSA key 3B4FE6ACC0B21F32
Get:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease [101 kB]
0% [3 InRelease 8239 B/101 kB 8%]gpgv: Good signature from "Ubuntu Archive Automatic Signing Key (2012) <ftpmaster@ubuntu.com>"
gpgv: Signature made Thu Apr 23 17:34:17 2020 UTC
gpgv:                using RSA key 871920D1991BC93C
gpgv: Good signature from "Ubuntu Archive Automatic Signing Key (2018) <ftpmaster@ubuntu.com>"
Get:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease [109 kB]
0% [4 InRelease 0 B/109 kB 0%]gpgv: Signature made Fri Jan 29 14:31:08 2021 UTC
gpgv:                using RSA key 3B4FE6ACC0B21F32
gpgv: Good signature from "Ubuntu Archive Automatic Signing Key (2012) <ftpmaster@ubuntu.com>"
gpgv: Signature made Fri Jan 29 14:31:08 2021 UTC
gpgv:                using RSA key 871920D1991BC93C
gpgv: Good signature from "Ubuntu Archive Automatic Signing Key (2018) <ftpmaster@ubuntu.com>"
Get:5 http://ports.ubuntu.com/ubuntu-ports focal/main armhf Packages [934 kB]
0% [5 Packages 8239 B/934 kB 1%]gpgv: Signature made Fri Jan 29 14:31:21 2021 UTC
gpgv:                using RSA key 3B4FE6ACC0B21F32
gpgv: Good signature from "Ubuntu Archive Automatic Signing Key (2012) <ftpmaster@ubuntu.com>"
gpgv: Signature made Fri Jan 29 14:31:21 2021 UTC
gpgv:                using RSA key 871920D1991BC93C
gpgv: Good signature from "Ubuntu Archive Automatic Signing Key (2018) <ftpmaster@ubuntu.com>"
Get:6 http://ports.ubuntu.com/ubuntu-ports focal/main Translation-en [506 kB]
Get:7 http://ports.ubuntu.com/ubuntu-ports focal/restricted armhf Packages [7044 B]
Get:8 http://ports.ubuntu.com/ubuntu-ports focal/restricted Translation-en [6212 B]
Get:9 http://ports.ubuntu.com/ubuntu-ports focal/universe armhf Packages [8321 kB]
0% [5 Packages store 0 B] [9 Packages 29.6 kB/8321 kB 0%]gpgv: Signature made Fri Jan 29 14:30:47 2021 UTC
gpgv:                using RSA key 3B4FE6ACC0B21F32
gpgv: Good signature from "Ubuntu Archive Automatic Signing Key (2012) <ftpmaster@ubuntu.com>"
gpgv: Signature made Fri Jan 29 14:30:47 2021 UTC
gpgv:                using RSA key 871920D1991BC93C
gpgv: Good signature from "Ubuntu Archive Automatic Signing Key (2018) <ftpmaster@ubuntu.com>"
Get:10 http://ports.ubuntu.com/ubuntu-ports focal/universe Translation-en [5124 kB]
Get:11 http://ports.ubuntu.com/ubuntu-ports focal/multiverse armhf Packages [116 kB]
Get:12 http://ports.ubuntu.com/ubuntu-ports focal/multiverse Translation-en [104 kB]
Get:13 http://ports.ubuntu.com/ubuntu-ports focal-updates/main armhf Packages [620 kB]
Get:14 http://ports.ubuntu.com/ubuntu-ports focal-updates/main Translation-en [192 kB]
Get:15 http://ports.ubuntu.com/ubuntu-ports focal-updates/restricted armhf Packages [10.1 kB]
Get:16 http://ports.ubuntu.com/ubuntu-ports focal-updates/restricted Translation-en [21.3 kB]
Get:17 http://ports.ubuntu.com/ubuntu-ports focal-updates/universe armhf Packages [583 kB]
Get:18 http://ports.ubuntu.com/ubuntu-ports focal-updates/universe Translation-en [152 kB]
Get:19 http://ports.ubuntu.com/ubuntu-ports focal-updates/multiverse armhf Packages [5340 B]
Get:20 http://ports.ubuntu.com/ubuntu-ports focal-updates/multiverse Translation-en [5076 B]
Get:21 http://ports.ubuntu.com/ubuntu-ports focal-backports/universe armhf Packages [4028 B]
Get:22 http://ports.ubuntu.com/ubuntu-ports focal-backports/universe Translation-en [1448 B]
Get:23 http://ports.ubuntu.com/ubuntu-ports focal-security/main armhf Packages [324 kB]
Get:24 http://ports.ubuntu.com/ubuntu-ports focal-security/main Translation-en [105 kB]
Get:25 http://ports.ubuntu.com/ubuntu-ports focal-security/restricted armhf Packages [6656 B]
Get:26 http://ports.ubuntu.com/ubuntu-ports focal-security/restricted Translation-en [17.6 kB]
Get:27 http://ports.ubuntu.com/ubuntu-ports focal-security/universe armhf Packages [384 kB]
Get:28 http://ports.ubuntu.com/ubuntu-ports focal-security/universe Translation-en [74.5 kB]
Get:29 http://ports.ubuntu.com/ubuntu-ports focal-security/multiverse armhf Packages [1000 B]
Get:30 http://ports.ubuntu.com/ubuntu-ports focal-security/multiverse Translation-en [2876 B]
Fetched 18.2 MB in 7s (2607 kB/s)                                                                                                                             
Reading package lists... Done
root@buildd02:/# apt-get install gdb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  file gdbserver libbabeltrace1 libc6-dbg libcc1-0 libdw1 libelf1 libexpat1 libglib2.0-0 libglib2.0-data libicu66 libmagic-mgc libmagic1 libmpdec2 libmpfr6
  libpython3.8 libpython3.8-minimal libpython3.8-stdlib libreadline8 libsqlite3-0 libssl1.1 libxml2 mime-support readline-common shared-mime-info tzdata
  xdg-user-dirs xz-utils
Suggested packages:
  gdb-doc readline-doc
The following NEW packages will be installed:
  file gdb gdbserver libbabeltrace1 libc6-dbg libcc1-0 libdw1 libelf1 libexpat1 libglib2.0-0 libglib2.0-data libicu66 libmagic-mgc libmagic1 libmpdec2
  libmpfr6 libpython3.8 libpython3.8-minimal libpython3.8-stdlib libreadline8 libsqlite3-0 libssl1.1 libxml2 mime-support readline-common shared-mime-info
  tzdata xdg-user-dirs xz-utils
0 upgraded, 29 newly installed, 0 to remove and 0 not upgraded.
Need to get 28.9 MB of archives.
After this operation, 137 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://ports.ubuntu.com/ubuntu-ports focal/main armhf libmagic-mgc armhf 1:5.38-4 [218 kB]
Get:2 http://ports.ubuntu.com/ubuntu-ports focal/main armhf libmagic1 armhf 1:5.38-4 [68.3 kB]
Get:3 http://ports.ubuntu.com/ubuntu-ports focal/main armhf file armhf 1:5.38-4 [22.4 kB]
Get:4 http://ports.ubuntu.com/ubuntu-ports focal/main armhf libelf1 armhf 0.176-1.1build1 [41.3 kB]
Get:5 http://ports.ubuntu.com/ubuntu-ports focal/main armhf libexpat1 armhf 2.2.9-1build1 [53.3 kB]
Get:6 http://ports.ubuntu.com/ubuntu-ports focal-updates/main armhf libglib2.0-0 armhf 2.64.6-1~ubuntu20.04.1 [1125 kB]
Get:7 http://ports.ubuntu.com/ubuntu-ports focal-updates/main armhf libglib2.0-data all 2.64.6-1~ubuntu20.04.1 [6120 B]
Get:8 http://ports.ubuntu.com/ubuntu-ports focal-updates/main armhf tzdata all 2021a-0ubuntu0.20.04 [295 kB]
Get:9 http://ports.ubuntu.com/ubuntu-ports focal/main armhf libicu66 armhf 66.1-2ubuntu2 [8222 kB]
Get:10 http://ports.ubuntu.com/ubuntu-ports focal/main armhf libmpdec2 armhf 2.4.2-3 [66.8 kB]
Get:11 http://ports.ubuntu.com/ubuntu-ports focal-updates/main armhf libssl1.1 armhf 1.1.1f-1ubuntu2.1 [1082 kB]
Get:12 http://ports.ubuntu.com/ubuntu-ports focal-updates/main armhf libpython3.8-minimal armhf 3.8.5-1~20.04 [705 kB]
Get:13 http://ports.ubuntu.com/ubuntu-ports focal/main armhf mime-support all 3.64ubuntu1 [30.6 kB]
Get:14 http://ports.ubuntu.com/ubuntu-ports focal/main armhf readline-common all 8.0-4 [53.5 kB]
Get:15 http://ports.ubuntu.com/ubuntu-ports focal/main armhf libreadline8 armhf 8.0-4 [109 kB]
Get:16 http://ports.ubuntu.com/ubuntu-ports focal-updates/main armhf libsqlite3-0 armhf 3.31.1-4ubuntu0.2 [467 kB]
Get:17 http://ports.ubuntu.com/ubuntu-ports focal-updates/main armhf libpython3.8-stdlib armhf 3.8.5-1~20.04 [1598 kB]
Get:18 http://ports.ubuntu.com/ubuntu-ports focal/main armhf libxml2 armhf 2.9.10+dfsg-5 [546 kB]
Get:19 http://ports.ubuntu.com/ubuntu-ports focal/main armhf shared-mime-info armhf 1.15-1 [428 kB]
Get:20 http://ports.ubuntu.com/ubuntu-ports focal/main armhf xdg-user-dirs armhf 0.17-2ubuntu1 [46.8 kB]
Get:21 http://ports.ubuntu.com/ubuntu-ports focal-updates/main armhf xz-utils armhf 5.2.4-1ubuntu1 [80.9 kB]
Get:22 http://ports.ubuntu.com/ubuntu-ports focal/main armhf libdw1 armhf 0.176-1.1build1 [211 kB]
Get:23 http://ports.ubuntu.com/ubuntu-ports focal/main armhf libbabeltrace1 armhf 1.5.8-1build1 [137 kB]
Get:24 http://ports.ubuntu.com/ubuntu-ports focal/main armhf libmpfr6 armhf 4.0.2-1 [196 kB]
Get:25 http://ports.ubuntu.com/ubuntu-ports focal-updates/main armhf libpython3.8 armhf 3.8.5-1~20.04 [1394 kB]
Get:26 http://ports.ubuntu.com/ubuntu-ports focal-updates/main armhf gdb armhf 9.2-0ubuntu1~20.04 [2593 kB]
Get:27 http://ports.ubuntu.com/ubuntu-ports focal-updates/main armhf gdbserver armhf 9.2-0ubuntu1~20.04 [171 kB]
Get:28 http://ports.ubuntu.com/ubuntu-ports focal-updates/main armhf libcc1-0 armhf 10.2.0-5ubuntu1~20.04 [34.6 kB]
Get:29 http://ports.ubuntu.com/ubuntu-ports focal-updates/main armhf libc6-dbg armhf 2.31-0ubuntu9.2 [8870 kB]
Fetched 28.9 MB in 6s (4871 kB/s)     
debconf: delaying package configuration, since apt-utils is not installed
E: Can not write log (Is /dev/pts mounted?) - posix_openpt (2: No such file or directory)
Selecting previously unselected package libmagic-mgc.
(Reading database ... 4113 files and directories currently installed.)
Preparing to unpack .../00-libmagic-mgc_1%3a5.38-4_armhf.deb ...
Unpacking libmagic-mgc (1:5.38-4) ...
Selecting previously unselected package libmagic1:armhf.
Preparing to unpack .../01-libmagic1_1%3a5.38-4_armhf.deb ...
Unpacking libmagic1:armhf (1:5.38-4) ...
Selecting previously unselected package file.
Preparing to unpack .../02-file_1%3a5.38-4_armhf.deb ...
Unpacking file (1:5.38-4) ...
Selecting previously unselected package libelf1:armhf.
Preparing to unpack .../03-libelf1_0.176-1.1build1_armhf.deb ...
Unpacking libelf1:armhf (0.176-1.1build1) ...
Selecting previously unselected package libexpat1:armhf.
Preparing to unpack .../04-libexpat1_2.2.9-1build1_armhf.deb ...
Unpacking libexpat1:armhf (2.2.9-1build1) ...
Selecting previously unselected package libglib2.0-0:armhf.
Preparing to unpack .../05-libglib2.0-0_2.64.6-1~ubuntu20.04.1_armhf.deb ...
Unpacking libglib2.0-0:armhf (2.64.6-1~ubuntu20.04.1) ...
Selecting previously unselected package libglib2.0-data.
Preparing to unpack .../06-libglib2.0-data_2.64.6-1~ubuntu20.04.1_all.deb ...
Unpacking libglib2.0-data (2.64.6-1~ubuntu20.04.1) ...
Selecting previously unselected package tzdata.
Preparing to unpack .../07-tzdata_2021a-0ubuntu0.20.04_all.deb ...
Unpacking tzdata (2021a-0ubuntu0.20.04) ...
Selecting previously unselected package libicu66:armhf.
Preparing to unpack .../08-libicu66_66.1-2ubuntu2_armhf.deb ...
Unpacking libicu66:armhf (66.1-2ubuntu2) ...
Selecting previously unselected package libmpdec2:armhf.
Preparing to unpack .../09-libmpdec2_2.4.2-3_armhf.deb ...
Unpacking libmpdec2:armhf (2.4.2-3) ...
Selecting previously unselected package libssl1.1:armhf.
Preparing to unpack .../10-libssl1.1_1.1.1f-1ubuntu2.1_armhf.deb ...
Unpacking libssl1.1:armhf (1.1.1f-1ubuntu2.1) ...
Selecting previously unselected package libpython3.8-minimal:armhf.
Preparing to unpack .../11-libpython3.8-minimal_3.8.5-1~20.04_armhf.deb ...
Unpacking libpython3.8-minimal:armhf (3.8.5-1~20.04) ...
Selecting previously unselected package mime-support.
Preparing to unpack .../12-mime-support_3.64ubuntu1_all.deb ...
Unpacking mime-support (3.64ubuntu1) ...
Selecting previously unselected package readline-common.
Preparing to unpack .../13-readline-common_8.0-4_all.deb ...
Unpacking readline-common (8.0-4) ...
Selecting previously unselected package libreadline8:armhf.
Preparing to unpack .../14-libreadline8_8.0-4_armhf.deb ...
Unpacking libreadline8:armhf (8.0-4) ...
Selecting previously unselected package libsqlite3-0:armhf.
Preparing to unpack .../15-libsqlite3-0_3.31.1-4ubuntu0.2_armhf.deb ...
Unpacking libsqlite3-0:armhf (3.31.1-4ubuntu0.2) ...
Selecting previously unselected package libpython3.8-stdlib:armhf.
Preparing to unpack .../16-libpython3.8-stdlib_3.8.5-1~20.04_armhf.deb ...
Unpacking libpython3.8-stdlib:armhf (3.8.5-1~20.04) ...
Selecting previously unselected package libxml2:armhf.
Preparing to unpack .../17-libxml2_2.9.10+dfsg-5_armhf.deb ...
Unpacking libxml2:armhf (2.9.10+dfsg-5) ...
Selecting previously unselected package shared-mime-info.
Preparing to unpack .../18-shared-mime-info_1.15-1_armhf.deb ...
Unpacking shared-mime-info (1.15-1) ...
Selecting previously unselected package xdg-user-dirs.
Preparing to unpack .../19-xdg-user-dirs_0.17-2ubuntu1_armhf.deb ...
Unpacking xdg-user-dirs (0.17-2ubuntu1) ...
Selecting previously unselected package xz-utils.
Preparing to unpack .../20-xz-utils_5.2.4-1ubuntu1_armhf.deb ...
Unpacking xz-utils (5.2.4-1ubuntu1) ...
Selecting previously unselected package libdw1:armhf.
Preparing to unpack .../21-libdw1_0.176-1.1build1_armhf.deb ...
Unpacking libdw1:armhf (0.176-1.1build1) ...
Selecting previously unselected package libbabeltrace1:armhf.
Preparing to unpack .../22-libbabeltrace1_1.5.8-1build1_armhf.deb ...
Unpacking libbabeltrace1:armhf (1.5.8-1build1) ...
Selecting previously unselected package libmpfr6:armhf.
Preparing to unpack .../23-libmpfr6_4.0.2-1_armhf.deb ...
Unpacking libmpfr6:armhf (4.0.2-1) ...
Selecting previously unselected package libpython3.8:armhf.
Preparing to unpack .../24-libpython3.8_3.8.5-1~20.04_armhf.deb ...
Unpacking libpython3.8:armhf (3.8.5-1~20.04) ...
Selecting previously unselected package gdb.
Preparing to unpack .../25-gdb_9.2-0ubuntu1~20.04_armhf.deb ...
Unpacking gdb (9.2-0ubuntu1~20.04) ...
Selecting previously unselected package gdbserver.
Preparing to unpack .../26-gdbserver_9.2-0ubuntu1~20.04_armhf.deb ...
Unpacking gdbserver (9.2-0ubuntu1~20.04) ...
Selecting previously unselected package libcc1-0:armhf.
Preparing to unpack .../27-libcc1-0_10.2.0-5ubuntu1~20.04_armhf.deb ...
Unpacking libcc1-0:armhf (10.2.0-5ubuntu1~20.04) ...
Selecting previously unselected package libc6-dbg:armhf.
Preparing to unpack .../28-libc6-dbg_2.31-0ubuntu9.2_armhf.deb ...
Unpacking libc6-dbg:armhf (2.31-0ubuntu9.2) ...
Setting up libexpat1:armhf (2.2.9-1build1) ...
Setting up mime-support (3.64ubuntu1) ...
Setting up xdg-user-dirs (0.17-2ubuntu1) ...
Setting up libmagic-mgc (1:5.38-4) ...
Setting up libglib2.0-0:armhf (2.64.6-1~ubuntu20.04.1) ...
No schema files found: doing nothing.
Setting up libssl1.1:armhf (1.1.1f-1ubuntu2.1) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/arm-linux-gnueabihf/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/arm-linux-gnueabihf/perl5/5.30 /usr/share/perl5 /usr/lib/arm-linux-gnueabihf/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/arm-linux-gnueabihf/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
Setting up libsqlite3-0:armhf (3.31.1-4ubuntu0.2) ...
Setting up libmagic1:armhf (1:5.38-4) ...
Setting up file (1:5.38-4) ...
Setting up libc6-dbg:armhf (2.31-0ubuntu9.2) ...
Setting up tzdata (2021a-0ubuntu0.20.04) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/arm-linux-gnueabihf/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/arm-linux-gnueabihf/perl5/5.30 /usr/share/perl5 /usr/lib/arm-linux-gnueabihf/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/arm-linux-gnueabihf/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
Configuring tzdata
------------------

Please select the geographic area in which you live. Subsequent configuration questions will narrow this down by presenting a list of cities, representing the
time zones in which they are located.

  1. Africa  2. America  3. Antarctica  4. Australia  5. Arctic  6. Asia  7. Atlantic  8. Europe  9. Indian  10. Pacific  11. SystemV  12. US  13. Etc
Geographic area: 13

Please select the city or region corresponding to your time zone.

  1. GMT    4. GMT+10  7. GMT+2  10. GMT+5  13. GMT+8  16. GMT-1   19. GMT-12  22. GMT-2  25. GMT-5  28. GMT-8  31. Greenwich  34. Universal
  2. GMT+0  5. GMT+11  8. GMT+3  11. GMT+6  14. GMT+9  17. GMT-10  20. GMT-13  23. GMT-3  26. GMT-6  29. GMT-9  32. UCT        35. Zulu
  3. GMT+1  6. GMT+12  9. GMT+4  12. GMT+7  15. GMT-0  18. GMT-11  21. GMT-14  24. GMT-4  27. GMT-7  30. GMT0   33. UTC
Time zone: 33


Current default time zone: 'Etc/UTC'
Local time is now:      Fri Jan 29 15:30:05 UTC 2021.
Universal Time is now:  Fri Jan 29 15:30:05 UTC 2021.
Run 'dpkg-reconfigure tzdata' if you wish to change it.

Setting up libglib2.0-data (2.64.6-1~ubuntu20.04.1) ...
Setting up libmpfr6:armhf (4.0.2-1) ...
Setting up xz-utils (5.2.4-1ubuntu1) ...
update-alternatives: using /usr/bin/xz to provide /usr/bin/lzma (lzma) in auto mode
update-alternatives: warning: skip creation of /usr/share/man/man1/lzma.1.gz because associated file /usr/share/man/man1/xz.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/unlzma.1.gz because associated file /usr/share/man/man1/unxz.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzcat.1.gz because associated file /usr/share/man/man1/xzcat.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzmore.1.gz because associated file /usr/share/man/man1/xzmore.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzless.1.gz because associated file /usr/share/man/man1/xzless.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzdiff.1.gz because associated file /usr/share/man/man1/xzdiff.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzcmp.1.gz because associated file /usr/share/man/man1/xzcmp.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzgrep.1.gz because associated file /usr/share/man/man1/xzgrep.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzegrep.1.gz because associated file /usr/share/man/man1/xzegrep.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzfgrep.1.gz because associated file /usr/share/man/man1/xzfgrep.1.gz (of link group lzma) doesn't exist
Setting up gdbserver (9.2-0ubuntu1~20.04) ...
Setting up libmpdec2:armhf (2.4.2-3) ...
Setting up libelf1:armhf (0.176-1.1build1) ...
Setting up readline-common (8.0-4) ...
Setting up libcc1-0:armhf (10.2.0-5ubuntu1~20.04) ...
Setting up libdw1:armhf (0.176-1.1build1) ...
Setting up libpython3.8-minimal:armhf (3.8.5-1~20.04) ...
Setting up libicu66:armhf (66.1-2ubuntu2) ...
Setting up libreadline8:armhf (8.0-4) ...
Setting up libbabeltrace1:armhf (1.5.8-1build1) ...
Setting up libpython3.8-stdlib:armhf (3.8.5-1~20.04) ...
Setting up libxml2:armhf (2.9.10+dfsg-5) ...
Setting up libpython3.8:armhf (3.8.5-1~20.04) ...
Setting up shared-mime-info (1.15-1) ...
Setting up gdb (9.2-0ubuntu1~20.04) ...
Processing triggers for libc-bin (2.31-0ubuntu9.2) ...
root@buildd02:/# gdb -ex run --args /bin/id
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /bin/id...
(No debugging symbols found in /bin/id)
Starting program: /usr/bin/id 
warning: /proc is not accessible.
^C
Program received signal SIGINT, Interrupt.
0xf7fd12f4 in ?? () from /lib/ld-linux-armhf.so.3
(gdb) t a a bt

Thread 1 (process 60131):
#0  0xf7fd12f4 in ?? () from /lib/ld-linux-armhf.so.3
#1  0xf7fc81e4 in ?? () from /lib/ld-linux-armhf.so.3
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) quit
A debugging session is active.

	Inferior 1 [process 60131] will be killed.

Quit anyway? (y or n) y
root@buildd02:/# 
```

**Comment by stgraber** [comment]
This log shows the exact same issue reproduced outside of a container on an aarch64 system.
So this implies a kernel/toolchain problem causing this kind of issue when running the 32bit personality on those 64bit systems.

LXD/LXC are properly switching the personality based on the image that's requested by the user and default to the 64bit image when the 32bit image isn't directly requested. So as far as that behavior goes, everything looks correct.

The issue here is really arm64 somehow not behaving as it should when it comes to running a 32bit personality.
I'm not aware of any such issues when running i386 on x86_64 or ppc on ppc64.

**Comment by stgraber** [comment]
@brauner you may find this interesting :)

**Comment by srkunze** [comment]
@stgraber xD

Well, at least reproducible. Where can I file a report on this?

**Comment by stgraber** [comment]
Not sure, maybe reaching out to the kernel arm maintainers would be a good first step?
It may be "expected" due to some weird architectural limitation though but then I would expect there to be some kind of kernel documentation around issues with this personality.

**Comment by wtarreau** [comment]
And I'm thinking that it would also make sense to first try to reproduce this with a mainline kernel, because it could very well be related to one of the thousands patches affecting this rpi kernel. I've never had any issues running armv7 code on an arm64 machine and still cannot reproduce these problems on other ones.

**Comment by stgraber** [comment]
My reproducer above was on an APM X-Gene server using a generic kernel (non-pi) though that's still an older 5.4 kernel with a mountain of cherry-picks done by Ubuntu so a test on pure current mainline would be interesting

**Comment by wtarreau** [comment]
Thanks to your detailed reproducer above, I could also reproduce it here on my macchiatobin which runs mainline 5.4.2 (not updated in a while...).
