### ISSUE TITLE
nil-deref during auto image update

### ISSUE THREAD

**Issue by brauner** [lxc/lxd#8589]
```
DBUG[03-20|17:14:14] Database error: &errors.errorString{s:"No such object"}
EROR[03-20|17:14:14] Failed to get image                      err="No such object"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x90 pc=0x11b7e5a]

goroutine 222154 [running]:
main.autoUpdateImage(0x18df5c0, 0xc0002ccdc0, 0xc000202a80, 0x0, 0x1d, 0x0, 0xc0006672e8, 0x7, 0x18b53e0, 0xc00019c3a0, ...)
        /home/brauner/src/go/src/github.com/lxc/lxd/lxd/images.go:1437 +0x3a
main.autoUpdateImages(0x18df5c0, 0xc0002ccdc0, 0xc000202a80, 0x72e890, 0xc000281810)
        /home/brauner/src/go/src/github.com/lxc/lxd/lxd/images.go:1201 +0x4ca
main.autoUpdateImagesTask.func1.1(0xc00012a400, 0xc000525508, 0x740746)
        /home/brauner/src/go/src/github.com/lxc/lxd/lxd/images.go:1098 +0x3c
github.com/lxc/lxd/lxd/operations.(*Operation).Run.func1(0xc00012a400, 0xc000e3b200)
        /home/brauner/src/go/src/github.com/lxc/lxd/lxd/operations/operations.go:251 +0x4a
created by github.com/lxc/lxd/lxd/operations.(*Operation).Run
        /home/brauner/src/go/src/github.com/lxc/lxd/lxd/operations/operations.go:250 +0x458
```

**Comment by brauner** [comment]
```
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
- instances
- image_types
- resources_disk_sata
- clustering_roles
- images_expiry
- resources_network_firmware
- backup_compression_algorithm
- ceph_data_pool_name
- container_syscall_intercept_mount
- compression_squashfs
- container_raw_mount
- container_nic_routed
- container_syscall_intercept_mount_fuse
- container_disk_ceph
- virtual-machines
- image_profiles
- clustering_architecture
- resources_disk_id
- storage_lvm_stripes
- vm_boot_priority
- unix_hotplug_devices
- api_filtering
- instance_nic_network
- clustering_sizing
- firewall_driver
- projects_limits
- container_syscall_intercept_hugetlbfs
- limits_hugepages
- container_nic_routed_gateway
- projects_restrictions
- custom_volume_snapshot_expiry
- volume_snapshot_scheduling
- trust_ca_certificates
- snapshot_disk_usage
- clustering_edit_roles
- container_nic_routed_host_address
- container_nic_ipvlan_gateway
- resources_usb_pci
- resources_cpu_threads_numa
- resources_cpu_core_die
- api_os
- container_nic_routed_host_table
- container_nic_ipvlan_host_table
- container_nic_ipvlan_mode
- resources_system
- images_push_relay
- network_dns_search
- container_nic_routed_limits
- instance_nic_bridged_vlan
- network_state_bond_bridge
- usedby_consistency
- custom_block_volumes
- clustering_failure_domains
- resources_gpu_mdev
- console_vga_type
- projects_limits_disk
- network_type_macvlan
- network_type_sriov
- container_syscall_intercept_bpf_devices
- network_type_ovn
- projects_networks
- projects_networks_restricted_uplinks
- custom_volume_backup
- backup_override_name
- storage_rsync_compression
- network_type_physical
- network_ovn_external_subnets
- network_ovn_nat
- network_ovn_external_routes_remove
- tpm_device_type
- storage_zfs_clone_copy_rebase
- gpu_mdev
- resources_pci_iommu
- resources_network_usb
- resources_disk_address
- network_physical_ovn_ingress_mode
- network_ovn_dhcp
- network_physical_routes_anycast
- projects_limits_instances
- network_state_vlan
- instance_nic_bridged_port_isolation
- instance_bulk_state_change
- network_gvrp
- instance_pool_move
- gpu_sriov
- pci_device_type
- storage_volume_state
- network_acl
- migration_stateful
- disk_state_quota
- storage_ceph_features
- projects_compression
- projects_images_remote_cache_expiry
- certificate_project
- network_ovn_acl
- projects_images_auto_update
- projects_restricted_cluster_target
- images_default_architecture
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIICFjCCAZygAwIBAgIRAOuwAUOjqQtjO98oIMbfglkwCgYIKoZIzj0EAwMwOjEc
    MBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEaMBgGA1UEAwwRcm9vdEB3aXR0
    Z2Vuc3RlaW4wHhcNMjEwMzAzMTMyNDE0WhcNMzEwMzAxMTMyNDE0WjA6MRwwGgYD
    VQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRowGAYDVQQDDBFyb290QHdpdHRnZW5z
    dGVpbjB2MBAGByqGSM49AgEGBSuBBAAiA2IABDsSRyR/fwnNYZbsVjoVdss5sw1u
    BaNBREmJ1j2Ggrw21Za2p7ymRzi/jgl8AK+v7THRXBTqCnTvyBizBwqzcYudoR2E
    Auu22yGD2NCypJ1KkmGvZpbiL7yMZ3J6uSc4eqNmMGQwDgYDVR0PAQH/BAQDAgWg
    MBMGA1UdJQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAwLwYDVR0RBCgwJoIM
    d2l0dGdlbnN0ZWluhwR/AAABhxAAAAAAAAAAAAAAAAAAAAABMAoGCCqGSM49BAMD
    A2gAMGUCMHGBdyfCKqOgvVz9CMWW3XTZbKzR92/6I+oMyWtxUhxG58RBf8rrRJT0
    h2cra1xk3AIxAOfwLBjIXg6EL8tFQnMaqGPlx96emUDyH+YP8uPjmB0YthBYx1ge
    aoNeR9v+P9eCpw==
    -----END CERTIFICATE-----
  certificate_fingerprint: 087290637548c33904f1dd13fbb38591e3fe2a703494fdde37b9f553b2d9e436
  driver: lxc | qemu
  driver_version: 4.0.0 (devel) | 5.0.0
  firewall: xtables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.8.0-44-generic
  lxc_features:
    cgroup2: "true"
    devpts_fd: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "true"
  os_name: Ubuntu
  os_version: "20.10"
  project: default
  server: lxd
  server_clustered: false
  server_name: wittgenstein
  server_pid: 804898
  server_version: "4.12"
  storage: dir
  storage_version: "1"
  ```

**Comment by stgraber** [comment]
@monstermunchkin any idea why `info` would be nil there?
Maybe we need to do something extra to catch the fact that there is no DB match?
