### ISSUE TITLE
Panic: instances_get 4.x client and master branch

### ISSUE THREAD

**Issue by SimonRichardson** [lxc/lxd#8786]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04 (bionic)
 * The output of "lxc info":

```
lxc info
config:
  core.https_address: '[::]'
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- snapshot_schedule_aliases
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
- instances
- image_types
- resources_disk_sata
- clustering_roles
- images_expiry
- resources_network_firmware
- backup_compression_algorithm
- ceph_data_pool_name
- container_syscall_intercept_mount
- compression_squashfs
- container_raw_mount
- container_nic_routed
- container_syscall_intercept_mount_fuse
- container_disk_ceph
- virtual-machines
- image_profiles
- clustering_architecture
- resources_disk_id
- storage_lvm_stripes
- vm_boot_priority
- unix_hotplug_devices
- api_filtering
- instance_nic_network
- clustering_sizing
- firewall_driver
- projects_limits
- container_syscall_intercept_hugetlbfs
- limits_hugepages
- container_nic_routed_gateway
- projects_restrictions
- custom_volume_snapshot_expiry
- volume_snapshot_scheduling
- trust_ca_certificates
- snapshot_disk_usage
- clustering_edit_roles
- container_nic_routed_host_address
- container_nic_ipvlan_gateway
- resources_usb_pci
- resources_cpu_threads_numa
- resources_cpu_core_die
- api_os
- container_nic_routed_host_table
- container_nic_ipvlan_host_table
- container_nic_ipvlan_mode
- resources_system
- images_push_relay
- network_dns_search
- container_nic_routed_limits
- instance_nic_bridged_vlan
- network_state_bond_bridge
- usedby_consistency
- custom_block_volumes
- clustering_failure_domains
- resources_gpu_mdev
- console_vga_type
- projects_limits_disk
- network_type_macvlan
- network_type_sriov
- container_syscall_intercept_bpf_devices
- network_type_ovn
- projects_networks
- projects_networks_restricted_uplinks
- custom_volume_backup
- backup_override_name
- storage_rsync_compression
- network_type_physical
- network_ovn_external_subnets
- network_ovn_nat
- network_ovn_external_routes_remove
- tpm_device_type
- storage_zfs_clone_copy_rebase
- gpu_mdev
- resources_pci_iommu
- resources_network_usb
- resources_disk_address
- network_physical_ovn_ingress_mode
- network_ovn_dhcp
- network_physical_routes_anycast
- projects_limits_instances
- network_state_vlan
- instance_nic_bridged_port_isolation
- instance_bulk_state_change
- network_gvrp
- instance_pool_move
- gpu_sriov
- pci_device_type
- storage_volume_state
- network_acl
- migration_stateful
- disk_state_quota
- storage_ceph_features
- projects_compression
- projects_images_remote_cache_expiry
- certificate_project
- network_ovn_acl
- projects_images_auto_update
- projects_restricted_cluster_target
- images_default_architecture
- network_ovn_acl_defaults
- gpu_mig
- project_usage
- network_bridge_acl
- warnings
- projects_restricted_backups_and_snapshots
- clustering_join_token
- clustering_description
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 10.125.0.204:8443
  - 192.168.123.1:8443
  - 10.103.52.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFSTCCAzGgAwIBAgIQNjK7hqvYfuL9wFy2t9+PnTANBgkqhkiG9w0BAQsFADA1
    MRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRUwEwYDVQQDDAxyb290QGdy
    dW1waWcwHhcNMjAwNjA0MDQzNTEyWhcNMzAwNjAyMDQzNTEyWjA1MRwwGgYDVQQK
    ExNsaW51eGNvbnRhaW5lcnMub3JnMRUwEwYDVQQDDAxyb290QGdydW1waWcwggIi
    MA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC0VxRyKTj5j519Lwf0w1xSVUtZ
    ATRLGUr0+IUYOKTVqRtrSu/xrg1ufTfTx9HFBYNUbdz1sE9QnZYDu8nkzNn89bz5
    8XW17BfYaW2MCa4+IkYtVtTtuU7MYF0DGhXTFPdCW+04ZhL9FjL0783Av3s0jtDh
    JRE1YT/R/o3X8Gcz2HNjq6PYIWG1oslv51YGagqBhXqOYBXGC8eSb7rGuFjlby6r
    S1WRPDeMYtvhBWrQC2jiyfoZRdjyrbe8vrBxGesKQ86Jjchl7LJTMsGlLOMI2Yn0
    ps1qzvlyS886bFKU7Z+voOq+v+SCBW8JXGL6eplu9SuOBF9XfPgzhyB2k7ywBKd3
    QqhbXLxDZTRrhBSjJulrGMbDuazD8GMjnh6p86zngx6DKcNfwf/NmIQQTndtp71d
    YZ3uBzBfdCmJPoZ17O2jhnWg8Rh5nfcuA+ZWqya2QkP6JIHJ8Q+5vkWBm+PPLjAW
    NbN/kzpcYlf9QHs4v9WajzWNbgmdvsTQqQBZ4QqAEcvIbDGpMhh9T+rehHDlwup8
    +wqsS/UBJH/4GMvNMQzrbxxjP2f1T79jytaogfajHhQDCxLd64kOfim7MqLSpi0o
    TcXbQQfYb7yLXQI6NJQNVDkyTSAjCEUIHXvuU0lleGqU1YPzf8nzVUgWWCLMH0Ga
    s9o92/Vu/jc1D8G4CQIDAQABo1UwUzAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAww
    CgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADAeBgNVHREEFzAVggdncnVtcGlnhwQK
    fQDMhwTAqHsBMA0GCSqGSIb3DQEBCwUAA4ICAQCTWt95zyuWMeADDp5Lmc/aLWFF
    0rnpeMC77ivGi9GqR5tY5maHhuuw3oJdJYnM6a2yUWeiGC4RoyhdlehqH5YNmRUw
    D8pKw1ux3mfTAObUXjLJ+wZ/rCA1gN6PMuq3YOCadWoquzGqszdTa0hUcx7FZoeG
    X5gynaxzheQsj4s92DRPX4qqDhKbejmaxbTFsmSWt0aEs2HICikFwwVLo19LmxTR
    9v1QYMs5k2aLU5VycaiJu29vzwEfSP95SMb7c1F2deJqTZazu57dur6KEIHqrkcc
    o/T5ugPN9RLi81Gmn+BOYoYgbNJHhSKlH311wVMWlTxhZNZXefgQkHtzeLqBJrSM
    TVFBQnuoWGqoUEfVfL08i8X0GUNpJqgl9Exv+df5V+v88J2lVpCPk0ibQs1SZ52N
    2iJosbQCiL4UVF7N9NUnEaePAhuWiutSnkT11Otd0sHAbO2G9KUZ4X5UBG7Oc+kS
    0TzyFYfKqsg+pXddfiLMAvzE1kyOWr7xeZWDDRpwQUFFAjZ5mcQOsGb8jfWLAi+N
    h1AdtswohUtGsl4j6eee6yMCCGjAYvBkUaLPKWdpXLvpb81XMfZuLOiDPHRUFRBo
    UQKGel4XQQjuGyGyvtYYn1SHj7lcm3/xvY19bQVk+pNQfhcHIlErL2iUJse5U4kr
    rQSlg6CLT+8PBS5MYQ==
    -----END CERTIFICATE-----
  certificate_fingerprint: cf512fb5e58b4e19418648d26ff4f49d93e6706dd7de475b6508d47826982699
  driver: qemu | lxc
  driver_version: 5.2.0 | 4.0.9
  firewall: xtables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "false"
    seccomp_listener: "false"
    seccomp_listener_continue: "false"
    shiftfs: "false"
    uevent_injection: "false"
    unpriv_fscaps: "true"
  kernel_version: 4.15.0-140-generic
  lxc_features:
    cgroup2: "true"
    devpts_fd: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "true"
  os_name: Ubuntu
  os_version: "18.04"
  project: default
  server: lxd
  server_clustered: false
  server_name: grumpig
  server_pid: 17000
  server_version: "4.14"
  storage: btrfs | dir | zfs
  storage_version: 4.15.1 | 1 | 0.7.5-1ubuntu16.10
```

# Issue description

Panic in `instances_get` (see stack from journalctl).

```
May 11 10:01:17 dogecoin lxd.daemon[26305]: panic: runtime error: invalid memory address or nil pointer dereference
May 11 10:01:17 dogecoin lxd.daemon[26305]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x188 pc=0x12c1d0b]
May 11 10:01:17 dogecoin lxd.daemon[26305]: goroutine 217797 [running]:
May 11 10:01:17 dogecoin lxd.daemon[26305]: main.doContainersGet.func5(0xc0035d5620, 0xc00068fc80, 0xc0019ac6f0, 0xc001b1b120, 0xc001b1b160, 0xc003065800)
May 11 10:01:17 dogecoin lxd.daemon[26305]:         /build/lxd/parts/lxd/src/.go/src/github.com/lxc/lxd/lxd/instances_get.go:258 +0xcb
May 11 10:01:17 dogecoin lxd.daemon[26305]: created by main.doContainersGet
May 11 10:01:17 dogecoin lxd.daemon[26305]:         /build/lxd/parts/lxd/src/.go/src/github.com/lxc/lxd/lxd/instances_get.go:250 +0xcc5
May 11 10:01:17 dogecoin lxd.daemon[26305]: => LXD failed with return code 2
```

# Steps to reproduce

All the containers are ephemeral, but was wondering why LXD was restarting. After some digging in journalctl I spotted this, I suspect that's the reason.

Code in question has moved from the [4.14 tag](https://github.com/lxc/lxd/blob/lxd-4.14/lxd/instances_get.go#L258), but is still present in the [master branch](https://github.com/lxc/lxd/blob/master/lxd/instances_get.go#L413).

# Information to attach

I can add the following if requested...

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
@SimonRichardson hey, could you provide the following:
 - What command is causing this crash (looks like you're in the recursion < 2 codepath which is unusual)
 - Output of `lxd sql global "SELECT * FROM instances;"`
 - Output of `lxd sql global "SELECT * FROM projects;"`
 - Output of `lxd sql global "SELECT * FROM nodes;"`

**Comment by tomponline** [comment]
@stgraber I'm going to rework that function slightly to protect against possible nils too

**Comment by stgraber** [comment]
Yeah, I'm just not sure in what case you end up not having it in the map, feels like it'd need to be one hell of a race condition, that or we have a DB query bug that's hiding ephemeral instances or something.

**Comment by tomponline** [comment]
> Yeah, I'm just not sure in what case you end up not having it in the map, feels like it'd need to be one hell of a race condition, that or we have a DB query bug that's hiding ephemeral instances or something.

I suppose it is possible for an instance to exist during the call to `GetInstanceNamesByNodeAddress` but subsequently have gone by the the time `instanceLoadNodeProjectAll` is run in a new transaction shortly afterwards.

**Comment by SimonRichardson** [comment]
👍
