### ISSUE TITLE
Linux.zip: lxc execution problem

### ISSUE THREAD

**Issue by 3eka** [lxc/lxd#8853]
# Required information

 * Distribution: RedHat Linux
 * Distribution version: CentOS Linux release 8.3.2011
 * The output of "lxc info" or if that fails:
   * Kernel version: *uname -r*: `4.18.0-240.22.1.el8_3.x86_64`
   * LXC version: ? (*lxc info* fails too, see below)
   * LXD version: `Server version: 4.14`
   * Storage backend in use: ZFS

# Issue description

I have downloaded latest "Client build and unit tests" Linux.zip artifact from https://github.com/lxc/lxd/actions/runs/903979689

Unpacked, *chmod 755 lxc pxd-p2c* and getting this error:
```
./lxc version
panic: list flag redefined: format

goroutine 1 [running]:
github.com/spf13/pflag.(*FlagSet).AddFlag(0xc00030ca00, 0xc000306e60)
        /home/runner/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:848 +0x825
github.com/spf13/pflag.(*FlagSet).VarPF(0xc00030ca00, 0xd4a200, 0xc0001a6c98, 0xc4c1a4, 0x6, 0xc49b49, 0x1, 0xc0002eeea0, 0x1e, 0x1e)
        /home/runner/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:831 +0x10b
github.com/spf13/pflag.(*FlagSet).VarP(...)
        /home/runner/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:837
* github.com/spf13/pflag.(*FlagSet).StringVarP(0xc00030ca00, 0xc0001a6c98, 0xc4c1a4, 0x6, 0xc49b49, 0x1, 0xc4b67e, 0x5, 0xc0002eeea0, 0x1e)
        /home/runner/go/pkg/mod/github.com/spf13/pflag@v1.0.5/string.go:42 +0xad
main.(*cmdStorageVolumeList).Command(0xc0001a6c80, 0xc0001a6c80)
        /home/runner/work/lxd/lxd/lxc/storage_volume.go:1092 +0x405
main.(*cmdStorageVolume).Command(0xc0002f6d60, 0xc0002f6d60)
        /home/runner/work/lxd/lxd/lxc/storage_volume.go:81 +0x5c6
main.(*cmdStorage).Command(0xc000280ee0, 0xc000280ee0)
        /home/runner/work/lxd/lxd/lxc/storage.go:74 +0x532
main.main()
        /home/runner/work/lxd/lxd/lxc/main.go:198 +0x166c
```

# Steps to reproduce

* See above. 
* Version 4.13 is last one worked properly (after download from github).

# Information to attach

* **lxd-p2c** utility, from same _Linux.zip_, outputs version correctly

Regards.

**Comment by tomponline** [comment]
I just tried this locally from the same link as above and `./lxc version` works fine.

Also the stack trace doesn't look right, the part:

```
main.(*cmdStorageVolumeList).Command(0xc0001a6c80, 0xc0001a6c80)
        /home/runner/work/lxd/lxd/lxc/storage_volume.go:1092 +0x405
```

doesn't match up with what is in the code base: 

Line 1092 is empty: https://github.com/lxc/lxd/blob/master/lxc/storage_volume.go#L1092
And cmdStorageVolumeList doesn't start until line 1158: https://github.com/lxc/lxd/blob/master/lxc/storage_volume.go#L1158

Are you certain you're running the copy you think you are?

**Comment by 3eka** [comment]
Hi @tomponline,

I have downloaded same zip file a month ago and utilities are in use on my linux system (was one requirement for **packer** utility -- https://www.packer.io):
```
:; ls -al /home/predrag_zecevic/bin/lx*
-rwxr-xr-x. 1 predrag_zecevic support 19290419 May  6 00:27 /home/predrag_zecevic/bin/lxc
-rwxr-xr-x. 1 predrag_zecevic support 16473813 May  6 00:27 /home/predrag_zecevic/bin/lxd-p2c

:; /home/predrag_zecevic/bin/lxc version
Client version: 4.13
Server version: unreachable

:; /home/predrag_zecevic/bin/lxd-p2c --version
4.13
```
This morning I have tried to use newer versions, and thus get into trouble with **lxc** functionality. Nothing else was changed on system.

Regards.

**Comment by tomponline** [comment]
@3eka I just tried the Linux.zip file from https://github.com/lxc/lxd/actions/runs/903979689 inside a brand new centos 7 VM and it works fine:

```
lxc file push /home/user/Downloads/Linux.zip vcentos7/root/
user@user-MS-7821:~/go/src/github.com/lxc/go-lxc$ lxc shell vcentos7
[root@vcentos7 ~]# yum install unzip
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.cwcs.co.uk
 * centosplus: mirror.as29550.net
 * extras: mirror.freethought-internet.co.uk
 * updates: mirror.as29550.net
Resolving Dependencies
--> Running transaction check
---> Package unzip.x86_64 0:6.0-21.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

============================================================================================================================================
 Package                         Arch                             Version                              Repository                      Size
============================================================================================================================================
Installing:
 unzip                           x86_64                           6.0-21.el7                           base                           171 k

Transaction Summary
============================================================================================================================================
Install  1 Package

Total download size: 171 k
Installed size: 365 k
Is this ok [y/d/N]: y
Downloading packages:
unzip-6.0-21.el7.x86_64.rpm                                                                                          | 171 kB  00:00:00     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : unzip-6.0-21.el7.x86_64                                                                                                  1/1 
  Verifying  : unzip-6.0-21.el7.x86_64                                                                                                  1/1 

Installed:
  unzip.x86_64 0:6.0-21.el7                                                                                                                 

Complete!
[root@vcentos7 ~]# unzip Linux.zip 
Archive:  Linux.zip
  inflating: lxc                     
  inflating: lxd-p2c                 
[root@vcentos7 ~]# ls
Linux.zip  lxc  lxd-p2c
[root@vcentos7 ~]# chmod +x lxc
[root@vcentos7 ~]# ./lxc version
Client version: 4.14
Server version: unreachable
```

Can you try it inside a VM or different machine too please. Also what OS and version are you running?

**Comment by 3eka** [comment]
Hi @tomponline,

hmm, thanks for checking (It might be that my VM -- lxd container, CentOS 8 x86_64 -- is somehow broken).
I will try it on CentOS 8, VirtualBox VM (fully virtualized) and will paste result here soon.

Regards.

**Comment by 3eka** [comment]
Sorry everybody for noise. 
Seems that everything is fine:
```
:; ./lxc --version
4.14
:; ./lxd-p2c --version
4.14
```
I will re-install my VM.
Thanks and best regards.
