### ISSUE TITLE
Panic during network create

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#9511]
https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/5183/arch=amd64,backend=dir,compiler=golang-1.16/console#console-section-3

```
LXC_LOCAL=1 lxc_remote network create lxd402710x
+ set +x
+ eval /lxc-ci/build/tmp.FDjsGkmosu/go/bin/lxc "network" "create" "lxd402710x" --verbose
+ /lxc-ci/build/tmp.FDjsGkmosu/go/bin/lxc network create lxd402710x --verbose
2021/11/10 13:35:07 http: panic serving @: runtime error: invalid memory address or nil pointer dereference
goroutine 1990 [running]:
net/http.(*conn).serve.func1(0xc0001ee3c0)
	/snap/go_116/8632/src/net/http/server.go:1804 +0x153
panic(0x1a01200, 0x295ad10)
	/snap/go_116/8632/src/runtime/panic.go:971 +0x499
database/sql.(*Stmt).Close(0x0, 0x0, 0x0)
	/snap/go_116/8632/src/database/sql/sql.go:2729 +0x3e
github.com/lxc/lxd/lxd/db.networkConfigAdd(0xc00036c380, 0x2, 0x0, 0xc00003b050, 0x1f60020, 0xc000080d10)
	/lxc-ci/build/tmp.FDjsGkmosu/go/src/github.com/lxc/lxd/lxd/db/networks.go:821 +0x3ee
github.com/lxc/lxd/lxd/db.(*ClusterTx).CreateNetworkConfig(...)
	/lxc-ci/build/tmp.FDjsGkmosu/go/src/github.com/lxc/lxd/lxd/db/networks.go:191
main.networksPostCluster.func1(0xc00049e108, 0x0, 0xc00053c6c0)
	/lxc-ci/build/tmp.FDjsGkmosu/go/src/github.com/lxc/lxd/lxd/networks.go:536 +0x3db
github.com/lxc/lxd/lxd/db.(*Cluster).transaction.func1.1(0xc00036c380, 0x1f94770, 0xc000280300)
	/lxc-ci/build/tmp.FDjsGkmosu/go/src/github.com/lxc/lxd/lxd/db/db.go:397 +0x42
github.com/lxc/lxd/lxd/db/query.Transaction(0xc0004e8410, 0xc00090cf48, 0x0, 0x0)
	/lxc-ci/build/tmp.FDjsGkmosu/go/src/github.com/lxc/lxd/lxd/db/query/transaction.go:28 +0x1fb
github.com/lxc/lxd/lxd/db.(*Cluster).transaction.func1(0x47d3cb, 0xc0007ac698)
	/lxc-ci/build/tmp.FDjsGkmosu/go/src/github.com/lxc/lxd/lxd/db/db.go:400 +0x6f
github.com/lxc/lxd/lxd/db/query.Retry(0xc00090d028, 0x0, 0x0)
	/lxc-ci/build/tmp.FDjsGkmosu/go/src/github.com/lxc/lxd/lxd/db/query/retry.go:26 +0xdb
github.com/lxc/lxd/lxd/db.(*Cluster).retry(0xc00048bb80, 0xc00090d028, 0x7f5a2c1d7dd8, 0x8)
	/lxc-ci/build/tmp.FDjsGkmosu/go/src/github.com/lxc/lxd/lxd/db/db.go:418 +0x77
github.com/lxc/lxd/lxd/db.(*Cluster).transaction(0xc00048bb80, 0xc00090d228, 0x41bbf8, 0x8)
	/lxc-ci/build/tmp.FDjsGkmosu/go/src/github.com/lxc/lxd/lxd/db/db.go:394 +0x94
github.com/lxc/lxd/lxd/db.(*Cluster).Transaction(0xc00048bb80, 0xc00090d228, 0x0, 0x0)
	/lxc-ci/build/tmp.FDjsGkmosu/go/src/github.com/lxc/lxd/lxd/db/db.go:357 +0x78
main.networksPostCluster(0xc000442960, 0x1c9634f, 0x7, 0xc00030c500, 0xc00003b050, 0x0, 0x0, 0xc0007be290, 0xa, 0x1c92513, ...)
	/lxc-ci/build/tmp.FDjsGkmosu/go/src/github.com/lxc/lxd/lxd/networks.go:506 +0x3fd
main.networksPost(0xc000442960, 0xc000181500, 0x0, 0x0)
	/lxc-ci/build/tmp.FDjsGkmosu/go/src/github.com/lxc/lxd/lxd/networks.go:414 +0xe25
main.(*Daemon).createCmd.func1.3(0x1d8a0d8, 0xc00012e8e8, 0x0, 0x1f39de0, 0x18fa380)
	/lxc-ci/build/tmp.FDjsGkmosu/go/src/github.com/lxc/lxd/lxd/daemon.go:669 +0x69
main.(*Daemon).createCmd.func1(0x1f8c410, 0xc0002927e0, 0xc000181500)
	/lxc-ci/build/tmp.FDjsGkmosu/go/src/github.com/lxc/lxd/lxd/daemon.go:678 +0x1109
net/http.HandlerFunc.ServeHTTP(0xc00003ac30, 0x1f8c410, 0xc0002927e0, 0xc000181400)
	/snap/go_116/8632/src/net/http/server.go:2049 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0004d83c0, 0x1f8c410, 0xc0002927e0, 0xc000181000)
	/lxc-ci/build/tmp.FDjsGkmosu/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
main.(*lxdHttpServer).ServeHTTP(0xc0004f5540, 0x1f8c410, 0xc0002927e0, 0xc000181000)
	/lxc-ci/build/tmp.FDjsGkmosu/go/src/github.com/lxc/lxd/lxd/api.go:155 +0x89
net/http.serverHandler.ServeHTTP(0xc0003d00e0, 0x1f8c410, 0xc0002927e0, 0xc000181000)
	/snap/go_116/8632/src/net/http/server.go:2867 +0xa3
net/http.(*conn).serve(0xc0001ee3c0, 0x1f947a8, 0xc000a8e540)
	/snap/go_116/8632/src/net/http/server.go:1932 +0x8cd
created by net/http.(*Server).Serve
	/snap/go_116/8632/src/net/http/server.go:2993 +0x39b
Error: Post "http://unix.socket/1.0/networks": EOF
```

**Comment by stgraber** [comment]
@tomponline the `defer stmt.Close()` should be after the error checking, in this case we got an error and therefore a nil `stmt` so calling .Close() on it causes a panic.
