### ISSUE TITLE
Nesting does not seem to function completely. Nested system never reaches multi-user target.

### ISSUE THREAD

**Issue by yurtesen** [lxc/lxd#9729]
# Required information

 * Distribution: Ubuntu 20.04
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-91-generic
   * LXC version: 4.0.8
   * LXD version: 4.0.8
   * Storage backend in use: ZFS

# Issue description

I am trying to execute LXD container inside LXD container.
It does seem to work but the nested container never reach multi-user target.

```
Dec 27 20:17:23 test2 sshd[405]: Server listening on 0.0.0.0 port 22.
Dec 27 20:17:23 test2 sshd[405]: Server listening on :: port 22.
Dec 27 20:17:23 test2 udisksd[395]: Failed to connect to the system message bus
Dec 27 20:17:23 test2 systemd[1]: Started OpenBSD Secure Shell server.
Dec 27 20:17:23 test2 udisksd[395]: udisks daemon version 2.8.4 exiting
Dec 27 20:17:23 test2 systemd[1]: accounts-daemon.service: Succeeded.
Dec 27 20:17:23 test2 systemd[1]: Started Accounts Service.
Dec 27 20:17:23 test2 systemd[1]: udisks2.service: Succeeded.
Dec 27 20:17:23 test2 systemd[1]: Started Disk Manager.
Dec 27 20:17:23 test2 systemd[1]: accounts-daemon.service: Unexpected error response from GetNameOwner(): Connection terminated
Dec 27 20:17:23 test2 systemd[1]: udisks2.service: Unexpected error response from GetNameOwner(): Connection terminated
Dec 27 20:17:23 test2 systemd[1]: systemd-logind.service: Unexpected error response from GetNameOwner(): Connection terminated
Dec 27 20:17:23 test2 systemd-logind[393]: New seat seat0.
Dec 27 20:17:23 test2 networkd-dispatcher[389]: No valid path found for iwconfig
Dec 27 20:17:23 test2 networkd-dispatcher[389]: No valid path found for iw
Dec 27 20:17:23 test2 snapd[391]: AppArmor status: apparmor is enabled and all features are available
Dec 27 20:17:23 test2 networkd-dispatcher[389]: Traceback (most recent call last):
Dec 27 20:17:23 test2 networkd-dispatcher[389]:   File "/usr/bin/networkd-dispatcher", line 497, in <module>
Dec 27 20:17:23 test2 networkd-dispatcher[389]:     init()
Dec 27 20:17:23 test2 networkd-dispatcher[389]:   File "/usr/bin/networkd-dispatcher", line 494, in init
Dec 27 20:17:23 test2 networkd-dispatcher[389]:     main()
Dec 27 20:17:23 test2 networkd-dispatcher[389]:   File "/usr/bin/networkd-dispatcher", line 478, in main
Dec 27 20:17:23 test2 networkd-dispatcher[389]:     dispatcher.register()
Dec 27 20:17:23 test2 networkd-dispatcher[389]:   File "/usr/bin/networkd-dispatcher", line 252, in register
Dec 27 20:17:23 test2 networkd-dispatcher[389]:     bus = dbus.SystemBus()
Dec 27 20:17:23 test2 networkd-dispatcher[389]:   File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 195, in __new__
Dec 27 20:17:23 test2 networkd-dispatcher[389]:     return Bus.__new__(cls, Bus.TYPE_SYSTEM, mainloop=mainloop,
Dec 27 20:17:23 test2 networkd-dispatcher[389]:   File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 102, in __new__
Dec 27 20:17:23 test2 networkd-dispatcher[389]:     bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
Dec 27 20:17:23 test2 networkd-dispatcher[389]:   File "/usr/lib/python3/dist-packages/dbus/bus.py", line 124, in __new__
Dec 27 20:17:23 test2 networkd-dispatcher[389]:     bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
Dec 27 20:17:23 test2 networkd-dispatcher[389]: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Failed to query AppArmor policy: Permission denied
Dec 27 20:17:23 test2 systemd[1]: networkd-dispatcher.service: Main process exited, code=exited, status=1/FAILURE
Dec 27 20:17:23 test2 systemd[1]: networkd-dispatcher.service: Failed with result 'exit-code'.
Dec 27 20:17:23 test2 systemd[1]: Failed to start Dispatcher daemon for systemd-networkd.
Dec 27 20:17:23 test2 systemd[1]: accounts-daemon.service: Unexpected error response from GetNameOwner(): Connection terminated
Dec 27 20:17:23 test2 systemd[1]: udisks2.service: Unexpected error response from GetNameOwner(): Connection terminated
Dec 27 20:17:23 test2 systemd[1]: systemd-logind.service: Unexpected error response from GetNameOwner(): Connection terminated
Dec 27 20:17:25 test2 snapd[391]: AppArmor status: apparmor is enabled and all features are available
Dec 27 20:17:25 test2 snapd[391]: patch.go:63: Patching system state level 6 to sublevel 1...
Dec 27 20:17:25 test2 snapd[391]: patch.go:63: Patching system state level 6 to sublevel 2...
Dec 27 20:17:25 test2 snapd[391]: patch.go:63: Patching system state level 6 to sublevel 3...
Dec 27 20:17:26 test2 snapd[391]: daemon.go:242: started snapd/2.53.2 (series 16; classic) ubuntu/20.04 (amd64) linux/5.4.0-91-generic.
Dec 27 20:17:26 test2 systemd[1]: accounts-daemon.service: Unexpected error response from GetNameOwner(): Connection terminated
Dec 27 20:17:26 test2 systemd[1]: udisks2.service: Unexpected error response from GetNameOwner(): Connection terminated
Dec 27 20:17:26 test2 systemd[1]: systemd-logind.service: Unexpected error response from GetNameOwner(): Connection terminated
```

# Steps to reproduce

 1. Install Ubuntu 20.04 / LXD 4.0.8 using snap 
 2. Start a container  `lxc launch ubuntu:20.04 test -c security.nesting=true -c security.privileged=true` or  `lxc launch ubuntu:20.04 test -c security.nesting=true`
 3. Install LXD using snap inside the container and start another container `lxc launch ubuntu:20.04 test2`

# Information to attach

I am not sure what other information might be relevant.

```
root@test2:~# systemctl list-jobs
JOB UNIT                                 TYPE  STATE
107 unattended-upgrades.service          start waiting
945 systemd-logind.service               start running
135 cloud-init.target                    start waiting
108 systemd-update-utmp-runlevel.service start waiting
1   graphical.target                     start waiting
2   multi-user.target                    start waiting
136 cloud-final.service                  start waiting
104 snapd.seeded.service                 start running
137 cloud-config.service                 start waiting
98  snapd.autoimport.service             start waiting

10 jobs listed.
root@test2:~# uptime
 20:31:24 up 14 min,  0 users,  load average: 0.00, 0.05, 0.07
root@test2:~#
```

By the way, I tried to sign up to the https://discuss.linuxcontainers.org/ but I never received confirmation e-mail. My e-mail address is from hotmail.com is that a problem?

**Comment by yurtesen** [comment]
Nevermind... I had to put
```
lxc profile set default raw.lxc lxc.apparmor.profile=unchanged
```
in parent container.

Explained here: https://linuxcontainers.org/lxc/manpages/man5/lxc.container.conf.5.html

There could be a better user guide explaining the nested containers... Because I have originally found this: https://stgraber.org/2016/04/14/lxd-2-0-lxd-in-lxd-812/ and it is not even mentioned there...
