### ISSUE TITLE
Websocket panic

### ISSUE THREAD

**Issue by turtle0x1** [lxc/lxd#9839]
If I open and close socket connections to LXD at "clicking speed" (hoping between one instance and another) it makes LXD panic.

Debug logs

```
DBUG[01-24|22:28:42] DefaultWriter got error getting next reader err="websocket: close 1005 (no status)"
DBUG[01-24|22:28:42] Got err writing websocket: close sent 
DBUG[01-24|22:28:42] Failed getting exec control websocket reader, killing command project=default instance=c1 PID=700859 interactive=true err="websocket: close 1005 (no status)"
DBUG[01-24|22:28:42] Exec mirror websocket finished           project=default instance=c1 PID=700859 interactive=true number=0
DBUG[01-24|22:28:42] Failed to send SIGKILL signal            project=default instance=c1 PID=700859 interactive=true err="no such process"
DBUG[01-24|22:28:42] Exec control handler finished            project=default instance=c1 PID=700859 interactive=true
DBUG[01-24|22:28:42] Instance process stopped                 project=default instance=c1 PID=700859 interactive=true exitStatus=0
WARN[01-24|22:28:42] Detected poll(POLLNVAL) event. 
panic: send on closed channel

goroutine 14326 [running]:
github.com/lxc/lxd/shared.ExecReaderToChannel.func3()
	/build/lxd/parts/lxd/src/shared/util_linux.go:618 +0x387
created by github.com/lxc/lxd/shared.ExecReaderToChannel
	/build/lxd/parts/lxd/src/shared/util_linux.go:506 +0x225
```

The code that caused / fixed the problem was the following

```
// This is called when a client disconnects from an xterm.js instance
my_connection_to_lxd[0].send(
       "exit\r\n",
      { binary: true },
      () => {
          // NOTE Without the timeout LXD will panic as it tries to send any final responses
          setTimeout(()=>{
              my_connection_to_lxd[0].close();
              my_connection_to_lxd["control"].close();
          }, 100)
      }
    );
```

I also encounter a strange issue with VM channels I suspect is of a similar nature, but I cant (hopefully) verify without #9838

**Comment by turtle0x1** [comment]
Similar error on spice VGA socket, though this one doesn't panic

```
DBUG[01-24|23:43:50] Connected websocket Operation: 18f0a70d-8027-4b74-af4a-2f40af142c42 
DBUG[01-24|23:43:50] VGA dynamic websocket connected 
DBUG[01-24|23:43:50] Handled websocket Operation: 18f0a70d-8027-4b74-af4a-2f40af142c42 
DBUG[01-24|23:43:54] Got error getting next reader websocket: close 1005 (no status) 
DBUG[01-24|23:43:54] VGA control websocket finished 
DBUG[01-24|23:43:54] DefaultWriter got error getting next reader err="read tcp 127.0.0.1:8443->127.0.0.1:43788: use of closed network connection"
DBUG[01-24|23:43:54] Sending write barrier 
DBUG[01-24|23:43:54] DefaultWriter got error getting next reader err="read tcp 127.0.0.1:8443->127.0.0.1:43800: use of closed network connection"
DBUG[01-24|23:43:54] Sending write barrier 
DBUG[01-24|23:43:54] DefaultWriter got error getting next reader err="read tcp 127.0.0.1:8443->127.0.0.1:43806: use of closed network connection"
DBUG[01-24|23:43:54] Sending write barrier 
DBUG[01-24|23:43:54] VGA websocket finished 
DBUG[01-24|23:43:54] Success for websocket operation: 18f0a70d-8027-4b74-af4a-2f40af142c42 
```

**Comment by stgraber** [comment]
@tomponline FYI, I've got a branch which completely rewrites our websocket logic, makes it all pure Go and moves it to a new `shared/ws` package. So far I've confirmed that it's working well for text console, vga console, interactive exec and non-interactive exec.

It however has issues when dealing with migration streams so there's a bit of work left to do to track that down before I can put it up for review.

**Comment by stgraber** [comment]
https://github.com/stgraber/lxd/tree/websocket

**Comment by tomponline** [comment]
Cool that would be nice to remove some of that complicated c based copying logic which ive not had time to fully comprehend. Look forward to PR!

**Comment by tomponline** [comment]
@turtle0x1 that should fix it ^
