### ISSUE TITLE
LXD invalid memory address or nil pointer dereference within DQLite library

### ISSUE THREAD

**Issue by richard-hajek** [lxc/lxd#9908]
# Required information

 * Distribution: Arch Linux
 * Distribution version: Rolling at 12.02.2022 ( DD.MM.YYYY)
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.15.16-1-aufs https://aur.archlinux.org/packages/linux-aufs
   * LXC version: 4.0.12, ABI: 1.7.0
   * LXD version: Client Version: 4.22
   * Storage backend in use: Directory?

# Issue description

`lxd -dv` results in a crash with internal error:

```
DBUG[02-12|11:11:31] Connecting to a local LXD over a Unix socket 
DBUG[02-12|11:11:31] Sending request to LXD                   method=GET url=http://unix.socket/1.0 etag=
INFO[02-12|11:11:31] LXD is starting                          version=4.22 mode=normal path=/var/lib/lxd
DBUG[02-12|11:11:31] Unknown backing filesystem type: 0x61756673 
INFO[02-12|11:11:31] Kernel uid/gid map: 
INFO[02-12|11:11:31]  - u 0 0 4294967295 
INFO[02-12|11:11:31]  - g 0 0 4294967295 
INFO[02-12|11:11:31] Configured LXD uid/gid map: 
INFO[02-12|11:11:31]  - u 0 1000000 1000000000 
INFO[02-12|11:11:31]  - g 0 1000000 1000000000 
WARN[02-12|11:11:31] AppArmor support has been disabled because of lack of kernel support 
INFO[02-12|11:11:31] Kernel features: 
INFO[02-12|11:11:31]  - closing multiple file descriptors efficiently: yes 
INFO[02-12|11:11:31]  - netnsid-based network retrieval: yes 
INFO[02-12|11:11:31]  - pidfds: yes 
INFO[02-12|11:11:31]  - core scheduling: yes 
INFO[02-12|11:11:31]  - uevent injection: yes 
INFO[02-12|11:11:31]  - seccomp listener: yes 
INFO[02-12|11:11:31]  - seccomp listener continue syscalls: yes 
INFO[02-12|11:11:31]  - seccomp listener add file descriptors: yes 
INFO[02-12|11:11:31]  - attach to namespaces via pidfds: yes 
INFO[02-12|11:11:31]  - safe native terminal allocation : yes 
INFO[02-12|11:11:31]  - unprivileged file capabilities: yes 
INFO[02-12|11:11:31]  - cgroup layout: hybrid 
WARN[02-12|11:11:31]  - AppArmor support has been disabled, Disabled because of lack of kernel support 
WARN[02-12|11:11:31]  - Couldn't find the CGroup blkio.weight, disk priority will be ignored 
INFO[02-12|11:11:31]  - shiftfs support: no 
INFO[02-12|11:11:31]  - idmapped mounts kernel support: yes 
INFO[02-12|11:11:31] Initializing local database 
DBUG[02-12|11:11:31] Refreshing local trusted certificate cache 
INFO[02-12|11:11:31] Set client certificate to server certificate fingerprint=cdfdcab6239bd6969e1998d4ac9a011468e9da0eac5e1ccc4fefcbc9eba6eae5
DBUG[02-12|11:11:31] Initializing database gateway 
INFO[02-12|11:11:31] Starting database node                   id=1 local=1 role=voter
INFO[02-12|11:11:31] Daemon stopped 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xd08 pc=0x5565af5f7a4e]

goroutine 1 [running]:
github.com/canonical/go-dqlite/internal/bindings._Cfunc_GoString(...)
	_cgo_gotypes.go:102
github.com/canonical/go-dqlite/internal/bindings.NewNode(0x5565af65f707, {0x5565b09d5198, 0x1}, {0xc000124b40, 0x1c})
	github.com/canonical/go-dqlite@v1.10.3-0.20220104182624-3491db06d32b/internal/bindings/server.go:127 +0x105
github.com/canonical/go-dqlite.New(0x1, {0x5565b09d5198, 0xc000040140}, {0xc000124b40, 0x1c}, {0xc000687090, 0x1, 0xc000687068})
	github.com/canonical/go-dqlite@v1.10.3-0.20220104182624-3491db06d32b/node.go:70 +0xb5
github.com/lxc/lxd/lxd/cluster.(*Gateway).init(0xc00029c380, 0x0)
	github.com/lxc/lxd/lxd/cluster/gateway.go:764 +0x6ca
github.com/lxc/lxd/lxd/cluster.NewGateway({0x5565b0de3bc0, 0xc00040ffc0}, 0xc000318078, 0xc0000f4000, 0xc000401aa0, {0xc000687638, 0x2, 0xc00050f4b0})
	github.com/lxc/lxd/lxd/cluster/gateway.go:65 +0x277
main.(*Daemon).init(0xc00016a000)
	github.com/lxc/lxd/lxd/daemon.go:1020 +0x1a9b
main.(*Daemon).Init(0xc00016a000)
	github.com/lxc/lxd/lxd/daemon.go:745 +0x5f
main.(*cmdDaemon).Run(0xc00040cd98, 0xc00050fc58, {0xc000401a30, 0x0, 0x0})
	github.com/lxc/lxd/lxd/main_daemon.go:78 +0x5b0
github.com/spf13/cobra.(*Command).execute(0xc00044aa00, {0xc00003c070, 0x1, 0x1})
	github.com/spf13/cobra@v1.3.0/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc00044aa00)
	github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.3.0/command.go:902
main.main()
	github.com/lxc/lxd/lxd/main.go:226 +0x1acd
```

# Steps to reproduce

Unknown, on my system it appears to always crash.

# Information to attach

- No apparent relevant dmesg output
- No container as daemon failed to launch
- My `root` filesystem is rebind mounted ( i.e. has `filesystem == none` )

Output of df -h

```
Filesystem                          Size  Used Avail Use% Mounted on
dev                                 5.8G     0  5.8G   0% /dev
run                                 5.8G  1.7M  5.8G   1% /run
none                                196G  324M  186G   1% /
/dev/mapper/ssdgroup-pkg            147G   52G   88G  38% /aufs/layers/pkg
/dev/mapper/ssdgroup-config         9.8G   43M  9.3G   1% /aufs/layers/config
/dev/mapper/ssdgroup-runtime        196G  324M  186G   1% /aufs/layers/runtime
/dev/mapper/ssdgroup-games_pkg       98G   32K   93G   1% /aufs/layers/gpkg
/dev/mapper/ssdgroup-games_runtime   98G  1.2G   92G   2% /aufs/layers/gruntime
none                                9.8G   43M  9.3G   1% /aufs/stacks/config
none                                 98G  1.2G   92G   2% /aufs/stacks/gaming
tmpfs                               5.8G     0  5.8G   0% /dev/shm
tmpfs                               4.0M     0  4.0M   0% /sys/fs/cgroup
tmpfs                               5.8G   28K  5.8G   1% /tmp
/dev/sda1                            16G  156M   16G   1% /boot
/dev/mapper/ssdgroup-home           167G  131G   28G  83% /home
tmpfs                               1.2G   40K  1.2G   1% /run/user/1000
```

Output of various package information

```
➜  ~ pacman -Q  | grep lx  
lxc 1:4.0.12-1
lxcfs 4.0.12-1
lxd 4.22-1
python-lxml 4.7.1-1
```

```
➜  ~ pacman -Q | grep ql 
dqlite 1.9.1-1
postgresql 13.4-6
postgresql-libs 13.4-6
sqlite 3.37.2-1
```

**Comment by richard-hajek** [comment]
Possibly related to #9189, unfortunately I do not know how to check whether this kernel supports AIO and Google has failed me.

**Comment by stgraber** [comment]
Unfortunately we can't move issues across organizations, would you mind filing this one again at https://github.com/canonical/go-dqlite?

**Comment by stgraber** [comment]
(Closing as not a LXD bug)
